### ISSUE TITLE
Support latest Iris 3.8

### ISSUE THREAD

**Issue by heikoklein** [metno/pyaerocom#1019]
**Is your feature request related to a problem? Please describe.**
Conda upgraded on 29.02.2024 to 3.8, which deprecates several functions and makes pyaerocom-tests fail. Therefore pyaerocom has been restricted to >=3.6, <3.8. Newer Iris versions should be supported in the future.

**Describe the solution you would like to see**
pyaerocom CI tests don't fail with latest Iris.

**Comment by jgriesfeller** [comment]
According to the iris documentation they did not deprecate anything since iris 3.5. Strange that this comes up now.

**Comment by heikoklein** [comment]
Looks like they changed the warning categories:
```warnings.warn(wmsg, category=iris.exceptions.IrisUserWarning)```

**Comment by lewisblake** [comment]
Example Error:

```console
ERROR tests/aeroval/test_utils.py::test_compute_model_average_and_diversity_error[None-False-None-invalid input, need ExperimentProcessor] - iris._deprecation.IrisDeprecation: Saving to netcdf with legacy-style attribute handling for backwards compatibility.
This mode is deprecated since Iris 3.8, and will eventually be removed.
Please consider enabling the new split-attributes handling mode, by setting 'iris.FUTURE.save_split_attrs = True'.
```

**Comment by heikoklein** [comment]
`iris.FUTURE.save_split_attrs` in `tests/fixtures/aeroval/common.py` does not exist in iris 3.7.0:
`AttributeError: 'Future' object has no attribute 'save_split_attrs'`

Tests with iris 3.7.0 all fail now. Bump version to 3.8 or fix.

**Comment by jgriesfeller** [comment]
Very strange. I thought I had tested that. But I did not test it with a complete recreation of the runtime environment.
