### ISSUE TITLE
Preferred order to be used for countries 

### ISSUE THREAD

**Issue by AugustinMortier** [metno/pyaerocom#102]
var regions = [
                'WORLD',
                'Denmark', 'Sweden', 'Norway', 'Finland', 'Svalbard and Jan Mayen', 'Iceland',
                'Ireland', 'United Kingdom', 'Belgium', 'Netherlands', 'France', 'Germany', 'Austria', 'Switzerland', 'Luxembourg', 'Andorra',
                'Poland', 'Hungary', 'Czech Republic', 'Slovakia', 'Romania', 'Estonia', 'Latvia', 'Belarus', 'Ukraine', 'Moldova', 'Russian Federation',
                'Slovenia', 'Croatia', 'Bosnia and Herzegovina', 'Montenegro', 'Albania', 'Macedonia', 'Bulgaria', 'Serbia', 'Greece',
                'Spain', 'Italy', 'Portugal', 'Malta', 'Holy Sea (Vatican City State)', 'Gibraltar', 'San Marino', 'Cypros',
                'Turkey', 'Armenia', 'Georgia'
                        ]

**Comment by avaldebe** [comment]
@AugustinMortier is this related to #582?
