### ISSUE TITLE
Invalid usage of DATA_ID in ReadGhost (after recent update in base class)

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#103]
Recent update in `ReadUngriddedBase` related to access of `DATA_ID` (via new decorator method `data_id`) was not migrated into `ReadGhost` and all usages of `DATA_ID` need to be replaced with new method `data_id` instead. 

This leads to invalid values related to assignment of `ts_type` (always daily) and also to assignment of the data ID in the when reading the files as value of `ReadGhost.DATA_ID` is now always 'GHOST.daily` (default) and `ReadGhost.data_id` should be used instead.

This may explain the inconsistent results related to constrained time resampling from hourly to daily mentioned in #101.

**Comment by jgliss** [comment]
@hansbrenna this bug may explain the appearance of daily datapoints even for sites / days where less than 6 hourly values are abundant. I have this bug already fixed locally and will see if this could explain the behaviour.

**NOTE**: since I modify `ReadGhost` this will trigger a reload of all the cached data that you have. And I think it is good advice to do this reload in any case.

**Comment by hansbrenna** [comment]
Thanks @jgliss. Though I'm not sure I understood the implications for any of our current results. I will of course re-load the GHOST data and re-run everything.

**Comment by jgliss** [comment]
Yes, I am also not entirely sure about the implications but what most likely happened is that when colocating to `ts_type=daily` is that it thought the observations were already daily and then just resampled without any constrained. Which would explain why cases like Tirilä Pekkasenkatu occurred. So probably / hopefully only minor implications for the results...
