### ISSUE TITLE
Pya browse for ungridded observations is broken. 

### ISSUE THREAD

**Issue by Ovewh** [metno/pyaerocom#1038]
**Describe the bug**
Please provide a clear and concise description of what the bug is.
 - Pyaerocom version: 0.16.0
 - Computing platform: All
 - Configuration file (if applicable):
 - Error message (if applicable): Reading failed for AeronetSunV3Lev2.daily. Error: TypeError("ReadUngridded.get_lowlevel_reader() got an unexpected keyword argument 'config'")

**To Reproduce**
1. pya browse " AeronetSunV3Lev2.daily"

**Expected behavior**
Give a list of variables and year which the observations are available

**Additional context**
Probably something that went between the cracks during the pyaero integration. 

The issue is this [function call](https://github.com/metno/pyaerocom/blob/8ff495b5daa6fe20cb999ca5fb7bc41733ab566c/pyaerocom/io/readungridded.py#L272)

**Comment by dulte** [comment]
#1039

**Comment by dulte** [comment]
Should be fixed with the PR above. Closing issue
