### ISSUE TITLE
Check if GHOST.daily contains different sites than GHOST.hourly (pm10, pm2.5)

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#104]
From CAMS61 meeting on 7.5. it was brought up that some sites are missing (e.g. France, Netherlands) when only using GHOST.hourly. Should be checked if both datasets need to be combined. So far we assumed that GHOST.daily contains the same data as GHOST.hourly but maybe that is not the case...

**Comment by hansbrenna** [comment]
These are the concpm25 stations before any filtering of outliers or invalid data for GHOST.daily and GHOST.hourly respectively. As you can see they are quite different.

**GHOST.daily**
![ghost_daily_concpm25_station_coords](https://user-images.githubusercontent.com/12746882/81303422-f5f3e380-907b-11ea-83d1-5e4ca1e0be6b.png)
**GHOST.hourly**
![ghost_hourly_concpm25_station_coords](https://user-images.githubusercontent.com/12746882/81303427-f68c7a00-907b-11ea-9a09-45fc2b553232.png)

**Comment by hansbrenna** [comment]
@jgliss This problem might be fixed by an update of the data set. On the other hand, is there a way to actually merge two ungridded datasets in pyaerocom?

**Comment by jgliss** [comment]
@hansbrenna yes, I saw the email from Dene, but if I understood correctly from the discussion around providing monthly, it seems that the different datasets for the different time resolutions in GHOST may contain partly different sites (or data). But we need to check with him if this is the case. In which case, pyaerocom would need to read both GHOST.daily and GHOST.hourly together into one `UngriddedData` object to be used for colocation. Merging is easy, either read both directly:

```python
data = pya.io.ReadUngridded().read(['GHOST.daily', 'GHOST.hourly'], 'concpm25')
```

or if you have both in memory:


```python
daily = pya.io.ReadUngridded().read('GHOST.daily', 'concpm25')
hourly = pya.io.ReadUngridded().read('GHOST.hourly', 'concpm25')
merged = daily.merge(hourly)
```

You can also use the *&* operator:

```python
merged = daily & hourly
```

The merged dataset will contain all data from both datasets. If you then call `to_station_data` for one of the sites (in the colocation routine, `to_station_data` is called for all sites), and if the corresponding site and variable exists both in daily and hourly resolution, the output `StationData` object will be in the lowest available (i.e. daily, hence the hourly data will be resampled to daily) and based on that (lowest) time resolution, overlaps in time will be identified and removed.

**Comment by hansbrenna** [comment]
I tried this earlier, but it failed (see code and error below)

```
#test of merging of GHOST data                                                                                                                                                                              
import pyaerocom as pya

print('reading ungridded data...')
daily = pya.io.ReadUngridded().read('GHOST.daily','concpm25')
hourly = pya.io.ReadUngridded().read('GHOST.hourly','concpm25')

print('merging ungridded data')
combined = daily.merge(hourly)
del daily
del hourly

combined.set_flags_nan(inplace=True)
# combined = combined.remove_outliers('concpm25')                                                                                                                                                           

print('reading model data')
ens = pya.io.ReadGridded('ENSEMBLE.cams61.day1')
ens_pm25 = ens.read('concpm25',start=2018,stop=2019,vert_which='Surface')[0]

('colocating...')
colocated_data = pya.colocation.colocate_gridded_ungridded(ens_pm25, combined, remove_outliers=True,start=2018,
stop=2019,ts_type='daily',var_ref='concpm25')

```

`AttributeError: Colocation can only be performed with ungridded data objects that only contain a single dataset. Use method `extract_dataset` of UngriddedData object to extract single datasets`

**Comment by jgliss** [comment]
Okay, I was referring to your question whether `UngriddedData` objects can be merged (which they can, as you already found out). 
What you are referring to now is a different problem, i.e. colocating `UngriddedData` objects that contain more than one dataset. I will look into this but should not be too hard to fix I hope. But please try to be more specific in the future wrt. to the actual problem.

**Comment by jgliss** [comment]
I think this can be closed, the answer is yes, different resolutions of same variables in GHOST may have differences in sites available.
