### ISSUE TITLE
is this typo a bug?

### ISSUE THREAD

**Issue by avaldebe** [metno/pyaerocom#1046]
https://github.com/metno/pyaerocom/blob/f4f5c3b0823b91a03eff9d2975d8fa8bb95b4d07/pyaerocom/colocation_auto.py#L1359-L1361

``` python
     vertical_layer = coldata.vertical_layer 
#      ^ missing "r"
```

**Comment by lewisblake** [comment]
> is this typo a bug?

Yes. Thanks for catching. I will submit a PR.
