### ISSUE TITLE
is this a bug? or it is masking a bug elsewhere?

### ISSUE THREAD

**Issue by avaldebe** [metno/pyaerocom#1047]
https://github.com/metno/pyaerocom/blob/f4f5c3b0823b91a03eff9d2975d8fa8bb95b4d07/pyaerocom/vert_coords.py#L446-L448

`if` clause does nothing, I suspect that this was supposed to be something like

``` python
 for coord in coord_list: 
     if coord in self: 
         continue
```

but I do not know enough about this module to say for certain

**Comment by lewisblake** [comment]
Probably it is (1) covering a bug elsewhere and (2) supposed to be what you suggest. I will submit a PR for to cover (2). (1) will need to be addressed in subsequent PRs defining classes more rigorously.
