### ISSUE TITLE
geodesy tests are broken or outdated

### ISSUE THREAD

**Issue by avaldebe** [metno/pyaerocom#1050]
**Describe the bug**
 - Pyaerocom version: 0.16.0 from main-dev
 - Computing platform: local machine (Ubuntu 22.04.4 LTS) and PPI rhel8 (Red Hat Enterprise Linux release 8.8)
 - Error message:
    ```
    FAILED tests/test_geodesy.py::test_etopo_altitude - FileNotFoundError: [Errno 2] No such file or directory: '/home/lewisb/.geonum/ETOPO1_Ice_g_gmt4.grd'
    ```

**To Reproduce**
``` bash
# create and activate new virtual environment
python3.10 -m venv --prompt pya-py310 .venv --upgrade-deps
source .venv/bin/activate

# install working version, on editable mode
pip install -e .[test]

# run broken/outdated test
pytest tests/test_geodesy.py::test_etopo_altitude 
```

**Expected behavior**
I expect the test to pass locally, or be labeled as broken/outdated with an `pytest.xfailed` decorator.

**Comment by thorbjoernl** [comment]
It looks like the `test_geodesy.py` error is caused the pypi release of [geonum](https://github.com/jgliss/geonum), not pyaerocom:

In geonum's `Etopo1Access` constructor the local path is always set to the geonum default which is `/home/USER/.geonum/...` even if the local_path argument is set to override.

```python
    def __init__(self, local_path=None, file_name=None, check_access=False,
                 search_database=True):

        if not NETCDF_AVAILABLE:
            raise ModuleNotFoundError("Etopo1Access class cannot be initiated. "
                                      "Please install netCDF4 library first")
        self._local_path = LOCAL_TOPO_DIR
        #[...]
```

I'm confused as this appears to already be fixed [upstream](https://github.com/jgliss/geonum/blame/main-dev/geonum/topoaccessbase.py#L223) and that line of code hasn't been changed in 3 years.
