### ISSUE TITLE
pyaerocom gives warnings about files not being in metastandards version

### ISSUE THREAD

**Issue by heikoklein** [metno/pyaerocom#1067]
**Describe the bug**
Please provide a clear and concise description of what the bug is.
 - Pyaerocom version: 0.16
 - Error message (if applicable):
```
pyaerocom.metastandards:INFO:Invalid or old data ID ECMWF_CAMS_REAN. Consider format <model-name>-<meteo-config>_<experiment>-<perturbation>
```
This info message is confusing and not real since metastandards are not enforced in pyaerocom yet, and 4 different standards are possible while only one is tested.

**To Reproduce**
`python cfg_benchmark.py`

**Expected behavior**
No INFO/warning should be given on default, DEBUG-message still possible.

**Comment by Ovewh** [comment]
I think the `"Meteorology config substring in data_id {meteo} needs to start with met."` warming should also only be a DEBUG message not warning. Since this is also not enforced.
