### ISSUE TITLE
Wrong logic in mathutils.calc_statistics()`

### ISSUE THREAD

**Issue by thorbjoernl** [metno/pyaerocom#1112]
The logic in `mathutils.calc_statistics`seems subtly wrong (or at least undocumented).

https://github.com/metno/pyaerocom/blob/913db174b59c255a60ce8262c111287b963ce8f2/pyaerocom/mathutils.py#L251

Identified issues:
- Calculations of multiple statistics do not take into account constraints given by `lowlim` or `highlim` (For example `totnum`, `num_valid`, `data_mean`/std, ...)
- This breaks the check for `min_num_valid` since it is based on the unconstrained data count.

**Comment by lewisblake** [comment]
Outlier removal typically takes place in the reader (it is debatable whether it should). I think this is reason the only place the `lowlim` and `highlim` in the call to this function within `plotting`, which is functionally unsupported. I agree, this is not well documented though, and probably the rewrite of this function should make this more clear.
