### ISSUE TITLE
Enforcing common whitespace standard

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#112]
Since editors handles whitespace differently some of my commits ends up as huge changes when my editor strips all whitespace at the end of a line, ensures that all blank lines have no whitespace and so on. This makes the review process a bit cumbersome. Should we have a common whitespace standard, or are there any other good solutions for these problems?

**Comment by jgliss** [comment]
Very good point indeed!! I think it is desirable to have the editor handle it the way your editor is doing it! I use spyder and need to check if this can be enforced there too. In the mean time, I think it should work to at `?w=1` at the end of the github URL of the diff view:

https://stackoverflow.com/questions/37007300/how-to-ignore-whitespace-in-github-when-comparing

**Comment by ejgal** [comment]
That's a nice workaround for the github part. Locally this is not so straightforward, one [solution](https://stackoverflow.com/questions/3515597/add-only-non-whitespace-changes) I found was `git diff -U0 -w --no-color | git apply --cached --ignore-whitespace --unidiff-zero - `

Setting for stripping extra whitespace in spyder:
`Preferences -> Editor -> Source code: Automatically remove trailing spaces when saving files`

**Comment by ejgal** [comment]
I will look for a script that strips all the extra whitespace throughout the code and test it in a new branch. Hopefully we can merge a cleaned version into v090dev soon.

As we talked about earlier today it would be nice if this in the future can be checked with github action on each push.

**Comment by ejgal** [comment]
This is the script used for stripping the whitespace.

```bash
#!/bin/bash -x

# Strips whitespace from all files ending with .EXTENSIONS and stage them
# Install sponge with apt install moreutils

shopt -s globstar
EXTENSIONS=(py ini)

for extension in ${EXTENSIONS[@]}; do
  for file in  **/*."$extension"; do
    git stripspace < "$file" | sponge "$file"
  done
  git add **/*."$extension"
done
```

**Comment by ejgal** [comment]
I think this can be closed for now. Haven't had any problems merging recently.
