### ISSUE TITLE
Allow setting variable specific obsdatasets in web-tools config

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#114]
Currently, observation configuration for one dataset for web processing is set e.g. as follows:

```python
CFG = dict(
...
obs_config = {

'GHOST'        :   dict(obs_id='GHOST.hourly',
                             obs_vars=['concpm25','conco3'],
                             obs_vert_type='Surface',
                             obs_filters=dict(set_flags_nan=True)),
}
)
```

In order to be more flexible, `obs_id` could also be a variable specific dictionary, so the following would work:

```python
CFG = dict(
...
obs_config = {

'GHOST'        :   dict(obs_id={'concpm25' : 'GHOST.daily', 'conco3' : 'GHOST.hourly'},
                             obs_vars=['concpm25','conco3'],
                             obs_vert_type='Surface',
                             obs_filters=dict(set_flags_nan=True)),
}
)
```

Not sure how much work that is in implementation of `Colocator` class, but my feeling is that it should be rather quick to fix and would enable processing of O3max (from hourly dataset) together with other GHOST variables that use the daily datasets.

**Comment by ejgal** [comment]
How is this coming along?

**Comment by jgriesfeller** [comment]
obsoleted by aeroval. Closing this issue.
