### ISSUE TITLE
Add CI-tests with minimum versions of main libraries

### ISSUE THREAD

**Issue by heikoklein** [metno/pyaerocom#1153]
**Is your feature request related to a problem? Please describe.**
pyaerocom has tests for the latest 3 python versions, while the main libraries, e.g. pandas, xarray, numpy require the latest version. pyaerocom should not require the latest version at all times, but allow for about 3 years of backward compatibility. E.g. the currently latest supported python version (3.10), xarray 2022.04 and pandas 1.5 should currently be supported for this year.

This should be implemented before #1066 .
This is related to #1140 and #1141 .

**Describe the solution you would like to see**
pyaerocom should be able to work with slightly older versions of the main libraries, as well as the newest versions.

**Comment by thorbjoernl** [comment]
Issue of interest: https://github.com/pypa/pip/issues/8085

In jupyter they generate a separate requirements.txt file automatically for this purpose. Maybe we can steal it. 
https://github.com/jupyterhub/jupyterhub/blob/main/ci/oldest-dependencies/requirements.in
