### ISSUE TITLE
Filtering metadata of type float with a list of 3 or more specific values fails

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#118]
I'm trying to use the Joly-Peuch classification codes to filter the new GHOST.EEA data, but all filters using a list with 3 or more values to filter a metadata variable with type `float` fails in the same way. I've tried with a few other metadata variables in addition to the Joly-Peuch classification.

Using 3 or more items in the list works for "standardised_network_provided_area_classification" where the data type is string.

See example code below.

```
import pyaerocom as pya
test= pya.io.ReadUngridded()
eea=test.read('GHOST.EEA.daily','concpm25',)

#filters that work
eea.filter_by_meta(standardised_network_provided_area_classification= ['rural','rural-near_city','rural-regional','rural-remote'])
eea.filter_by_meta(Joly_Peuch_classification_code=1)
eea.filter_by_meta(Joly_Peuch_classification_code=[1,3])
eea.filter_by_meta(distance_to_kerb=10)
eea.filter_by_meta(distance_to_kerb=[1,10])

#Filters that fail with message: Input filters {filter_attributes} result in unchanged data object
eea.filter_by_meta(Joly_Peuch_classification_code=[1,2,3])
eea.filter_by_meta(Joly_Peuch_classification_code=[1,2,4])
eea.filter_by_meta(distance_to_kerb=[1,2,10])
```

**Comment by jgliss** [comment]
That is actually not a bug but a missing feature. List filters can only be applied for lists of strings so far. lists of values for numerical equality checks, are only considered as range interval (e.g. for altitude=[0, 1000]). I think this functionality will need modifications in methods `UngriddedData._init_meta_filters` and `UngriddedData._find_meta_matches`

**Comment by hansbrenna** [comment]
Thanks @jgliss. I agree this would be a reasonable enhancement. However, for now I only need to filter on continuous numerical values, so the range syntax actually fits well for what I want to do. I'll use [1,5] instead of [1,2,3,4,5] when filtering using Joly-Peuch.

**Comment by jgliss** [comment]
@hansbrenna good. We should leave this open, since having this more flexible should work anyways!
