### ISSUE TITLE
PPI tests for EBAS failing

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#1205]
**Describe the bug**
Please provide a clear and concise description of what the bug is.

Tests on PPI are failing because the testdata_minimal data set and is not the latest version. Long term: make the testdata_minimal come from MyPyaerocom, not shared resource
 - Pyaerocom version: v0.20.dev1
 - Computing platform: PPI
 - Configuration file (if applicable): NA
 - Error message (if applicable): NA

**To Reproduce**
1. pytest .

**Comment by jgriesfeller** [comment]
fixed via #1230
