### ISSUE TITLE
Empty colocated object when start and stop are not given

### ISSUE THREAD

**Issue by dulte** [metno/pyaerocom#1211]
**Describe the bug**
The colocator returns an empty object when no start and stop are given in the colocation setup

**To Reproduce**
1. Make a colocation setup without start and stop
2. Run a colocator with said setup
3. The result is an empty colocated object

**Comment by dulte** [comment]
This is a bigger (design) issue than first thought. #1212 makes the tutorials work, but breaks tests. 

The way it is done #1212 work to some degree, but keeps the old notion that if no start and stop are given, then pyaerocom try to infer them. More tests need to be made before this PR is ready

We have tried to make start and stop mandatory to define in colocation setup, but this breaks the tests. This is because a "default" ColocationSetup can't exist now; it must be given atleast start and stop. 

We need to decide how we want ColocationSetup to work

1. Start/stop is optional, and pyaerocom can infer them. 
2. Start/stop must be given by the user.

**Comment by dulte** [comment]
We will go for option 2

**Comment by heikoklein** [comment]
Won't fix, was a issue for tutorials which have been rewritten.
