### ISSUE TITLE
make the colour bars for the contours and the map user defined

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#1221]
**Is your feature request related to a problem? Please describe.**
The clour scales are right now defined globally here:
https://github.com/metno/pyaerocom/blob/26df81b3a82fd360c779c56fd724057101754f4f/pyaerocom/aeroval/glob_defaults.py#L2-L10
Different users have different priorities for how the scaling should look like. The scales should therefore be easily changeable (e.g. via the aeroval config file)

**Describe the solution you would like to see**
make the scales an optional part of the aeroval config file

**Additional context**
 color bars are used at the contours:
![image](https://github.com/metno/pyaerocom/assets/10772065/86c796a7-d85b-4314-a143-d1d25046012f)
The same values are also used here:
![image](https://github.com/metno/pyaerocom/assets/10772065/b3db811c-c77b-422d-ae8f-2be169eb4adf)

**Comment by heikoklein** [comment]
In addition, default color-maps should be defined by frequency, i.e. a range of `0-80` of hourly PM is fine, while it should be rather `0-35` for daily averages and `0-20` (or even less) for yearly averages.

**Comment by heikoklein** [comment]
> In addition, default color-maps should be defined by frequency, i.e. a range of `0-80` of hourly PM is fine, while it should be rather `0-35` for daily averages and `0-20` (or even less) for yearly averages.

moved to issue #1258
