### ISSUE TITLE
Is it possible to easily drop a small number of stations from an UngriddedData object

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#124]
There is a small number (<10) of erroneous stations in the GHOST data set. Is there a simple way of dropping a list of station names in an UngriddedData object? 

The only way I can think of is to use `filter_by_meta(station_name=list_of_all_good_stations)`, but this is clunky as I need to pre-define the list of good stations.

**Comment by jgliss** [comment]
If you don't need it to be removed before colocation, you can specify this via input arg `ignore_station_names` in the colocation routine. 

This can also be specified in the config file for the web-processing, here an example I use for removing some EBAS sites for the analysis of scattering and absorption in my paper:

```python
ebas_cfg = CFG['obs_config']['EBAS-Lev3']
ebas_cfg['obs_use_climatology'] = True
ebas_cfg['ignore_station_names']= {
        
        'ac550aer'    :   ['Granada', 'Leipzig Mitte', 'Ústí n.L.-mesto'],
        'sc550dryaer' :   ['Granada', 'Phoenix', 
                           'National Capitol - Central, Washington D.C']
        
```

Would this be sufficient?

**Comment by hansbrenna** [comment]
I think this is exactly what I need. Thanks.

**Comment by ejgal** [comment]
Think this can be closed. I also used this for dropping stations, and seems to work well.
