### ISSUE TITLE
Option to ignore locations outside of lat/lon domain in GriddedData.to_time_series

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#125]
When calling `GriddedData.to_time_series`, with `scheme=nearest`, lat/lon input coordinates that are not within the grid domain will be colocated with the nearest grid lat/lon at the edge of the domain. This is currently default behaviour and there needs to be an option to ignore input coordinates that are not within the domain and then selecting the nearest coordinates only for lat/lon coords that are within the domain.

**Comment by ejgal** [comment]
Fixed in #128
