### ISSUE TITLE
MDA8 values not shown on Overall Evaluation

### ISSUE THREAD

**Issue by heikoklein** [metno/pyaerocom#1264]
**Describe the bug**
MDA8 values are not shown on the overall [Evaluation page](https://aeroval-test.met.no/emep_evaluation/pages/overall/?project=emep&experiment=2024-XXX_2022_ebas2&station=ALL&observation=EBAS-m&parameter=vmro3&tab=heatmap&statistic=nmb#) . The are available on the Evaluation page.

Latest main-dev, run during the weekend.

**Screenshots**

![Image](https://github.com/user-attachments/assets/c03e9338-9ede-4121-bbe5-9ff9b557ea74)

**Comment by thorbjoernl** [comment]
~~I suspect the issue may be related to missing model id in `menu.json`.~~

~~On my own test experiment this value exists: https://api.aeroval-test.met.no/api/0.2.1/menu/mda8/mda8-test?data_path=thlun and vmro3mda8 is shown in the overall evaluation: https://aeroval-test.met.no/thlun/pages/overall/?project=mda8&experiment=mda8-test&station=ALL&frequency=daily~~

~~But for some reason it doesn't exist for mda8 on this evaluation (It exists for the other variables): https://api.aeroval-test.met.no/api/0.2.1/menu/emep/2024-XXX_2022_ebas2?data_path=emep_evaluation~~

~~Could you try adding model_id keys to menu.json manually to confirm @heikoklein?~~

**Comment by heikoklein** [comment]
I will rerun the experiment and the we will know more...

**Comment by heikoklein** [comment]
Doing the rerun with the latest version of aeroval with the yearly/monthly MDA8 data fixes, and the fixed comma between "vmrox" "vmro3mda8" in menu.json, the output looks as expected.

![Image](https://github.com/user-attachments/assets/d12c21b1-f037-46b3-a0a7-cd8e15b2bbf9)

Closing this issue since it existed only temporarily and seems to be fixed.
