### ISSUE TITLE
Bug in gridded timeseries extraction within lat/lon domain

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#127]
Bug related to recent changes in timeseries extraction from GriddedData, within a certain domain (#125), in method [extract_latlon_dataarray](https://github.com/metno/pyaerocom/blob/a882e325216ac43048dcb003bffeb75ef27212bb/pyaerocom/helpers.py#L85)

@ejgal pointed out:

I think this should be changed so that only pairs of latitudes and longitudes that exists gets added to lat and lon.
Currently this might lead to lat and lon having different lengths which causes problems in line 146.
Something like this (not tested):
`lat, lon = [x,y for x,y in zip(lat, lon) if (lat0 <= x <= lat1) and (lon0 <= y <= lon1) ]`

_Originally posted by @ejgal in https://github.com/metno/pyaerocom/pull/126/files/fdc3fab2bccbdf28f4f8ea0df23d0673e783cc40_

**Comment by ejgal** [comment]
Fixed in #128
