### ISSUE TITLE
Milestones are removed when issues are added from the AeroTools/Backlog

### ISSUE THREAD

**Issue by heikoklein** [metno/pyaerocom#1271]
**Describe the bug**
Adding issues directly in the [Backlog](https://github.com/orgs/metno/projects/12/views/1) is very convenient because the milestone and project are automatically set.

When adding a pyaerocom issue through the Backlog, the milestone is set for a couple of seconds, and then the milestone is removed by some internal automation.

**Expected behavior**
Automation should not remove the milestone of a project if set during creation.

**Screenshots**
Creation of bug through backlog, with milestone and project set.
![Image](https://github.com/user-attachments/assets/212f6bc6-89ff-4591-9b21-9d4693efa5a0)

**Comment by heikoklein** [comment]
github-project-automation removed milestone while adding AeroTools/Todo
![image](https://github.com/user-attachments/assets/a86dc355-b921-4ec7-9582-6c46645fc518)

**Comment by lewisblake** [comment]
This seems like a bug in GitHub's automation, not something we can control. 

![Image](https://github.com/user-attachments/assets/4e111182-5c40-4ecb-87fd-abce141219fe)
