### ISSUE TITLE
Pure hourly runs with o3 crash because o3mda8 is generated but not useable (for hourly)

### ISSUE THREAD

**Issue by heikoklein** [metno/pyaerocom#1279]
**Describe the bug**
Please provide a clear and concise description of what the bug is.
 - Pyaerocom version: Latest dev
 - Original reporter: @charlienegri 
 - Error message (if applicable):
```
│ /modules/rhel8/user-apps/fou-modules/cams2_83-evaluation/test-2/venv/lib/pyt │
│ hon3.10/site-packages/pyaerocom/aeroval/coldatatojson_helpers.py:642 in      │
│ _init_site_coord_arrays                                                      │
│                                                                              │
│    639 │   │   else:                                                         │
│    640 │   │   │   assert all(cd.data.station_name.values == sites)          │
│    641 │   │   jsdates[freq] = cd.data.jsdate.values.tolist()                │
│ ❱  642 │   return (sites, lats, lons, alts, countries, jsdates)              │
│    643                                                                       │
│    644                                                                       │
│    645 def _get_stat_regions(lats, lons, regions, **kwargs):                 │
│                                                                              │
│ ╭────────── locals ──────────╮                                               │
│ │      cd = None             │                                               │
│ │    data = {'hourly': None} │                                               │
│ │   found = False            │                                               │
│ │    freq = 'hourly'         │                                               │
│ │ jsdates = {}               │                                               │
│ ╰────────────────────────────╯                                               │
╰──────────────────────────────────────────────────────────────────────────────╯
UnboundLocalError: local variable 'sites' referenced before assignment
```

**To Reproduce**
Create an pyaeroval experiment containing o3 hourly and the following frequencies:
```
 "ts_type": "hourly",
  "freqs": [ "hourly"  ],
  "main_freq": "hourly",
```
(e.g. https://aeroval.met.no/pages/infos/?project=cams2-83&experiment=forecast-last-day&station=Switzerland&frequency=hourly&statistic=refdata_mean&parameter=conco3 )

**Expected behavior**
analysis should not crash. Only hourly o3 is shown (no o3max or o3mda8)

**Comment by thorbjoernl** [comment]
I'm having some difficulty confirming that this is caused by mda8 calculation. I still get this error even if I disable mda8 calculation by setting [colocator.py L386](https://github.com/metno/pyaerocom/blob/ba9431cead0e73d970e3653160ab08e8894a555e/pyaerocom/colocation/colocator.py#L386) to `if False:`

I'm not sure if this is due to a problem with my config or if this is a broader issue.

Could you try running it with mda8 calculation explicitly disabled (as above) and see if the issue still occurs? If not could you share the config you are using? @charlienegri 

Thanks!

**Comment by charlienegri** [comment]
ok I will try a short run with this edit, it might come from something else, but at least we are sure it's not in the code in production (tag cams2-83_2024-07 currently)  
with latest code I got another error that I posted in the chat so keep in mind that we might have overlapping issues

**Comment by charlienegri** [comment]
for reference, what I run for the 1-day test (the one that has hourly only) is something like
`cams2_83 forecast day 2024-03-01 2024-03-01 --model-path /lustre/storeB/project/fou/kl/CAMS2_83/model --obs-path /lustre/storeB/project/fou/kl/CAMS2_83/obs  --data-path /lustre/storeB/users/charlien/cams2-83-tests/data --coldata-path /lustre/storeB/users/charlien/cams2-83-tests/coldata --cache /lustre/storeB/users/charlien/cams2-83-tests/_cache_test_day --name 'TEST: NEW CODE' --id test-forecast-day --description 'Hic sunt leones.' `  
(so there is no extra config file than what is there in the repo for cams2_83, it all happens in the cli)

**Comment by charlienegri** [comment]
by editing L386 as you suggested (/modules/rhel8/user-apps/fou-modules/cams2_83-evaluation/test/venv/lib64/python3.10/site-packages/pyaerocom/colocation/colocator.py) the run seems to go through
