### ISSUE TITLE
test fail with xarray 2024.7.0

### ISSUE THREAD

**Issue by avaldebe** [metno/pyaerocom#1289]
**Describe the bug**
Please provide a clear and concise description of what the bug is.
 - Pyaerocom version: 0.21.0.dev0
 - Computing platform: Ubuntu 22.04.4 LTS and CI
 - Configuration file (if applicable):
 - Error message (if applicable):
```
        indexer = either_dict_or_kwargs(indexer, indexer_kwargs, "resample")
        if len(indexer) != 1:
>           raise ValueError("Resampling only supported along single dimensions.")
E           ValueError: Resampling only supported along single dimensions.

.tox/py311/lib/python3.11/site-packages/xarray/core/common.py:1056: ValueError 
```

**To Reproduce**
``` bash
tox -re py311 -- tests/aeroval/test_aeroval_HIGHLEV.py -vvx
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by thorbjoernl** [comment]
Deprecation of `base` and `loffset`causes `loffset` to be picked up as an indexer which is what causes the exception.

https://github.com/pydata/xarray/pull/9233

https://docs.xarray.dev/en/stable/whats-new.html#breaking-changes

>Using the origin or offset parameters is recommended as a replacement for using the base parameter and using time offset arithmetic is recommended as a replacement for using the loffset parameter. ([PR9233](https://github.com/pydata/xarray/pull/9233)) By [Deepak Cherian](https://github.com/dcherian).

I think the replacements are not supported by the oldest version of xarray which we currently support which means we either need to bump the oldest supported xarray version or have special logic (I vote for the former).
