### ISSUE TITLE
Simplify test data

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#131]
Some of the tests on f.e. colocation methods are unnecessarily tied to the data in testdata-minimal.
We already have `pyaerocom.helpers.make_dummy_cube_latlon` which is useful, but implementing additional functions that can generate test data "on the go" would be nice. See [this test](https://github.com/metno/pyaerocom/pull/128#discussion_r435792435) for an example where this would be useful.

**Comment by jgliss** [comment]
I totally agree and for most tests (especially unit tests) we do not need "real" data but can use suitable dummy data, that is created on the run. Let's discuss more next week, also how we best tackle #132 and #133.

**Comment by avaldebe** [comment]
I think we could tackle this after #547 and #595 are merged
