### ISSUE TITLE
We need tests for colocation_auto.py

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#132]
Tests for module `colocation_auto.py` are missing and urgently needed as there is several parallel developments going on at the moment. @hansbrenna and @ejgal, please keep that in mind. This module is the heart of the web evaluation tools which are currently also edited heavily and which lack any tests at the moment. The latter is on me and I am sorry for that, I will try to work on these tests a little here and there, but I appreciate any help on this. 

Tests should, if possible, rely on the content of [testdata-minimal](https://pyaerocom.met.no/pyaerocom-suppl/), so that they are executed in the automatic CI. If needed *testdata-minimal* may be extended by small, representative, subsets of your data.

The setup of the test environment is defined in [conftest.py](https://github.com/metno/pyaerocom/tree/v090dev) 

Creating dummy data is also an option and may be possible to use for testing certain things.

Let me know if you have any questions!

**Comment by jgliss** [comment]
Both for this issue and also for #133 we will probably need a place where temporary data is stored (e.g. this may be colocated data NetCDF files created by Colocator class or json files created for web tools). Tests should then also check these files by reading them and testing if format, values, etc. are correct.

I think one option to handle temporary output created by tests is to use the provided [temporary directories from pytest](https://docs.pytest.org/en/latest/tmpdir.html). I haven't used that yet, but it looks useful and simple to use.

**Comment by avaldebe** [comment]
the current version of `pyaerocom.colocation_auto` has a 82% coverage
