### ISSUE TITLE
add CAMEO aeroval base configuration

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#1330]
**Is your feature request related to a problem? Please describe.**
adding another base configuration similar to `pyaerocom/aeroval/config/emep/reporting_base.py` but for the CAMEO project

**Describe the solution you would like to see**
adjust `pyaerocom/aeroval/config/emep/reporting_base.py` to the needs of the CAMEO project
No assistance from other members of the pyaerocom team needed

**Additional context**
my old configs are a mess and needed a rewrite anyway

**Comment by lewisblake** [comment]
This issues raises the idea of creating a pyaerocom command line for converting EMEP output into aerocom3 format. Would save a lot of memory at run time if files pre-computed this way.
