### ISSUE TITLE
vars_order_menu should only appear in webdisp_opts

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#1388]
**Describe the bug**
Please provide a clear and concise description of what the bug is.
 - Pyaerocom version: 0.23.0
 - Computing platform: All
 - Configuration file (if applicable):
 - Error message (if applicable):

**To Reproduce**
1. Check any config

**Comment by lewisblake** [comment]
@AugustinMortier Changing this seemingly innocuous attribute to only exist in `webdisp_opts` actually breaks the `EvalSetup` interface. The reason is that the user just dumps all of these keys into `EvalSetup` and then they are passed over to their respective attributes (class instances, in this case `VarWebInfo`). The hacky solution would then be to then delete these attributes from `EvalSetup`, if that is even possible. In general, I'm not a fan of the unstructured way in which attributes are just dumped into a dict and then passed to `EvalSetup`, but unless we change the interface, this has to remain in place. I would be in favor of implementing a deprecation warning in `EvalSetup` that this approach will be removed in the future, but we also need to agree on what the solution is. Does this cause a big issue for you?

**Comment by AugustinMortier** [comment]
Having this duplicated is not a big deal for AeroVal which is just using one of them. It just causes confusion to the users when they are trying to understand why some species are missing from their menus, and that they see a variable with two possible different entries in two different places. So, having it in two places does not break anything as long as the right set of variables is the one showing up in "webdisp_opts"
