### ISSUE TITLE
pyaerocom makes IRIS emit warning: Using DEFAULT_SPHERICAL_EARTH_RADIUS

### ISSUE THREAD

**Issue by magnusuMET** [metno/pyaerocom#1394]
**Describe the bug**
Please provide a clear and concise description of what the bug is.
 - Pyaerocom version: `main-dev`

The use of [`iris.analysis.cartography.area_weights`](https://github.com/SciTools/iris/blob/8753cfb9c30f9bb71b6878e4d29000771b6fea9e/lib/iris/analysis/cartography.py#L379) will emit a warning that `DEFAULT_SPHERICAL_EARTH` is used. The fix will likely include specifying a coordinate system for the iris cube.

**To Reproduce**
1. Run `pytest` without `"ignore:Using DEFAULT_SPHERICAL_EARTH_RADIUS:UserWarning:iris.*:"` in `filterwarnings`

**Expected behavior**
No warnings emitted by code using `pyaerocom`

**Comment by lewisblake** [comment]
We are ignoring because it is not relevant to the use of iris in pyaerocom.
