### ISSUE TITLE
Change from cf_units to cf-units in pyaerocom_env?

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#141]
Currently we use the package [cf_units](https://anaconda.org/conda-forge/cf_units)
in the environment file. This package hasn't been updated for more than a year, and it is using syntax
that was deprecated in python 3.2.
A better version of cf units in conda forge is [cf-units](https://anaconda.org/conda-forge/cf-units) which seem to be more up to date.

I tested setting up an environment with the newer version and all tests passed. Okay to change the package in pyaerocom_env.yml?

**Comment by jgliss** [comment]
Yes, I think that is outdated and can be updated! Thanks!

**Comment by jgliss** [comment]
It may not be needed to specify cf-units explicitly since it comes with iris package. I think I added this in the environment during the transition phase (when iris changed from cf_units to cf-units) since there were initially some issues with cf-units.

**Comment by ejgal** [comment]
Ah, I see. Tested building an environment without cf*units listed, and got the new version.
Removed it in #142.
