### ISSUE TITLE
Broken output of configuration

### ISSUE THREAD

**Issue by magnusuMET** [metno/pyaerocom#1417]
**Describe the bug**
`main-dev` of pyaerocom outputs `obs_cfg` and `model_cfg` quoted (e.g. https://api.aeroval-test.met.no/api/0.2.1/cfg/eeareadertest/2024-reporting-mock?data_path=magnusu)

Might be related to the changes in #1407 as rerunning the experiment from before this yields the expected outcome (https://api.aeroval-test.met.no/api/0.2.1/cfg/eeareadertest/2024-reporting-mock-2?data_path=magnusu)

**Comment by lewisblake** [comment]
Pull main-dev :) fixed in #1406
