### ISSUE TITLE
runs with `only_model_maps=True` get a "WARNING:no output available for experiment.." warning which is misleading

### ISSUE THREAD

**Issue by charlienegri** [metno/pyaerocom#1426]
**Describe the bug**
this condition https://github.com/metno/pyaerocom/blob/232a3c956b98fd1f54e2b73792dacfb244107ab2/pyaerocom/aeroval/experiment_output.py#L209    
is based on checking that the `map` subfolder is populated in the output folder https://github.com/metno/pyaerocom/blob/232a3c956b98fd1f54e2b73792dacfb244107ab2/pyaerocom/aeroval/experiment_output.py#L159

in the case of a run with `only_model_maps=True`, the only subfolder that will be populated is `contour`   
so this check will always fail and the rest of the operations in `update_interface` will never be executed, despite the output having been correctly written out to `contour`

**To Reproduce**
1. run an experiment with `only_model_maps=True` and a fresh output folder

**Expected behavior**
in the case of a `only_model_maps=True` it should still be possible to finish the run by writing out the cfg[..].json, menu.json and the rest of the stuff in update_interface

**Comment by lewisblake** [comment]
Being addressed in #1434. As you mention, this is due to the reliance on of the `maps` dir in `ExperimentOutput` to determine if files were created correctly, so the fix will be to generalize this checking.
