### ISSUE TITLE
Support for 3.13

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#1436]
**Is your feature request related to a problem? Please describe.**
Add support for 3.13 and test against this  version

**Describe the solution you would like to see**
Title 
- Would you be able to work on this solution yourself? maybe
- How can the Pyaerocom development team assist you? N/A

**Additional context**
Magnus has been running on 3.13 already seemingly without issues :)

**Comment by heikoklein** [comment]
Tests should be run for 3.13
PPI-installation should be 3.12
Oldest supported is 3.10

We drop CI-tests of 3.11 for efficiency.
