### ISSUE TITLE
Vertical grid for time series plots

### ISSUE THREAD

**Issue by rkouznetsov** [metno/pyaerocom#1459]
Currently the time series plots have only horizontal grid, a-la  excel, which is reasonable for financial bar charts. 

![Untitled](https://github.com/user-attachments/assets/e629c284-6a04-41ca-aedb-e6f632328ac3)

Adding vertical grid lines would facilitate the visual inspection of the time series and attributing events of interest to specific times. Probably, also minor ticks and corresponding grid lines could be added to the time line.
Thank you!

UPD: The download png files already have vertical grid...
![o3-all-20241204-20241211](https://github.com/user-attachments/assets/e1d8012c-ea28-48b5-a71d-a5a7c70013b5)

**Comment by AugustinMortier** [comment]
Thanks a lot for your suggestion! The vertical grid lines were disabled by default because it can make some charts a little bit messy, but we have added a user option to activate it. Hope it fits your needs! 

![image](https://github.com/user-attachments/assets/2e77ad67-70da-4e79-a495-209076ec53cc)
