### ISSUE TITLE
We need a test-suite

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#15]
We need to define some sample datasets, that should be small and in the ideal case, openly accessible. The latter would make it easier to develop a test framework for pyaerocom using these data (which, if too big, could e.g. be accessed from the test environment online). Starting point could be currently existing minimal test suite (cf. [here](https://github.com/metno/pyaerocom/tree/master/pyaerocom/test), or [here](https://github.com/metno/pyaerocom/tree/master/pyaerocom/io/test), which, at the moment, however can only be run if access to METno servers is provided.

The test suite needs to grow and should run regularly in an automised manner, for instance, when pushing to remote or when drafting a release (e.g. using pytest and travis). 

### Status

Needs to be discussed and most relevant test routines are to be implemented.

**Comment by hannasv** [comment]
@jgriesfeller can you make some initial suggestions

**Comment by jgriesfeller** [comment]
Principle for station based data:
select max a had full of stations with old data (that is likely to going to change), download that, calculate a mean and compare that to a stored mean.
Example for Aeronet:
Aeronet also has a web API where one can download data. Documentation: https://aeronet.gsfc.nasa.gov/print_web_data_help_v3.html

Similar things we could do with model data and by comparing to observations also make sure the e.g. the colocation still works properly. Try to avoid the need to read an entire dataset. Use just data from the read_file method if possible.

**Comment by ejgal** [comment]
Seems that this has been improved on a lot with the automated run of pytest on push and tests (mostly) being written for new features.
