### ISSUE TITLE
warning messages switch on/off?

### ISSUE THREAD

**Issue by MichaelSchulzMETNO** [metno/pyaerocom#153]
How can you get rid of warning messages in pyaerocom? @jgliss

"Applying regional cropping in GriddedData using Filter class. Note that this does not yet include potential cropping in the vertical dimension. Coming soon...
Setting od550aer outlier lower lim: -1.00
Setting od550aer outlier upper lim: 10.00
Filtering of lat_range=[-180, 180] and lon_range=[-90, 90] results in unchanged object, returning self"

**Comment by jgliss** [comment]
I think the following should do the job:

```python
import pyaerocom as pya
pya.change_verbosity('critical', pya.const.print_log)
```

**Comment by jgliss** [comment]
@MichaelSchulzMETNO please let me know if this worked, in which case this issue can be probably closed. Cheers

**Comment by ejgal** [comment]
Closing this for now @MichaelSchulzMETNO. Feel free to reopen it if the suggestion from Jonas did not work.
