### ISSUE TITLE
Simple parallelization of web processing.

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#157]
The CAMS61 web processing takes a long time, so I thought of a simple way to parallelize the web processing, without really modifying pyaerocom. The basic flow is illustrated below:

```
obs_config = {
'obs1'     :    dict(obs_id='GHOST.EEA.daily',
                   obs_vars=[vars],
                   ...
                   obs_filters={some filters}),

'ob2'     :    dict(obs_id='GHOST.EEA.daily',
                   obs_vars=[vars],
                   ...
                   obs_filters={some more filters}),

...

'obsN'     :    dict(obs_id='GHOST.EEA.daily',
                   obs_vars=[vars],
                   ...
                   obs_filters={some other filters}),
}

CFG = {
# All normal things like model_config and setting parameters for the evaluation
obs_config = {} # empty dict
}

def run_processing(CFG):
    from pyaerocom.web import AerocomEvaluation
    # Create an instance of the Evaluation class and pass the configuration
    stp = AerocomEvaluation(**CFG)
     
    stp.run_evaluation()
    CFG['obs_config']={}

if __name__ == '__main__':
    from multiprocessing import Pool
    import copy
    CFG_list = []
    for k,v in obs_config.items():
        CFG['obs_config'].update({k:v})
        CFG_list.append(copy.deepcopy(CFG))
        CFG['obs_config']={}
    with Pool(6) as p:
        p.map(run_processing,CFG_list)

    CFG['obs_config'] = obs_config
    CFG['reanalyse_existing'] = False
    from pyaerocom.web import AerocomEvaluation
    stp = AerocomEvaluation(**CFG)
    stp.update_interface()
```

The colocation part is completely independent of each other and works perfectly in this way, but the computation of the .json files is only *almost* independent. There are a handful of places where the different processes might collide when accessing the same files or calling the same os functions at the same time which leads to a crash (writing to glob_stats*.json or regions.json; or when calling init_dirs() are the ones I've found until now). 

A simple solution I found after some googling was the library `tenacity` (available from conda-forge) which has a retry decorator. Just having the process wait a little and try again a few times fixed any crashes I've had. It really significantly speeds up the processing in the CAMS61 case (though I'm still testing). A more "elegant" solution would be to rewrite the offending parts of the code in a way that would allow safe multiprocessing, but I wanted a solution with minimal code changes.

The decorator looks like this:

`@retry(wait=wait_random_exponential(multiplier=1, max=20),stop=stop_after_attempt(20))`

I really like this functionality, since I spend quite some time waiting for results. The problem right now is that it breaks the automated testing for the branch where it's implemented. Could we add tenacity to the automated testing environment? Might you or any other users be interested in this, or is it's usefulness limited to my specific use case?

**Comment by jgriesfeller** [comment]
Have you considered s simple locking mechanism (create a lock file at operations begin; remove it at the end; test for it before starting).
That's a decades old concept for these problems.

**Comment by hansbrenna** [comment]
I thought of that, but I wanted minimal changes. Thinking about it again I guess that would be a simple solution which would also not impact the performance of a job not using parallelization.

**Comment by jgliss** [comment]
It is a very good idea to improve the performance of the web-tools using parallelization. However, to be honest this solution sounds more like a hack for me and I think we should not over-rush things here, but rather implement it properly. E.g. if you look at the main processing method AerocomEvaluation.run_evaluation:

```python
class AerocomEvaluation():
   ...
    def run_evaluation(self, model_name=None, obs_name=None, var_name=None,
                       update_interface=True,
                       reanalyse_existing=None, raise_exceptions=None,
                       clear_existing_json=None, only_colocation=None,
                       only_json=None):
        """Create colocated data and json files for model / obs combination

        Parameters
        ----------
        model_name : str or list, optional
            Name or pattern specifying model that is supposed to be analysed.
            Can also be a list of names or patterns to specify multiple models.
            If None (default), then all models are run that are part of this
            experiment.
        obs_name : :obj:`str`, or :obj:`list`, optional
            Like :attr:`model_name`, but for specification(s) of observations
            that are supposed to be used. If None (default) all observations
            are used.
        var_name : str, optional
            name of variable supposed to be analysed. If None, then all
            variables available for observation network are used (defined in
            :attr:`obs_config` for each entry). Defaults to None.
        update_interface : bool
            if true, relevant json files that determine what is displayed
            online are updated after the run, including the the menu.json file
            and also, the model info table (minfo.json) file is created and
            saved in :attr:`exp_dir`.
        reanalyse_existing : Bool, optional
            if True, existing colocated data files are ignored. If None, the
            class default will be used (defined in config file)
        raise_exceptions : bool, optional
            if True, exceptions during colocation will be raised if they occur
            (for debugging). If None, the class default will be used (defined
            in config file)
        clear_existing_json : bool, optional
            if True, existing json files for model / obs combination will be
            deleted before rerun. If None, the
            class default will be used (defined in config file)
        only_colocation : bool, optional
            if True, only colocation will be performed and no json files will
            be created. If None, the class default will be used (defined in
            config file)
        only_json : bool, optional
            if True, no colocation will be performed and only existing
            colocated data files will be re-processed.

        Returns
        -------
        list
            list containing all colocated data objects that have been converted
            to json files.
        """
        res = None
        if reanalyse_existing is not None:
            self.colocation_settings['reanalyse_existing'] = reanalyse_existing
        if raise_exceptions is not None:
            self.colocation_settings['raise_exceptions'] = raise_exceptions
        if clear_existing_json is not None:
            self.clear_existing_json = clear_existing_json
        if only_colocation is not None:
            self.only_colocation = only_colocation
        if only_json is not None:
            self.only_json = only_json
        if self.clear_existing_json:
            self.clean_json_files()

        if model_name is None:
            model_list = list(self.model_config)
        else:
            model_list = self.find_model_matches(model_name)

        if obs_name is None:
            obs_list = list(self.obs_config)
        else:
            obs_list = self.find_obs_matches(obs_name)

        self._log.info(self.info_string_evalrun(obs_list, model_list))

        self._update_custom_read_methods()

        for obs_name in obs_list:
            if obs_name in self.obs_ignore:
                self._log.info('Skipping observation {}'.format(obs_name))
                continue
            for model_name in model_list:
                if model_name == obs_name:
                    msg = ('Cannot run same dataset against each other'
                           '({} vs. {})'.format(model_name, model_name))
                    self._log.info(msg)
                    const.print_log.info(msg)
                    continue

                if model_name in self.model_ignore:
                    self._log.info('Skipping model {}'.format(model_name))
                    continue

                if not self.only_json:
                    col = self.run_colocation(model_name, obs_name, var_name)
                else:
                    col = None
                if only_colocation:
                    self._log.info('Skipping computation of json files for {}'
                                   '/{}'.format(obs_name, model_name))
                    continue
                res = self.make_json_files(model_name, obs_name, var_name,
                                           colocator=col)

        if update_interface:
            #self.clean_json_files()
            self.update_interface()

        return res
```

you can see that 1. colocation and 2. computation of json files are separate function calls. I believe the source code here could be modified easily so that first all colocated data files are computed (with or without a multiprocessing pool) and afterwards (e.g. in a second loop), all json files would be created. I think this would be a cleaner way, but it presumes, that the colocation is the main bottleneck and that the computation time of the json files is much less.

**Comment by hansbrenna** [comment]
I agree, but for the CAMS61 case on PPI, the computation of the json files takes at least as much time as the colocation.

I actually tried this in practice by first running it like below with `only_colocation=True` in the Pool runs and then doing all the json writing afterwards. To get significan speedup, in my case at least, the json computation and writing should be parallelized as well.
```python
for k,v in obs_config.items():
        CFG['obs_config'].update({k:v})
        l2.append(copy.deepcopy(CFG))
        CFG['obs_config']={}
    with Pool(2) as p:
        p.map(run_processing,l2)

    CFG['obs_config'] = obs_config
    CFG['only_colocation'] = False
    CFG['reanalyse_existing'] = False
    run_processing(CFG)
```

**Comment by hansbrenna** [comment]
I'm also not sure I agree that placing the parallelization outside pyaerocom is inherently hacky, even though my solution to the write problem was. If we could make the writing of files and management of directories multiprocess safe in a simple way it would place the burden of managing the extra layer of complication that parallelization often leads to on the user.

**Comment by jgliss** [comment]
I see! Could indeed be the case that on PPI the json processing takes much longer, since it is so many small files. I usually don't run on PPI, but at least my experience with reading of UngriddedData (lots of files) is much slower on PPI than on my local machine. 

Don't misunderstand me, I think it is a good idea to speed this up but I don't want to rush things like that. I just think we should discuss parallelization strategies properly, before rushing into one solution. 

And I think we should first have proper tests for all json conversion methods in [helpers_evaluation_iface.py](https://github.com/metno/pyaerocom/blob/v090dev/pyaerocom/web/helpers_evaluation_iface.py). Especially if we consider adding methods like `@retry` decorator (from additional libraries that we don't know very well) for handling I/O conflicts when writing the json files.

**Comment by hansbrenna** [comment]
I've also noticed the reading/writing of the small files is much slower on PPI.

I made a small benchmark and ran it on PPI and writing json files used about 1/3 of the run time so it's less than colocation but still significant. 

Let's discuss it properly then before doing anything else with it. I'll keep my `@retry` decorated code in a separate branch for now.

**Comment by jgriesfeller** [comment]
The solution above is limited to all processors of one machine. This something you hardly ever get on a queue. In my opinion we should put a normal config through a (to be written) tool that runs every model, variable, time span combination independently and puts together the files after the last piece has finished. This will even scale to the hundreds of combinations. 
The combination tool can then also be used to combine different experiments together.

**Comment by avaldebe** [comment]
Getting a full note is not that hard in my experience. One might have to wait for a PPI bionic node, but CentOS7 nodes are more readily available.

However, I'm not sure that this could be achieved without rewriting the `pyaerocom.aeroval` classes. The functions/methods submitted to a multi-process pool need to be pickle-able and I suspect that the implementation of the classes makes them too dynamic.

I think that splitting the job into independent tasks at the configuration stage is a better strategy. Maybe even using something like [hydra](https://hydra.cc/docs/intro) to run the individual tasks.

**Comment by jgriesfeller** [comment]
closing this because it's obsolete. 
Look at https://github.com/metno/pyaerocom-parallelization for a working parallelization
