### ISSUE TITLE
Config files in testdata

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#162]
When writing tests for `AerocomEvaluation` I want to read one of the eval_py files from data_new.
We could either create this file during test setup, or add it to the testdata.

What about storing it in a directory inside testdata (`testdata-minimal/config`)?

**Comment by jgliss** [comment]
Sounds good to me! Go ahead and (if you have access the pyaerocom web server) please update the test dataset at https://pyaerocom.met.no/pyaerocom-suppl/ directly. If you do not have access to the server, you can ask @jgriesfeller for help :)

**Comment by ejgal** [comment]
Got access and uploaded it now.
