### ISSUE TITLE
Colocating hourly data only matches every 24th hour

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#163]
Running an aerocom evaluation of hourly EMEP and GHOST data results in a ColocatedData object
where 23 out of 24 in the gridded data are NaN.

Looking into one station with `data.isel(station_name=0).isel(time=range(22,27)).values`
shows that the data_source corresponding to the EMEP data has NaN everywhere except from the 24th value. The pattern repeats itself.
 ```
array([[43.10035706, 36.585186  , 43.60152435, 41.59685135, 41.09568405],
       [        nan,         nan, 36.08344269,         nan,         nan]])
```

Not sure where to start looking here.
Any ideas @jgliss, @hansbrenna ?

First 25 values of the time dimension in the EMEP GriddedData object used for colocation:
```
['2018-01-01T00:29:59.999999488' '2018-01-01T01:30:00.000000000'
 '2018-01-01T02:30:00.000000000' '2018-01-01T03:29:59.999999488'
 '2018-01-01T04:30:00.000000000' '2018-01-01T05:30:00.000000000'
 '2018-01-01T06:29:59.999999488' '2018-01-01T07:30:00.000000000'
 '2018-01-01T08:30:00.000000000' '2018-01-01T09:29:59.999999488'
 '2018-01-01T10:30:00.000000000' '2018-01-01T11:30:00.000000000'
 '2018-01-01T12:29:59.999999488' '2018-01-01T13:30:00.000000000'
 '2018-01-01T14:30:00.000000000' '2018-01-01T15:29:59.999999488'
 '2018-01-01T16:30:00.000000000' '2018-01-01T17:30:00.000000000'
 '2018-01-01T18:29:59.999999488' '2018-01-01T19:30:00.000000000'
 '2018-01-01T20:30:00.000000000' '2018-01-01T21:29:59.999999488'
 '2018-01-01T22:30:00.000000000' '2018-01-01T23:30:00.000000000'
 '2018-01-02T00:29:59.999999488']
```

**Comment by hansbrenna** [comment]
How is the time dimension in GHOST? 

Could it be due to the 30 minute shift from whole hours?

**Comment by ejgal** [comment]
I guess that's the reason. Was a bit thrown off by the daily matches, but I guess the daily colocation is not as strict.

Here's the ghost time dimension:
```
['2018-01-01T00:00:00.000000000' '2018-01-01T01:00:00.000000000'
 '2018-01-01T02:00:00.000000000' '2018-01-01T03:00:00.000000000'
 '2018-01-01T04:00:00.000000000' '2018-01-01T05:00:00.000000000'
 '2018-01-01T06:00:00.000000000' '2018-01-01T07:00:00.000000000'
 '2018-01-01T08:00:00.000000000' '2018-01-01T09:00:00.000000000'
 '2018-01-01T10:00:00.000000000' '2018-01-01T11:00:00.000000000'
 '2018-01-01T12:00:00.000000000' '2018-01-01T13:00:00.000000000'
 '2018-01-01T14:00:00.000000000' '2018-01-01T15:00:00.000000000'
 '2018-01-01T16:00:00.000000000' '2018-01-01T17:00:00.000000000'
 '2018-01-01T18:00:00.000000000' '2018-01-01T19:00:00.000000000'
 '2018-01-01T20:00:00.000000000' '2018-01-01T21:00:00.000000000'
 '2018-01-01T22:00:00.000000000' '2018-01-01T23:00:00.000000000'
 '2018-01-02T00:00:00.000000000']
```

**Comment by ejgal** [comment]
Yes! Converted the units of the EMEP time dimension (from days since -> hours since) and it looks great!

![Selection_003](https://user-images.githubusercontent.com/23613579/86256166-47ba7500-bbb8-11ea-8b37-caec14855977.png)

**Comment by jgliss** [comment]
Great that you figured it out! Is this something where pyaerocom should do a check and give a proper warning?
