### ISSUE TITLE
Evaluation -  using observation variable for two interface variables

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#165]
Since we want to have both O3 and O3max in the interface we need to use vmro3 from GHOST for two variables:

1. O3 - Run normal colocation + diurnal.
2. O3max - Extract maximum daily values of vmro3 and colocate with vmro3max, using resample_how for observations.

Running this with two different config files works fine, but doing it in one config file is problematic. Is there a way to make this work using one config file, or combining the output from two runs?
@hansbrenna, @jgliss 

Config examples:
1. 
```
VAR_MAPPING['vmro3'] = ['O3', '3D', 'Volume mixing ratio']
obs_config = {'EEA-O3' : dict(obs_id='GHOST.EEA.hourly',
                            obs_vars=['vmro3'],
                            obs_vert_type='Surface',
                            web_interface_name='EEA',
                            ignore_station_names = ignore_dict,
                            obs_filters = OBS_FILTERS_BASE,
                            ts_type='hourly')}

model_config = {'EMEP-tnoCRef2': dict(model_id='EMEP-tnoCRef2',
                             data_dir = data_dir_tnoCRef2,
                             gridded_reader_id={'model':'ReadEMEP'})
}
```
2.
```
VAR_MAPPING['vmro3'] = ['O3max', '3D', 'Volume mixing ratio']
obs_config = {
'EEA-O3max' : dict(obs_id='GHOST.EEA.hourly',
                            obs_vars=['vmro3'],
                            obs_vert_type='Surface',
                            web_interface_name='EEA',
                            ignore_station_names = ignore_dict,
                            obs_filters = OBS_FILTERS_BASE,
                            ts_type='hourly',
                            resample_how='max')}

model_config = {'EMEP-tnoCRef2': dict(model_id='EMEP-tnoCRef2',
                             model_ts_type_read={'vmro3':'daily'},
                             model_use_vars = {'vmro3' : 'vmro3max'},
                             data_dir = data_dir_tnoCRef2,
                             gridded_reader_id={'model':'ReadEMEP'})
}
```

**Comment by jgliss** [comment]
Not entirely sure, but I think there is a way to do something like this. Check out this experiment:

http://localhost:8000/overall.php?project=noresm&exp=hygro

Config file is cfg_noresm_hygro and back then I introduced option `model_add_vars` in ColocationSetup that can be specified model config entry, to enable that two different model variables (here clear-sky and all-sky AOD, i.e. od550csaer and od550aer) are colocated with the same obs variable (AERONET, od550aer).

However,

1. not sure if this functionality with `model_add_vars` still works (if not, good to check if the problem is in `Colocator._find_var_matches`)
2. `resample_how` would need to be specified in model config entry, and variable specific, not sure if that works, but should be easy to fix if not.

Let me know if this does not work.

**Comment by ejgal** [comment]
Nice! Getting very close to what I want now :)
Selecting the ts_type for the model with `model_ts_type_read={'vmro3max':'daily', 'vmro3':'hourly'}` does not seem to work now.

With the following config it ran both vmro3 and vmro3max in hourly resolution.
```
'EEA' : dict(obs_id='GHOST.EEA.hourly',
                obs_vars=['vmro3'],
                obs_vert_type='Surface',
                web_interface_name='EEA',
                ignore_station_names = ignore_dict,
                obs_filters = OBS_FILTERS_BASE,
                ts_type='hourly'
                ),
```

```
'EMEP-tnoCRef2-hourly': dict(model_id='EMEP-tnoCRef2',
                             data_dir = data_dir_tnoCRef2,
                             model_ts_type_read={'vmro3max':'daily', 'vmro3':'hourly'},
                             model_add_vars = {'vmro3' : 'vmro3max'},
                             gridded_reader_id={'model':'ReadEMEP'}
                             )
```

**Comment by ejgal** [comment]
Adding these lines to _run_gridded_ungridded and passing ts_type=ts_type_model into _read_gridded seems to work.

```
            try:
                ts_type_model = self.model_ts_type_read[model_var]
            except Exception as e:
                ts_type_model = self.ts_type
```
