### ISSUE TITLE
Combining model_add_vars and model_ts_type_read fails in Colocator

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#166]
While trying to use `model_add_vars` to colocate a model variable with two different obs variables (#165) the correct ts_type was not used if `model_ts_type_read` was set to a dictionary.

Failing test (col_tm5_aero is a Colocator)
```
def test_model_ts_type_read(col_tm5_aero):
    model_var = 'vmro3'
    obs_var = 'od550aer'
    col_tm5_aero.model_add_vars = {obs_var:model_var}
    col_tm5_aero.model_ts_type_read = {model_var:'daily'}
    data = col_tm5_aero._run_gridded_ungridded()
    assert (data['od550aer'].data.ts_type_src == ['daily', 'daily']).all()
```

The current way to handle `model_ts_type_read` is to pass `ts_type = model_ts_type_read` into the gridded reader.
Since the gridded reader does not know about `model_add_vars` it will fail to use the correct ts_type.

**Comment by ejgal** [comment]
To test these features and others depending on different ts_types I want to extend the TM5 data available in the test data with at least one other variable and daily resolution.
To keep the daily files small I will extract only a few points for the daily resolution files.

@jgliss, is this the dataset you used?
```
Data ID: TM5-met2010_AP3-CTRL2019
Data directory: /lustre/storeA/project/aerocom/aerocom-users-database/AEROCOM-PHASE-III-2019/TM5-met2010_AP3-CTRL2019/renamed
```

**Comment by ejgal** [comment]
Or rather this one?
`/lustre/storeA/project/aerocom/aerocom-users-database/AEROCOM-PHASE-III/TM5_AP3-CTRL2016/renamed`

**Comment by jgliss** [comment]
Great idea, thanks @ejgal. I used `AEROCOM-PHASE-III-2019/TM5-met2010_AP3-CTRL2019/renamed`

**Comment by ejgal** [comment]
Thanks! Added monthly od550aer + monthly and daily ac550aer now.

**Comment by jgliss** [comment]
Great!

**Comment by ejgal** [comment]
After adding the new test data I found that the failing test was only caused by the lack of daily data ;)
Should be fine to close this.
