### ISSUE TITLE
Skip reading of model data if reanalyse_existing = False

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#169]
When running evaluations with large model data files it would be useful if the option `reanalyse_existing` is enforced before reading the model data.

I am not sure how feasible this is.
At the moment the model data is used for determining the filename of the colocated data and might be used for setting the ts_type to use for reading observations.

Any thoughts on this @jgliss?

**Comment by ejgal** [comment]
This is in `colocation_auto`. (`_run_gridded_gridded` and `_run_gridded_ungridded`).

**Comment by jgliss** [comment]
Hmm, would need to dig into this (which I currently don't have the time for), but I suspect it will require some restructuring related to variable name, etc., especially for cases where `model_add_vars` is used or `model_use_vars`, and also not sure, how aliases etc. are handled...

**Comment by ejgal** [comment]
No hurry on this. I expected it wouldn't be straightforward.
Maybe we just keep this issue in mind for the restructuring of ReadGridded for supporting different gridded readers.
