### ISSUE TITLE
Dealing with several gridded readers

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#174]
With the addition of other gridded readers (ReadEMEP so far) to pyaerocom there is a need to restructure reading of gridded data.

The proposal so far is to implement something similar to what is done for reading of ungridded data ([see docs for details](https://pyaerocom.met.no/api.html?highlight=dark%20green#reading-of-ungridded-data)).

**Comment by jgliss** [comment]
One possibility could be to make `ReadGridded` a factory (like `ReadUngridded`) that has registered different gridded readers but does not implement any reading itself. The current `ReadGridded` could then be renamed `ReadGriddedAerocom` and there should also be a template meta class `ReadGriddedBase` that defines the shared API of the gridded reader implementations (such as `ReadGriddedAerocom` and `ReadEMEP` / `ReadGriddedEmep`).

**Comment by jgliss** [comment]
Just made a quick conceptual draft:

```python
import abc
from pyaerocom.mathutils import compute_angstrom_coeff_cubes

class ReadGriddedBase(abc.ABC):
    # template base class (the API defined here would need to be implemented in gridded readers
    # and the factory class `ReadGridded` could make use of that.
    # common attributes and method declararions, e.g.

    AUX_REQUIRES = {'ang4487aer'    : ('od440aer', 'od870aer'),}
    AUX_FUNS = {'ang4487aer'   :    compute_angstrom_coeff_cubes}

    @property
    @abc.abstractmethod
    def data_id(self):
        # data ID
        pass

    @abc.abstractmethod
    def has_var(self, var_name):
        # Declared (needs to be implemented returns boolean
        pass

    @abc.abstractmethod
    def read_var(self, var_name, *args,  **kwargs):
        # returns GriddedData
        pass

class ReadGriddedAerocom(ReadGriddedBase):
    # currently called `ReadGridded` and implemented in readgridded.py (master)
    pass

class ReadGriddedEmep(ReadGriddedBase):
    # currently called ReadEMEP and implemented by @ejgal (branch ReadEMEP)
    pass

class ReadGridded(object):
    # factory that has all implementations of ReadGriddedBase registered
    SUPPORTED = [ReadGriddedAerocom, ReadGriddedEmep]

    def __init__(self, data_id, data_dir, **ini_opts):
        self.data_id = data_id
        self.data_dir = data_dir

        self._ini_opts = {}
        self._ini_opts.update(ini_opts)

    def get_reader(self):
        """
        Identify reader based on data_id

        ToDo: missing logic that needs to be implemented. Needs to be disscussed
        how to do that best.

        Returns
        -------
        ReadGriddedBase
            reader class derived from :class:`ReadGriddedBase`
        """
        raise NotImplementedError

    def read_var(self, var_name, **kwargs):
        """
        Read gridded variable data

        Parameters
        ----------
        var_name : str
            Name of variable that is supposed to be read.
        **kwargs : TYPE
            additional keyword agrs parsed to :func:`read_var` of reader
            class.

        Returns
        -------
        GriddedData
            Loaded data object

        """
        reader_cls = self.get_reader()
        # init reader
        reader = reader_cls(data_id=self.data_id,
                            data_dir=self.data_dir,
                            **self._ini_opts)

        return reader.read_var(var_name, **kwargs)

if __name__ == '__main__':

    reader = ReadGridded('NorESM2-met2010_AP3-CTRL')

    aerocom_data = reader.read_var('od550aer')

    reader = ReadGridded('EMEP-testrun',
                         data_dir='/home/my_emep_output')

    emep_data = reader.read_var('vmro3')
```

**Comment by jgliss** [comment]
@ejgal what do you think? Could something like this work with your current implementation of ReadEMEP?

**Comment by jgliss** [comment]
The above code is available here:

https://github.com/metno/pyaerocom-dev-scripts/blob/master/2020/20201007_draft_readgridded_factory.py

**Comment by ejgal** [comment]
Are we thinking that ReadGridded would be used mainly for reading datasets that have been added with something similar to `Config.add_ungridded_obs`?

**Comment by jgliss** [comment]
It should be able to do both:

1. Accept data directory directly provided (via `data_ dir`)
2. Find `data_dir` via `data_id` 

For the latter case, `data_id` would be the name of a directory containing model diagnostics. Directories to be searched can be added via `Config.add_data_search_dir`. E.g..

```python
# /home/my_model_output/
# /home/my_model_output/my_run1/ -> bunch of NetCDF files
# /home/my_model_output/my_run2/ -> bunch of other NetCDF files

import pyaerocom as pya

pya.const.add_data_search_dir('/home/my_model_output/')

reader = pya.io.ReadGridded('my_run1')
``` 

should suffice.

**Comment by ejgal** [comment]
Thanks for clarifying!
So both cases leads to resolving the reader based on a folder with a bunch of files, right?
For emep and aerocom we could check for `Base_` or `aerocom` in the beginning of the file name, but it doesn't feel like a good solution for handling many different gridded readers.

**Comment by jgliss** [comment]
Yes! That is correct. In case of AeroCom, there is some logic to identify different AeroCom file conventions used throughout the years, and the logic for that is available in [io/fileconventions.py](https://github.com/metno/pyaerocom/blob/v090dev/pyaerocom/io/fileconventions.py). Most of this code is from the early days and a little hard coded and unelegant, but it works....

This code is also used to retrieve metadata from the filenames, to create the overview `__str__` representation of the current `ReadGridded`, i.e., information about available diagnostics, sampling frequencies, year etc.

For AeroCom, the netcdf files are single year and single variable, so you can basically get most relevant meta information from the file names in the directory, without opening the files. 

Perhaps you could elaborate whether it would make sense to revise fileconventions.py and implement something similar for ReadEmep. So that the new factory `ReadGridded` will use class `FileConventionRead` to identify the reader that it should use.

But **note** that this issue is not relevant for the upcoming release ;)
