### ISSUE TITLE
Unit "nmol mol-1" is not converted to "mol mol-1"

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#181]
It's not clear to me whether units are supposed to be converted automatically or if this is the expected behaviour in pyaerocom.

I want to run co-location on volume mixing ratio variables with units "nmol mol-1". This fails during the check_units method of UngriddedData:

```
Traceback (most recent call last):
  File "/home/hansb/pyaerocom/pyaerocom/ungriddeddata.py", line 1236, in remove_outliers
    self.check_unit(var_name, unit=unit_ref)
  File "/home/hansb/pyaerocom/pyaerocom/ungriddeddata.py", line 1154, in check_unit
    .format(u, unit))
pyaerocom.exceptions.MetaDataError: Invalid unit nmol mol-1 detected (expected mol mol-1)
```

Are standard SI prefixes like nano- etc. not supposed to be automatically converted?

**Comment by jgliss** [comment]
This looks like a bug, it should be converted automatically. Strange that it does not work, must be due to some recent changes, since I am sure it worked before. I can check that later today.

**Comment by jgliss** [comment]
@hansbrenna feel free to close this issue after you tested the updates.

**Comment by hansbrenna** [comment]
I'm running some analysis now. Will see if things make sense.

**Comment by hansbrenna** [comment]
It seems to be working, so I'm closing this.
