### ISSUE TITLE
CAMS61 model MONARCH data has an embedded coordinate system causing regridding to fail

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#187]
At least one of the CAMS61 phase 2 models (MONARCH) has an embedded coordinate system in the iris.cube underlying the GriddedData object. This can be accessed as:
```
[in] gridded_data_ref.cube.coord_system()
[out] GeogCS(6371000.0)
```
This causes regridding to fail since the dummy cube created for regridding has coordinate system `None` and the coordinate systems has to be the same. EMEP and the other models I have checked until now also has `None` as their coordinate systems.

Is this something anyone has encountered before and know how to handle?

**Comment by jgliss** [comment]
I have not encountered this so far and pyaerocom support for different coordinate systems does not go beyond what iris can do on it. Perhaps it can be fixed by assigning the coordinate system to the dummy cube?

**Comment by hansbrenna** [comment]
I've looked more into this and adding the coordinate system to the dummy cube works, but when we colocate two models, this will not work as they will have different coordinate systems. I have not been able to figure out how to change or strip coordinate systems from iris cubes.

**Comment by jgriesfeller** [comment]
CAMS61 is over. Closing this issue.
