### ISSUE TITLE
Redesign `StationData`

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#189]
Not fully defined yet but should be based on `xarray`, for instance, a `Dataset` with global site attributes such as lat, lon, site name, etc. and `DataArray` instances that contain variable data and associated metadata (such as wavelength, instrument name, etc.).

**Comment by ejgal** [comment]
Duplicate of #146?

**Comment by jgliss** [comment]
> Duplicate of #146?

YES!
