### ISSUE TITLE
Attempting to add conversion from vmr to conc for gridded data

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#191]
For the CAMS61 analysis we need to be able to convert some variables from vmr to concentrations. The conversion from conc to mmr (using rho) is already defined in the ReadGridded class, so i thought the best way to do it would be to add the conversion from vmr to mmr as this will not break the other conversion. I also defined the calculation of rho from T and P. I added this to the dictionary in the class definition as:

```python
AUX_REQUIRES = {'ang4487aer'    : ('od440aer', 'od870aer'),
                    'od550gt1aer'   : ('od550aer', 'od550lt1aer'),
                    'wetoa'         : ('wetpoa', 'wetsoa'),
                    'dryoa'         : ('drypoa', 'drysoa'),
                    'conc*'         : ('mmr*', 'rho'),
                    'sc550dryaer'   : ('ec550dryaer', 'ac550dryaer'),
                    'mmr*'          : ('vmr*'),
                    'rho'           : ('ts','ps'),
                    #'mec550*'       : ['od550*', 'load*'],
                    #'tau*'          : ['load*', 'wet*', 'dry*'] #DOES NOT WORK POINT BY POINT
                    }
```

with dummy functions for the conversion added to the AUX_FUNS dictionary:

```python
AUX_FUNS = {'ang4487aer'   :    compute_angstrom_coeff_cubes,
                'od550gt1aer'  :    subtract_cubes,
                'wetoa'        :    add_cubes,
                'dryoa'        :    add_cubes,
                'sc550dryaer'  :    subtract_cubes,
                'conc*'        :    multiply_cubes,
                'mmr*'         :    mmr_from_vmr,
                'rho'          :    rho_from_ts_ps,
                #'mec550*'      :    divide_cubes,
                #'tau*'         :    lifetime_from_load_and_dep
                }
```

After doing this, rho is available to read from the list of variables, but neither mmr or conc of the gas variables are available. I don't understand why this does not work.

**Comment by ejgal** [comment]
There is a lot going on when determining which variables are available. I would try running a debugging session on `_check_var_match_pattern` for the conc and mmr variable you have in vmr format.

For the conc part:
I think running f.e. `_check_var_match_pattern('concso2')` at will run `_check_var_avail('mmrso2')` which only looks into aliases and available files for determining availability. Since it does not look into auxilliary variables this will fail if you don't already have an mmrso2 file.

Not sure why the mmr does not show up.

**Comment by hansbrenna** [comment]
So the search for calculatable variables is not recursive. That requires some thinking, and I really have to look into the details of the implementatiob.

But I still can't figure out how to get mmr* to work. Which should in principle be straightforward.

**Comment by hansbrenna** [comment]
The mmr calculation failed because my test gas, ozone, was not defined as an mmr. So at least that part is done. Now I only need to figure out the rest and actually implement the conversion functions.

This has taken me a day and a half (-:

**Comment by hansbrenna** [comment]
Another issue is that adding only one variable as an aux to another does not work, e.g. the following:
```Pyhton
AUX_REQUIRES = {'ang4487aer'    : ('od440aer', 'od870aer'),
                    'od550gt1aer'   : ('od550aer', 'od550lt1aer'),
                    'wetoa'         : ('wetpoa', 'wetsoa'),
                    'dryoa'         : ('drypoa', 'drysoa'),
                    'conc*'         : ('mmr*', 'rho'),
                    'sc550dryaer'   : ('ec550dryaer', 'ac550dryaer'),
                    'mmr*'          : ('vmr*'),
                    'rho'           : ('ts','ps'),
                    #'mec550*'       : ['od550*', 'load*'],
                    #'tau*'          : ['load*', 'wet*', 'dry*'] #DOES NOT WORK POINT BY POINT
                    }
```

While this works, even though I don't need `ts` for anything in this calculation:
```Pyhton
AUX_REQUIRES = {'ang4487aer'    : ('od440aer', 'od870aer'),
                    'od550gt1aer'   : ('od550aer', 'od550lt1aer'),
                    'wetoa'         : ('wetpoa', 'wetsoa'),
                    'dryoa'         : ('drypoa', 'drysoa'),
                    'conc*'         : ('mmr*', 'rho'),
                    'sc550dryaer'   : ('ec550dryaer', 'ac550dryaer'),
                    'mmr*'          : ('vmr*','ts'),
                    'rho'           : ('ts','ps'),
                    #'mec550*'       : ['od550*', 'load*'],
                    #'tau*'          : ['load*', 'wet*', 'dry*'] #DOES NOT WORK POINT BY POINT
                    }
```

**Comment by hansbrenna** [comment]
I've made progress on the vmr -> mmr calculation, which now works when I run `Readgridded.read_var` but not when I run `ReadGridded.read`. i.e. this works:

`pya.io.ReadGridded('EMEP.cams61.rerun')read('mmro3',vert_which='Surface')`

While this does not:

`pya.io.ReadGridded('EMEP.cams61.rerun')read_var('mmro3',vert_which='Surface')`

and fails with:
`VarNotAvailableError: None of the desired variables is available in EMEP.cams61.rerun`

Is this the expected behaviour or is there a bug in my implementation?

**Comment by ejgal** [comment]
Does mmro3 show up when you run `pya.io.ReadGridded('EMEP.cams61.rerun').vars_provided`?
read is a bit higher level than read_var and checks `vars_provided` against `vars_to_retrieve` before reading.

**Comment by ejgal** [comment]
I'm unsure of what to expect from vars_provided.
This test does not pass, since vars_provided lacks conco3.
```
@pytest.mark.parametrize('vars,expected',[
    (['mmro3', 'rho'], ['conco3', 'mmro3', 'rho']),
])
def test_ReadGridded_aux(tmpdir, vars, expected):
    for var in vars:
        filename = 'aerocom3_TM5-met2010_AP3-CTRL2019_{}_Column_2010_daily.nc'.format(var)
        open(os.path.join(tmpdir, filename), 'a').close()
    r = ReadGridded(data_dir=str(tmpdir))
    assert r.vars_provided == expected
```

**Comment by hansbrenna** [comment]
I'll look into your comments. 

I see that the reading of gridded data in aerocom_evaluation uses read_var, so that means it will work for my main purpose at least.

**Comment by hansbrenna** [comment]
It seems like variables computed from a pattern family are not shown in `pya.io.ReadGridded('EMEP.cams61.rerun').vars_provided`, until `check_compute_var('varname')` has been called for the specific variable name. Afterwards it shows up at the en of the list.

**Comment by hansbrenna** [comment]
To solve the greater problem, that I need another definition of the conc* pattern than what is currently supported, is it better to try to make the search for calculatable variables recursive or to add multiple definitions for a pattern?

something like `'conc*'         : (('mmr*', 'rho'),('var1','var2')),` as alternate solutions to the same pattern? @jgliss

**Comment by hansbrenna** [comment]
I have implemented conversion from vmr -> conc directly in my branch now (as a test) by changing the definition of the conc* pattern to use vmr, temperature and pressure to calculate concentrations from volume mixing ratios and rho from T and P.

**Comment by jgliss** [comment]
@hansbrenna I think a recursive search would be nicer, something like that is already implemented for the ungridded reading, so it would be similar (see class method `ReadUngriddedBase.check_vars_to_retrieve`). If possible this should be included in the upcoming release, but I won't have time to work on this. Can you make a PR branching off v090dev, also including your rho computation logic from p and T? You use `ts` and `ps` for that, right? Isn't that only at the surface? Perhaps, default `rho` computation should be 4D pressure and temperature! 

I just figured that I would also need to read 4D conc via mmr, temperature (ta) and pressure (pfull), see here for variable definitions:

https://docs.google.com/spreadsheets/d/1NiHLVTDsBo0JEBSnnDECNI2ojUnCVlxuy2PFrsRJW38/edit#gid=1256817062

So what we would need in terms of logic is: try most general case (4D) and do ts and ps only if ta and pfull are not available (or if `vert_which` is speciefied in `ReadGridded.read_var`). 

@ejgal I think we should deprecate `ReadGridded.read` for now, as this is never really used (to my knowledge. Might indeed be buggy and not up to the latest developments.

**Comment by hansbrenna** [comment]
@jgliss I thought it was surface as well, but in the CAMS61 data `ts` and `ps` are 4D variables, even though they are the standard short names for surface fields. Surface T and P were not submitted in the CAMS61 data.

This might complicate things a bit, but should be fixable.

**Comment by jgliss** [comment]
@hansbrenna thanks for the info, these variable names are wrong then in CAMS61... another classical example that illustrates why it is difficult to clearly resolve reading and computation of variables for a given user request... For the pyaerocom release, your solution (with `ts` and `ps`) should be handled as an exception if `ta` and `pfull` are not available. The default in the header of `ReadGridded` should try to read `ta` and `pfull`.
