### ISSUE TITLE
Sparse test coverage for ReadGridded

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#194]
There are not that many tests for ReadGridded and most rely on a lustre connection.
Some of the lustre tests could be converted to use the testdata instead.

There is a little confusion about the expected behavior of some functionality (see #191), which could be clarified through some tests.

**Comment by jgliss** [comment]
@ejgal great initiative, thanks! I think the variable resolving logic in ReadGridded could indeed see some revision, it has been developed over quite some time and I agree that some method names are misleading, and likely some methods (like `read`) are buggy/outdated now. On the longer term, I think we should think about redesigning this issue of resolving variables. It is a thing in both ungridded and gridded reading and could be perhaps unified in a separate API that is used by ReadGridded, ReadEMEP, ReadUngridded, etc. Not for v0.10.0 but perhaps for v.1.0.0.

**Comment by ejgal** [comment]
The API idea sounds interesting, will keep it in mind.
There are now at least some tests for ReadGridded not relying on lustre. Closing this for now.
