### ISSUE TITLE
ReadGridded.get_var_info_from_files() fails if AUX_REQUIRES.keys() contain *

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#196]
See `test_ReadGridded_get_var_info_from_files` in #195.
Caused by calling `check_compute_var(conc*`) which expects a variable name with no wildcards.

**Comment by jgliss** [comment]
Good point! Thanks for looking into this. Should we add variable family checks also in `check_compute_var`? Shouldn't be too expansive, right?

**Comment by ejgal** [comment]
`get_var_info_from_files` looped over all the AUX_REQUIRES keys calling `_get_aux_vars_and_fun(conc*)`.
I added `except VariableDefinitionError` to fix it for now.

I think calling `check_compute_var` or `_get_aux_vars_and_fun` with a variable family name does not make sense, since they both deal with one variable at a time. They both seem to work with f.e. conco3.

**Comment by ejgal** [comment]
Closed with merge of #195
