### ISSUE TITLE
packages

### ISSUE THREAD

**Issue by MichaelSchulzMETNO** [metno/pyaerocom#2]
Shouldnt the installation guide also explain or autmatically install all needed packages?

**Comment by jgliss** [comment]
Yes, I will include more detailed installation instructions soon. On a longer perspective, installation of pyaerocom including all requirements should simply work via 

`conda install pyaerocom`

**Comment by jgliss** [comment]
More detailed installation instructions are now provided in the notebook [info00_install_detailed.ipynb](https://github.com/metno/pyaerocom/blob/master/notebooks/info00_install_detailed.ipynb). I consider this issue closed for now.
