### ISSUE TITLE
Rename ReadEMEP to ReadGriddedEmep

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#201]
https://github.com/metno/pyaerocom/blob/5a882427d95cacd9e847f58434adf371595cc49d/pyaerocom/io/read_emep.py#L25

@ejgal would it be possible to rename the class `ReadEMEP` to `ReadGriddedEmep` for the upcoming release (to be consistent with other implementations and future devs, see my comment in  #174)?

You could also keep `ReadEMEP` for backwards compatibility. I usually do it this way:

```python
class ReadGriddedEmep(object):
    # your implementation (currently called ReadEMEP)

class ReadEMEP(ReadGriddedEmep):
    """Old name of :class:`ReadGriddedEmep`."""

    def __init__(self, *args, **kwargs):
        super(ReadGriddedEmep, self).__init__(*args, **kwargs)
        print("You are using a deprecated name ReadEMEP for class ReadGriddedEmep")

**Comment by ejgal** [comment]
Sure @jgliss , but isn't the naming convention for the reading classes just ReadDatasource? So we would have ReadAerocom, ReadEMEP, ReadWRF etc.? This is how it is done for the ungridded readers.

**Comment by jgliss** [comment]
@ejgal true! I'm fine with leaving the "Gridded" out.

**Comment by jgliss** [comment]
However, I would prefer `ReadEmep` over `ReadEMEP` to be more consistent with other readers (e.g. ReadEbas, ReadGhost, etc.).

**Comment by ejgal** [comment]
Good point :) Will change it.

**Comment by jgliss** [comment]
We should also keep in mind that there is an EMEP measurement network in Europe (PM measurements). But if we ever want to read that (as ungridded obs), we can find a way to name it (e.g. ReadEmepObs) or so...

**Comment by ejgal** [comment]
And there are several EMEP models from the other centres (MSCE-HM and MSCE-POP).
Seems we are actually reading: The EMEP MSC-W chemical transport model.
So, change to ReadEmep or MSCW-CTM? :confused:

**Comment by jgliss** [comment]
Yes, that is okay!

**Comment by jgliss** [comment]
I am not so familiar with the conventions (filename and structure) of the different EMEP modelling centres but it is better to be explicit from the beginning. In the end, we will have `ReadGridded` resolving (somehow) which reader to use, and the user will not know, what reader is instantiated in the background.
