### ISSUE TITLE
Logic to resolve filepath in ReadEMEP

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#203]
https://github.com/metno/pyaerocom/blob/6156d4d03fae0fbac02e002f2b2249a1c85529cb/pyaerocom/io/read_emep.py#L245-L258

@ejgal can you review this logic please? This can lead to a crash in L277, e.g. if both self.filepath and self.data_dir are not set or invalid.

Also, please try to be more explicit in if statements, e.g. replace

```python
if self.data_dir: 
    # code
```

with 

```python
if self.data_dir is not None and os.path.isdir(self.data_dir): 
    # code
```

**Comment by ejgal** [comment]
Good catch, this was a bit sloppy.
I pushed an improved version now, see #204.
