### ISSUE TITLE
Does the variable name in NetCDF files to be read as gridded data have to be the same as the variable name specified in the file name?

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#206]
In one of the cams_61 model submissions the name of the variable in the netcdf file does not match the variable name specified in the file name, e.g. file name says vmro3, netcdf file content says O3. Will this cause problems?

**Comment by jgliss** [comment]
I am a little uncertain, but yes it may cause problems. It should be easy to test, right?

**Comment by hansbrenna** [comment]
I would love to, but the files also seem to be corrupted for some other unrelated reason (:

**Comment by jgriesfeller** [comment]
If you allow that the variable name in the filename and the netcdf variable name differ, you have to run a lot of tests to make that work correctly. We tried ;-)
That's why it has always been a requirement so far that they are the same

**Comment by jgriesfeller** [comment]
CASMS61 has finished. closing this issue.
