### ISSUE TITLE
Failing lustre tests

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#210]
Running pytest on branch v090dev with lustre mounted fails on these tests:

```
FAILED pyaerocom/io/test/test_read_aeronet_sdav3.py::test_load_berlin_AeroSdaV2L2D - OSError: No files could be detected that match the pattern
FAILED pyaerocom/io/test/test_read_aeronet_sunv3.py::test_load_berlin - OSError: No files could be detected that match the pattern
FAILED pyaerocom/io/test/test_read_ghost.py::TestReadGhost::test__eval_flags_slice - PermissionError: [Errno 13] Permission denied: b'/lustre/storeA/project/aerocom/aerocom1/AEROCOM_OBSDATA/GHOST/data/EEA_AQ_...
FAILED pyaerocom/io/test/test_read_ghost.py::TestReadGhost::test_read_file[ghost_eea_daily-2290-Bleak House] - PermissionError: [Errno 13] Permission denied: b'/lustre/storeA/project/aerocom/aerocom1/AEROCOM_...
FAILED pyaerocom/io/test/test_readgridded.py::test_years_available - AssertionError: 
FAILED pyaerocom/io/test/test_readungridded.py::test_basic_attributes - AssertionError: assert ['od340aer', ...4&87aer', ...] == ['od340aer', ...er_calc', ...]
FAILED pyaerocom/test/test_ebas_sample_stats.py::test_ungriddeddata_jungfraujoch - assert (17520, 12) == (245448, 12)
FAILED pyaerocom/test/test_ebas_sample_stats.py::test_scat_jungfraujoch - assert 8323 == 25789
FAILED pyaerocom/test/test_ebas_sample_stats.py::test_scat_jungfraujoch_lev3 - assert 8323 == 25789
FAILED pyaerocom/test/test_ebas_sample_stats.py::test_scat_jungfraujoch_subset - pyaerocom.exceptions.DataCoverageError: ['sc550aer'] data could not be retrieved for meta  index (or station name) [0.0, 1.0]
FAILED pyaerocom/test/test_obsdata_versions.py::test_revision_dates - AssertionError: 
```

The two tests related to read_ghost is caused by the new ghost data having more restrictive permissions than other aerocom data. @hansbrenna can you update that? Other files have 664 permissions so they are readable but not writable even if not in the aerocom group.

For the others I'm not sure what is going on. Has the datasets been changed recently?

**Comment by jgliss** [comment]
@ejgal some of the AERONET datasets have been updated by @jgriesfeller I think and I recall, that the Berlin site was missing in one of them. Perhaps, you could update these? Also test_revision_dates, which checks if any of the datasets on lustre has been updated. I also changed the initial shape of the _data attribute of UngriddedData, which is why some shape checks fail I think. For GHOST, I am not sure, but looks like there is an issue with file permissions.

**Comment by ejgal** [comment]
Thanks @jgliss, I'll have a look into that.

For ghost the problem is that the new files have permissions `-rwxrwx---` -> no reading for those not part of aerocom group. The other Aerocom files have permissions `-rw-rw-r--`.
I think running something like `chmod --recursive 0664 /lustre/storeA/project/aerocom/aerocom1/AEROCOM_OBSDATA/GHOST/data` should work. (Given that there are no data that shouldn't be available for reading by everyone with lustre access...)

**Comment by ejgal** [comment]
The EBAS tests fails due to [this commit](https://github.com/metno/pyaerocom/commit/aa87ce82050ae21fb8e453e8811f160218802ee8) which changed the fixture that `test_ebas_sample_stats` relies on.
This is great since we can convert the EBAS lustre tests to use testdata-minimal instead.
But I have no idea how to read the EBAS files directly for calculating the values that we test for.
Should I just use pyaerocom to calculate the values?

**Comment by ejgal** [comment]
Seems that the EBAS data hasn't been changes, so I'll just create a new fixture that looks like the old one and use that for now.

**Comment by ejgal** [comment]
For the aeronetsun tests I removed the test relying on lustre since there were already tests using the testdata.
For aeronetsda I converted the lustre test to a testdata test.
