### ISSUE TITLE
Time filtering of UngriddedData sensitive to the way time limits are specified

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#228]
When making StationData from UngriddedData, the number of stations is sensitive to the specific way the time limits are specified. Even when I would expect input to give the same result.

The following gives different results:

```
data = pya.io.ReadUngridded().read(f'GHOST.EEA.hourly','vmro3')
station_data = data.to_station_data_all(start=2018,stop=2019) 
print(f"EEA Raw: {len(station_data['station_name'])}") -> 2358

station_data = data.to_station_data_all(start='2018',stop='2019')
print(f"EEA Raw: {len(station_data['station_name'])}") -> 2359

station_data = data.to_station_data_all(start='2018-01-01T00',stop='2019-01-01T00')
print(f"EEA Raw: {len(station_data['station_name'])}") -> 2359

station_data = data.to_station_data_all(start='2018-01-01T00',stop='2018-12-31T23')
print(f"EEA Raw: {len(station_data['station_name'])}") -> 2358
```

That the last two give different numbers aren't surprising, but I would expect the top three to give the same result.

**Comment by jgliss** [comment]
@hansbrenna thanks for finding this inconsistency. I will try to fix investigate / fix this behaviour this week.
