### ISSUE TITLE
Unit conversions

### ISSUE THREAD

**Issue by mifads** [metno/pyaerocom#24]
For O3 Ebas has ug/m3 although the variable is named vmro3. Models tend to use vmr, so we need to covert between the two. Often one uses a fixed ratio 1 ppb O3 = 2 ug/m3, but of course a proper calculation would need temperature and pressure and mol. weights. Could the method convert_units have options for a fixed numerical factor (e.g. 0.5) or MW input, or similar. 

Also, some stations at high elevations need thinking about. Often they want to convert ug/m3 as measured to ug/m3 STP.

**Comment by MichaelSchulzMETNO** [comment]
Would be good ensure that both model and obs read routines convert to a standard unit, which is documented along with the variable. Could be part of a documentation page on variable standards. Which unit and standards can the user expect?

**Comment by MichaelSchulzMETNO** [comment]
wrt to mountain sites: Some measurements are indeed converted to standard pressure and temperature at sea level (concentrations, in-situ optical properties). Good to be clear about this as well as a standard.

**Comment by jgriesfeller** [comment]
@MichaelSchulzMETNO Is this still relevant?

**Comment by MichaelSchulzMETNO** [comment]
There was a lot of discussions on units afterwards in CAMS61. I am not sure if they covered this. What does "m3" mean, is that clear now?

**Comment by jgriesfeller** [comment]
For me at least yes, that's cubic meters.

**Comment by MichaelSchulzMETNO** [comment]
but at which temperature and pressure???
