### ISSUE TITLE
models level conversion 

### ISSUE THREAD

**Issue by TatianaKlisho** [metno/pyaerocom#240]
@MichaelSchulzMETNO 
@jgliss 

Hej all,

I'm trying to convert levels in CAM5-ATRAS and MIROC-SPRINTARS models. I'm working with ec550aer_ModelLevel_2010_monthly files. Unfortunately, some variables from the level formula are missing.

For instance, in CAM5-ATRAS, where    lev:long_name = "hybrid level at midpoints (1000*(A+B))  B and A are not there.
What can be a solution?

Cheers

**Comment by MichaelSchulzMETNO** [comment]
@jgliss dont we have the dz variable for these models, the height per level in meter?

**Comment by MichaelSchulzMETNO** [comment]
Another idea: One could search for the coordinates in other 3d variable (eg standard humidity, air temperature)  CAM5 model experiments in the aerocom-modeldata or CMIP5 folder... having the same resolution. For MIROC, the coordinates might be in the CMIP6 files possibly.

**Comment by jgliss** [comment]
@TatianaKlisho it can happen that the metadata in the NetCDF files is incomplete and does not allow to compute the atmospheric pressure from the vertical coordinate info provided in the files. But like Michael said, there is often additional NetCDF files in the model data directory (if you work with AeroCom model data). For instance, you would need to search for *ModelLevel* files that have  *pfull* or *dh* or *z* or *dz* as a function of time, lat, lon and lev. I just checked and both CAM5-ATRAS and MIROC-SPRINTARS have sufficient additional fields available, SPRINTARS has even variable *zg* (Geopotential height). Does this work for you?

**Comment by TatianaKlisho** [comment]
@jgliss Yes, I found pfull variable for  CAM5-ATRAS  model. Would that mean that instead of converting existing levels into atm. pressure I can just use pfull?

**Comment by jgliss** [comment]
@TatianaKlisho yes, you can use pfull (which is pressure at layer mid-levels) directly!
