### ISSUE TITLE
Calculating ammonia and nitric acid variables

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#243]
Reading the variables Sum(HNO3+NO3)  and Sum(NH3+NH4) from EBAS works fine after defining them with units `ug N m-3` in variables.ini.

On the model side we have the following relevant variables:
Sum(HNO3+NO3)
* concno3c
* concno3f
* vmrhno3
concno3c and concno3f could be combined with add_cubes and AUX_REQUIRES in ReadGridded.

Sum(NH3+NH4)
* concnh4
* vmrnh3

Can mathutils.vmrx_to_concx be used for converting vmrnh3 and vmrhno3?

In the end we want everything in units of ug N m-3.

**Comment by jgliss** [comment]
@hansbrenna can you comment on this? Eirik is checking units etc., and obsreading of the N related variables. Is there an easy way to convert vmrhno3 to conchno3? I remember you also implemented some more flexibility in ReadGridded for automatic conversion of vmrX to concX, given that P and T fields are provided. 

In the ideal case, this could be handled recursively via AUX_REQUIRES etc in ReadGridded.

**Comment by ejgal** [comment]
I checked these variables for the following models (from here: https://gitlab.met.no/aerocom-evaluation/cams61_json_p2/-/blob/master/2018-rerun4/cfg_cams61_p2_2018-rerun4.json)
```
model_ids = ['EMEP.cams61.rerun',
'EMEP.cams50.u3all', 'EMEP.cams50.u3da', 'SILAM.cams61.rerun',
'MONARCH.cams61.rerun','EURAD-IM.cams61.rerun', 'MINNI.cams61.rerun',
'DEHM.cams61.rerun', 'MATCH.cams61.rerun', 'CHIMERE.cams61.rerun',
'LOTOSEUROS.cams61.rerun', 'CAMSRA.cams61.rerun']
```
Are these the right models @hansbrenna?

It showed the following variables are missing:
```
EMEP.cams50.u3all: ['ts', 'ps']
EMEP.cams50.u3da: ['ts', 'ps']
MONARCH.cams61.rerun: ['concno3c']
EURAD-IM.cams61.rerun: ['concno3c']
MINNI.cams61.rerun: ['concno3c']
MATCH.cams61.rerun: ['ts', 'ps', 'concno3c', 'concno3f', 'vmrhno3', 'concnh4', 'vmrnh3']
CHIMERE.cams61.rerun: ['ts']
LOTOSEUROS.cams61.rerun: ['ts', 'ps', 'concno3c', 'vmrnh3']
CAMSRA.cams61.rerun: ['ts', 'ps', 'concno3c', 'concno3f', 'concnh4', 'vmrnh3']
```

**Comment by hansbrenna** [comment]
@ejgal are you reading from EBASMC or GHOST.EBAS? We also have conctno3 in EBASMC, which is already the sum of the no3 components (there should be one for NH4+NH3 as well, maybe it's not specified in variables.ini yet?). I'm not sure summing the components from the observations makes sense. As I understood it, more stations are measuring the totals than the components.

For the models, the total NO3 would be the sum of those three, and the two for total NH3/4. Converting it from vmr to conc is possible, by changing the definition of the conc* family in ReadGridded. I never had time to finish the recursive conversion vmr->mmr->conc using ps and ts to calculate rho.

Those are the models we're using. CAMSRA and MATCH are missing a lot of data anyway. Some models have not submitted everything, which is fine I guess.

When ps/ts is missing we should talk to them. Or are they all using the same meteorology? if so we could think about a solution using the other model's ps and ts.

**Comment by hansbrenna** [comment]
LOTOSEUROS only submitted ps and ts for NativeLevels. We can probably extract a ModelLevel or Surface-type file from those. The alternative EMEP versions are variants of the new operational CAMS50 EMEP. If we include them going forward, I think Alvaro can provide ps and ts.

CAMSRA is the global ECMWF model which were never going to submit everything.

**Comment by ejgal** [comment]
EBASMC. I added the NH4+NH3 component in ebas_config.ini and in variables.ini. I called it conctnh, not sure if there's a better name for it. See #244.

**Comment by jgliss** [comment]
> @ejgal are you reading from EBASMC or GHOST.EBAS? We also have conctno3 in EBASMC, which is already the sum of the no3 components (there should be one for NH4+NH3 as well, maybe it's not specified in variables.ini yet?). I'm not sure summing the components from the observations makes sense. As I understood it, more stations are measuring the totals than the components.
> 
> For the models, the total NO3 would be the sum of those three, and the two for total NH3/4. Converting it from vmr to conc is possible, by changing the definition of the conc* family in ReadGridded. I never had time to finish the recursive conversion vmr->mmr->conc using ps and ts to calculate rho.
> 
> Those are the models we're using. CAMSRA and MATCH are missing a lot of data anyway. Some models have not submitted everything, which is fine I guess.
> 
> When ps/ts is missing we should talk to them. Or are they all using the same meteorology? if so we could think about a solution using the other model's ps and ts.

@hansbrenna just to clarify: @ejgal is reading conctno3 from EBASMC and implemented now also NH3+NH4 from EBAS as provided. Since this works (but is in units `ug N m-3`) he started looking already into how we can compute the summed variables from the models and convert to that unit.

**Comment by jgliss** [comment]
> EBASMC. I added the NH4+NH3 component in ebas_config.ini and in variables.ini. I called it conctnh, not sure if there's a better name for it. See #244.

Ah :) `contnh` seems okay.

**Comment by jgliss** [comment]
> LOTOSEUROS only submitted ps and ts for NativeLevels. We can probably extract a ModelLevel or Surface-type file from those. The alternative EMEP versions are variants of the new operational CAMS50 EMEP. If we include them going forward, I think Alvaro can provide ps and ts.
> 
> CAMSRA is the global ECMWF model which were never going to submit everything.

I think we should start with the models where we can actually compute both NH4+NH3 and HNO3+NO3 for now from the models that have everything available, that is needed to compute the sum in units of `ug N m-3`, so we can compare with the observations. But would be good to ask Alvaro or Jan, if they could in parallel compute T and P for the other models. Or ask the modellers to provide these fields at  ModelLevel or Surface.

**Comment by hansbrenna** [comment]
I agree that we should work on the ones with everything submitted first :)

**Comment by jgliss** [comment]
@hansbrenna since HNO3+NO3 is on top of the variables to process, do you have a suggestion how to best compute this from the model output (concno3c+concno3f+vmrhno3), and in units of nitrogen mass (i.e. 'ug N m-3')?

**Comment by ejgal** [comment]
I tried doing this with cube_read_methods and model_read_aux as we talked about @jgliss (only for conctno3 for now). I used the cube methods from branch dev_gridded_conc_from_vmr for converting from vmr to . Not sure to what degree these work correctly at the moment @hansbrenna.

It doesn't look that bad, but I have no idea if f.e. concno3c/f are contributing the most and then masks any conversion errors...

![Selection_009](https://user-images.githubusercontent.com/23613579/100105179-59523100-2e67-11eb-959f-c7fc07444883.png)


cube_read_methods.py - https://gist.github.com/ejgal/ada2f470ffc39a54f7b75e08c16fd114
config - https://gist.github.com/ejgal/0e81494fced50d7eb790e2051473e3af

Here are the different units for these variables in the models (where available) which we have to deal with if we want to solve it this way:
```
'concno3c': ['ug/m3', 'ug/m3', 'ug/m3', 'ug/m3', 'ug/m3', 'ug/m3', 'ug/m3'],
'concno3f': ['ug/m3', 'ug/m3', 'ug/m3', 'ug/m3', 'ug m-3', 'ug/m**3', 'ug/m3', 'ug/m3', 'ug/m3', 'ug/m3'],
'vmrhno3': ['ppb', 'ppb', 'ppb', 'ppb', 'ppb', '1e-9', 'ppb', 'ppb', 'ppb', 'ppb']
```

**Comment by jgliss** [comment]
Great! @hansbrenna this should suffice for the conctno3 evaluation (NO3c + NO3f + HNO3). Can you check that and see if you can make it work with Eiriks code?

**Comment by hansbrenna** [comment]
The functions for converting vmr to conc are finished and uses STP as specified in the functions. I'll try to see if it all works. @ejgal which branch should I get the code from?

**Comment by jgliss** [comment]
@hansbrenna additional computation functions (like in this case) can be also defined outside of pyaerocom, which is what Eirik did here. These are defined in:

https://gitlab.met.no/aerocom-evaluation/data/-/tree/master/eval_py

Eirik's latest definitions (for concno3t) are not in there yet. @ejgal can you update the "data" repo with your changes? Or send a merge request? In that case you can also point Hans to the example config file in the data repo, that he can use as a template.

Cheers

**Comment by ejgal** [comment]
For the pyaerocom branch I think we need to merge the functions from dev_gridded_conc_from_vmr and the new+updated variable definitions from check_ebas.
For now I just copied over the conversion functions so that using cube_read_methods.py with other pyaerocom branches won't crash. @jgliss, should we merge in just the variable changes from check_ebas?

**Comment by hansbrenna** [comment]
I see. I can use his files to test, but I need the variable definitions I guess.

**Comment by ejgal** [comment]
Example cfg and update cube_read_methods.py: https://gitlab.met.no/aerocom-evaluation/data/-/merge_requests/1

**Comment by ejgal** [comment]
https://github.com/metno/pyaerocom/blob/3c5259f2fe46a158f5f9ee8d03994cbf88dc43aa/pyaerocom/data/ebas_config.ini#L215-L225

https://github.com/metno/pyaerocom/blob/3c5259f2fe46a158f5f9ee8d03994cbf88dc43aa/pyaerocom/data/variables.ini#L2522-L2528

**Comment by ejgal** [comment]
Oh, there are also changes in molmasses.py.

Maybe better if I create a new branch off main-dev and merge in the changes from check_ebas and dev_gridded_conc_from_vmr that is needed?

**Comment by hansbrenna** [comment]
You decide. You could also only make a branch with the variable definition changes etc. and leave the vmr to conc out for now and I can merge those changes into my branch and test with the functions outside pyaerocom.

**Comment by ejgal** [comment]
Use this branch @hansbrenna - https://github.com/metno/pyaerocom/tree/conctno3_definitions
It should work with the read_cube_methods from https://gitlab.met.no/aerocom-evaluation/data/-/merge_requests/1

**Comment by hansbrenna** [comment]
Thanks, I'll test now.

**Comment by hansbrenna** [comment]
I was able to run your example config and get the same results you got. Going to test it in the context of the full evaluation setup when my current run finishes.

**Comment by jgliss** [comment]
Great that you managed to make it work! I am a little confused with all these branches you are working on (and which "histories" they carry around with them) so go ahead with your workflow. In general, if you work on a new feature, please branch off `main-dev` and best if you instantiate a PR draft right away, to keep an overview.

The vmr to conc functionality should also go via PR into `main-dev` soon.

**Comment by ejgal** [comment]
Great! Should I implement the same type of solution for conctnh?

**Comment by jgliss** [comment]
Yes, @ejgal that would be great, thanks!

**Comment by ejgal** [comment]
Added calc_contnh in cube_read_methods @hansbrenna. Also, check out the config for a better way to set up model_read_aux.

Branch conctno3_definition has a small update in molmasses.py which is necessary.

These are the models with the necessary variables to calculate conctno and conctnh:
```
conctno
EMEP.cams61.rerun
EMEP.cams50.u3all
EMEP.cams50.u3da
SILAM.cams61.rerun
MONARCH.cams61.rerun
EURAD-IM.cams61.rerun
MINNI.cams61.rerun
DEHM.cams61.rerun
CHIMERE.cams61.rerun
LOTOSEUROS.cams61.rerun

conctnh
EMEP.cams61.rerun
EMEP.cams50.u3all
EMEP.cams50.u3da
SILAM.cams61.rerun
DEHM.cams61.rerun
CHIMERE.cams61.rerun
LOTOSEUROS.cams61.rerun
```

**Comment by hansbrenna** [comment]
Thanks Eirik. I'll test it asap

**Comment by hansbrenna** [comment]
Fro some models the operations does not work even though the variables are available.

I think it's caused by limitations to this operation `conctno3 = concno3 + conchno3`. If I replace it `conctno3 = add_cubes(concno3,conchno3)` I think it's more robust to small differences in the grid.

**Comment by hansbrenna** [comment]
We also need to make calc_conctno3 work if concno3c is missing from a model data set.

**Comment by hansbrenna** [comment]
@jgliss @ejgal This is weird. When I run the tNH processing for some models (at least DEHM and MINNI) it works on my laptop, but not on PPI, even though I use the same pyaerocom branch which is fully up to date.

There are no diffs between either local branch and the remote branch, so they should be identical.

The actual error happens in `colocation_auto.py:_run_gridded_ungridded()`:

```Python
 ts_type_src = model_data.ts_type #error happens here
 rshow = self._eval_resample_how(model_var, obs_var)
```

When I run it on PPI model_data.ts_type is undefined, but on my laptop it works fine. Has either of you encountered this type of issue before?

Could it have something to do with the specific versions of the dependencies? 

Traceback coming soon.

**Comment by hansbrenna** [comment]
Traceback:

```
Traceback (most recent call last):
  File "/home/hansb/pyaerocom/pyaerocom/colocation_auto.py", line 376, in run
    self.data[self.model_id] = self._run_gridded_ungridded(var_name)
  File "/home/hansb/pyaerocom/pyaerocom/colocation_auto.py", line 809, in _run_gridded_ungridded
    ts_type_src = model_data.ts_type
  File "/home/hansb/pyaerocom/pyaerocom/griddeddata.py", line 164, in ts_type
    self.infer_ts_type()
  File "/home/hansb/pyaerocom/pyaerocom/griddeddata.py", line 337, in infer_ts_type
    raise ValueError('Could not identify unique frequency')
ValueError: Could not identify unique frequency
```

**Comment by jgliss** [comment]
@hansbrenna that sounds strange, nothing I have encountered so far. Isn't this variable calculated in post as sum of some other variables? And maybe this function is defined eval_py dir in `data` repo?

https://gitlab.met.no/aerocom-evaluation/data/-/blob/master/eval_py/cube_read_methods.py

Maybe you use different versions of that function?

**Comment by hansbrenna** [comment]
No, it's the same cube_read_methods file on lustre. And most models work. Only some fail. I'll keep digging.

**Comment by jgliss** [comment]
OK, which branch are you working on?

**Comment by jgliss** [comment]
And which iris version do you have installed on lustre vs local, you can see the version via `conda list iris`.

**Comment by hansbrenna** [comment]
Hans_main_dev. I tried it on main-dev as well, but not all necessary developments have been merged in there yet.

**Comment by hansbrenna** [comment]
The iris version is the same on both machines

iris                      2.4.0                    py37_0    conda-forge

**Comment by hansbrenna** [comment]
I was able to recreate the problem outside of the web processing by running this script (test.py) in the same dir as cube_read_methods. You can find both here /lustre/storeA/project/fou/kl/CAMS61/postprocessed_data/repositories/aerocom_evaluation/data_subbed/eval_py

```Python
import pyaerocom as pya
import cube_read_methods as cr

model = 'MINNI.cams61.rerun'

obs_net = 'EBASMC'

var = 'conctnh'

mod_read = pya.io.ReadGridded(model)

nh4 = mod_read.read_var('concnh4')
nh3 = mod_read.read_var('vmrnh3')

tnh=pya.GriddedData(cr.calc_conctnh(nh4,nh3))
tnh.var_name='conctnh'
```

On my laptop running `tnh.ts_type` returns `'hourly'` while on PPI I get the following traceback:

In [3]: tnh.ts_type                                                                                                                                                                                         
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-b1126a7d2aba> in <module>
----> 1 tnh.ts_type

~/pyaerocom/pyaerocom/griddeddata.py in ts_type(self)
    162         """Temporal resolution"""
    163         if self.metadata['ts_type'] == 'n/d':
--> 164             self.infer_ts_type()
    165 
    166         return self.metadata['ts_type']

~/pyaerocom/pyaerocom/griddeddata.py in infer_ts_type(self)
    335         dt = np.unique(self.delta_t)
    336         if len(dt) > 1:
--> 337             raise ValueError('Could not identify unique frequency')
    338         dt = dt[0]
    339         for ts_type, freq in TS_TYPE_TO_NUMPY_FREQ.items():

ValueError: Could not identify unique frequency

Using EMEP instead of MINNI, it works both places.

**Comment by jgliss** [comment]
Is this a local version of cube_read_methods? [Here](https://gitlab.met.no/aerocom-evaluation/data/-/blob/master/eval_py/cube_read_methods.py) there is no such method `calc_conctnh`.

**Comment by hansbrenna** [comment]
It's local for now, yes. You can find it on PPI

**Comment by jgliss** [comment]
It is a bit hard to diagnose this without seeing this custom method. But you should make sure to that `ts_type` is assigned in the `cube` that is returned by this object.

**Comment by hansbrenna** [comment]
I've pushed the updated red_cube_methods.py to the repository.

**Comment by hansbrenna** [comment]
I debugged the `calc_conctnh()` function for the DEHM model on PPI and found where the ts_type attribute is lost. I don't think these functions are written in a way which robustly preserves metadata, and that probably includes mmr_from_vmr(), conc_from_vmr_STP() and calc_conctno3() as well. Can you help a little @jgliss?

```Python
def calc_conctnh(concnh4, vmrnh3):
    if concnh4.units == 'ug m-3' or concnh4.units == 'ug/m**3':
        concnh4.units = 'ug/m3'
    if vmrnh3.units == '1e-9':
        vmrnh3.units = 'ppb'
    assert concnh4.units == 'ug/m3'
    assert vmrnh3.units == 'ppb'

    concnh3 = conc_from_vmr_STP(vmrnh3.cube)
    concnh3.units = 'ug/m3'
    concnh3 *= M_N / (M_N + M_H * 3)
    concnh4 = concnh4.cube #<====== After this operation, concnh4 no longer has attribute ts_type
    concnh4 *= M_N / (M_N + M_H * 4)
    conctnh = add_cubes(concnh3, concnh4)
    conctnh.units = 'ug N m-3'
    return conctnh
```

**Comment by hansbrenna** [comment]
I think this works now

```Python
def calc_conctnh(concnh4, vmrnh3):
    if concnh4.units == 'ug m-3' or concnh4.units == 'ug/m**3':
        concnh4.units = 'ug/m3'
    if vmrnh3.units == '1e-9':
        vmrnh3.units = 'ppb'
    assert concnh4.units == 'ug/m3'
    assert vmrnh3.units == 'ppb'

    concnh3 = conc_from_vmr_STP(vmrnh3.cube)
    concnh3.units = 'ug/m3'
    concnh3 *= M_N / (M_N + M_H * 3)
    concnh4_ts_type = concnh4.ts_type
    concnh4 = concnh4.cube
    concnh4 *= M_N / (M_N + M_H * 4)
    conctnh = add_cubes(concnh3, concnh4)
    conctnh.attributes['ts_type']=concnh4_ts_type
    conctnh.units = 'ug N m-3'
    return conctnh
```

**Comment by hansbrenna** [comment]
@ejgal Do you have any idea for how we might make `calc_conctno3` work when `concno3c` is missing from a model?

**Comment by ejgal** [comment]
Great @hansbrenna!

Hmm. Should we then only use concno3f?

**Comment by hansbrenna** [comment]
Yes. according to Hilde, some models don't separate the NO3 aerosol into fin and coarse components.

**Comment by ejgal** [comment]
I see.

Maybe wrap it like this
```
def calc_conctno3_fine(concno3f, vmrhno3):
    return calc_conctno3(concno3f, concno3c=None, vmrhno3)
```
redefine model_read_aux for the models with only concno3f
```
"model_read_aux": { "conctno3": {
               "vars_required": ["concno3f", "vmrhno3"],
               "fun": "calc_conctno3_fine"
            }
```

and change calc_conctno3 to check for concno3c=None and then only using concno3f.

**Comment by hansbrenna** [comment]
This should work I think. i'll try it. Thanks

**Comment by hansbrenna** [comment]
I did it like this:

```Python
def calc_conctno3(concno3c, concno3f, vmrhno3):
    if concno3c != None:
        if concno3c.units == 'ug m-3' or concno3c.units == 'ug/m**3':
            concno3c.units = 'ug/m3'
        assert concno3c.units == 'ug/m3'

    if vmrhno3.units == '1e-9':
        vmrhno3.units == 'ppb'
    assert concno3f.units == 'ug/m3'
    assert vmrhno3.units == 'ppb'

    in_ts_type = vmrhno3.ts_type
    if concno3c != None:
        concno3 = add_cubes(concno3f.cube, concno3c.cube)
    else:
        concno3 = concno3f

    conchno3 = conc_from_vmr_STP(vmrhno3.cube)
    conchno3.units = 'ug/m3'
    concno3 *= M_N / (M_N + M_O * 3)
    conchno3 *= M_N / (M_H + M_N + M_O * 3)
    conctno3 = add_cubes(concno3,conchno3)
    conctno3.attributes['ts_type']=in_ts_type
    conctno3.units = 'ug N m-3'
    return conctno3

def calc_conctno3_fine(concno3f, vmrhno3):
    return calc_conctno3(concno3f=concno3f, concno3c=None, vmrhno3=vmrhno3)
```

Will test now.

**Comment by hansbrenna** [comment]
I'm having problems getting the web processing to understand that there's a new function in the file. I get the following error:

`ValueError: File ../eval_py/cube_read_methods.py does not contain custom read method: calc_fine_conctno3`

Usually when I get hhis kind of error it's because Python is importing a cached version of the file, but I deleted the .pyc file and restarted spyder so it should be clean...

i also changed the name to `calc_fine_conctno3` so the other function would not be a substring of it, just in case that caused any problems.

**Comment by ejgal** [comment]
Did you update FUNS in `cube_read_methods'?


```
FUNS = {'add_cubes'         : add_cubes,
        'subtract_cubes'    : subtract_cubes,
        'divide_cubes'      : divide_cubes,
        'multiply_cubes'    : multiply_cubes,
        'calc_ae'           : compute_angstrom_coeff_cubes,
        'calc_conctno3'     : calc_conctno3,
        'calc_conctnh'      : calc_conctnh,
        'calc_fine_conctno3': calc_fine_conctno3
        }
```

**Comment by hansbrenna** [comment]
I guess that's the problem. Thanks!

**Comment by hansbrenna** [comment]
Seems to be working!! :)

**Comment by ejgal** [comment]
Great!

**Comment by ejgal** [comment]
Seems this is fixed, feel free to reopen if not.
