### ISSUE TITLE
Tests not running after recent changes to actions

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#245]
Our test suite is not running anymore after set-env and att-path was deprecated due to security issues ([link](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).
I'm guessing one of those commands are used by [setup-conda](https://github.com/s-weigand/setup-conda)
or [checkout](https://github.com/actions/checkout).
We could try using the latest version of both as a possible quickfix, or look into other workarounds.

**Comment by jgliss** [comment]
@ejgal thanks for pointing that out!! Can you try to fix it? Maybe define a new "action" file instead of modifying the current one?

**Comment by jgliss** [comment]
I think this can be closed.
