### ISSUE TITLE
Missing argument var_name in function colocate_gridded_ungridded

### ISSUE THREAD

**Issue by eivindgw** [metno/pyaerocom#25]
The function pyaerocom.colocation.colocate_gridded_ungridded does not have an explicit input argument var_name, as is indicated in the doc-string. It is still possible to specify var_name as a key-value argument, but it does not appear to do anything. The function actually appears to use the var_name stored in the GriddedData object, and not the name provided as function input (in line 196, the first line after the doc-string).

**Comment by jgliss** [comment]
This should be fixed by now. The variable name for the model is implicit from the input `GriddedData` and `var_ref` may be used to specify if a different variable should be used from the observations. 

Closing this.
