### ISSUE TITLE
Using STP instead of T and P to convert vmr -> conc

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#250]
I did some quick calculations and the maximum difference in air density I could get between standard rho and rho for "reasonable" extremes was ~25% for 30 C at 850 hPa.

P                T      Error
850 hPa, -10 C: 9%
850 hPa, 15 C: 19%
850 hPa, 30 C: 25%
1013 hPa, -10 C: 9%
1013 hPa, 30 C: 5%

**Comment by jgliss** [comment]
@hansbrenna I get similar results (see email that I just sent). Let's to std. atm. for now and we work on a fix in parallel! Good to have this here as an issue.
