### ISSUE TITLE
How to add more data to an already run evaluation case without having to rewrite all json files

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#251]
I keep "breaking" my runs by trying to rerun one (or a few) observation case for all models or one model for all observations and ending up with a heatmap on the web interface containing only that (or those) entries that were calculated in the last run. 

While the maps and time series are still there for all models and cases, I've found no way to correct the heatmap without re-creating all the json files, which for the limited CAMS61 case I have set up now takes a few hours, and will take more when I set up more obs_config entrie.

It is also not clear to me when the overwrite of the heatmap is triggered, becasue I sometimes seem to be able to add more models to it, but now I'm just very confused.

Is there a way to add more models or observations (or rerun one case) without killing the full heatmap? Or equivalently, a way of recreating the full heatmap afterwards. @jgliss

**Comment by ejgal** [comment]
How are you currently rerunning? Are you changing the call to run_evaluation or the config entries?

**Comment by hansbrenna** [comment]
I'm changing the config entries

**Comment by ejgal** [comment]
I think commenting out model or obs entries in the config will mess with menu.json which is used in `update_heatmap_json()`.

Try changing `stp.run_evaluation()` instead.
F.e. `stp.run_evaluation(var_name='od550aer')` will rerun everything related to that variable.
You can also specify model_name and obs_name (which I think can use wildcards).

**Comment by hansbrenna** [comment]
OK. I'll look into that. 

What about adding more obs_config or model_config entries?

**Comment by ejgal** [comment]
I think you could run f.e. `stp.run_evaluation(model_name='EMEP.u3da')` after adding that to model_config, and it should be processed without touching the files that has already been calculated for other models.

Relevant part of run_evaluation:
```
        if model_name is None:
            model_list = list(self.model_config)
        else:
            model_list = self.find_model_matches(model_name)

        if obs_name is None:
            obs_list = list(self.obs_config)
        else:
            obs_list = self.find_obs_matches(obs_name)
```
If I understand this correct then not specifying model_name or obs_name will make run_evaluation loop through all entries in model_config or obs_config. Same with var_name.

**Comment by hansbrenna** [comment]
Thanks!

**Comment by jgliss** [comment]
Exactly, what is displayed online is only what is currently specified in the config! Thus, if you comment out models or observations, it will remove them from the interface.

**Comment by jgliss** [comment]
You can also set `reanalyse_existing` to False, which will skip colocation of the model / obs / var combinations for which  colocated .nc files already exist. However, I think the latter will still trigger re-computation of the json files, which should be fixed at some point

**Comment by hansbrenna** [comment]
I set `reanalyse_existing=False` It still triggers the recomputation of the json files, which is a significant part of the runtime for CAMS61. I will test giving arguments to run_evaluation next time.

**Comment by hansbrenna** [comment]
Closing this. Thanks for the help.
