### ISSUE TITLE
When setting custom time resampling model with 3hourly time resolution stops working in the evaluation

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#252]
When setting custom time resampling constraints, the model with resolution `'3hourly'` stops working. When I do not set the custom constraints in the config file, it works. Do any of you know why?

```
apply_time_resampling_constraints=True,
min_num_obs = {'yearly': {'monthly': 9},
    'monthly': {'weekly': 3},
    'weekly': {'daily': 5},
    'daily': {'hourly': 18},
    'hourly': {'minutely': 45}},
```

**Comment by jgliss** [comment]
@hansbrenna I think the `TimeResampler` ignores multiplication factors (such as *3* in *3daily*), so it would treat the 3hourly as hourly and then it will not work since a day cannot have 18 3hourly values.

**Comment by jgliss** [comment]
```python
import pyaerocom as pya
import numpy as np
import pandas as pd

# get default resampling "min_num_obs"
min_num_obs_default = pya.const.OBS_MIN_NUM_RESAMPLE

# get stricter constraints (from Hans issue)
min_num_obs_custom = {'yearly': {'monthly': 9},
                      'monthly': {'weekly': 3},
                      'weekly': {'daily': 5},
                      'daily': {'hourly': 18},
                      'hourly': {'minutely': 45}
                      }

# make hourly fake data
idx_hr = pya.helpers.make_datetime_index('1-1-2018', '1-2-2018', 'h')

data = np.ones_like(idx_hr).astype(float)

s_hr = pd.Series(data, idx_hr)

# make 3hourly fake data
idx_3hr = pya.helpers.make_datetime_index('1-1-2018', '1-2-2018', '3h')

data = np.ones_like(idx_3hr).astype(float)

s_3hr = pd.Series(data, idx_3hr)

# test conversion

resampler = pya.TimeResampler(s_hr)

daily_from_hourly_default = resampler.resample(to_ts_type='daily',
                                               from_ts_type='hourly')

resampler.input_data = s_3hr
daily_from_3hourly_default = resampler.resample(to_ts_type='daily',
                                                from_ts_type='3hourly')

resampler = pya.TimeResampler(s_hr)

daily_from_hourly_custom = resampler.resample(to_ts_type='daily',
                                              from_ts_type='hourly',
                                              min_num_obs=min_num_obs_custom)

resampler.input_data = s_3hr
daily_from_3hourly_custom = resampler.resample(to_ts_type='daily',
                                                from_ts_type='3hourly',
                                                min_num_obs=min_num_obs_custom)
```

**Comment by jgliss** [comment]
This code illustrates the issue. So the last resampling operation will return a Series containing only NaNs. One workaround could be that you specify "min_num_obs" explicitly for the 3hourly model in its config entry?

**Comment by jgliss** [comment]
Rethinking this, I think this should be considered a bug, and I will try to fix it right away, I see 2 options:

If there is an entry in `min_num_obs` for one of the "hierarchical steps" (e.g. *16* for hourly-> daily) and the initial resolution is lower than hourly (e.g. 3hourly, i.e. `mulfac=3`), then either

1. It should ignore the min_num_obs entry (here *16*) completely and make a daily mean, even if there is only one 3hourly value, or
2. It could do something like `int(np.floor(16/3))` (less restrictive) or `int(np.ceil(16/3))` (more restrictive) to compute a new `min_num_obs` that matches the actual resolution. 

2 sounds better but I am not sure of edge cases that may occur.
