### ISSUE TITLE
plot_station_coordinates based on station name

### ISSUE THREAD

**Issue by hannasv** [metno/pyaerocom#26]
Include functionality in plot_station_coordinates in order to plot station coordinates based on  station name.

**Comment by jgliss** [comment]
I think this refers to `UngriddedData.plot_station_coordinates`. This method is not supposed to plot individual site locations. You may plot individual site location coordinates by filtering the data first, e.g. `UngriddedData.filter_by_meta(station_name='Bondville').plot_station_coordinates()`.

Closing this!
