### ISSUE TITLE
using resample_how='max' stops unit from being inferred when colocating

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#263]
@jgliss Since yesterday, colocation fails when using `resample_how='max'. It prints the following warning:

`Cannot infer unit when aggregating using max. Please set unit in returned data object!`

I've tracked it to the commit b04bd27 with commit message: "Minor updates in GriddedData.resample_time (i.e. only keep unit for aggr mean, median, std)"

In griddeddata.py function _resample_time_xarray() you added:
```
        if how in ('mean', 'median', 'std'):
            data.units = self.units
        else:
            print_log.info(
                f'Cannot infer unit when aggregating using {how}. Please set '
                f'unit in returned data object!')
```

Can 'max' be safely added to the list of accepted aggregators?

**Comment by hansbrenna** [comment]
I tried adding `'max'` to the accepted aggregator functions, and that works for normal colocation.

If resample_how is specified as a dictionary in the web config file (like `resample_how={'vmro3' : {'daily' : {'hourly' : 'max','3hourly':'max'}}}`), it is still a dictionary when the check in _resample_time_xarray is performed. e.g. 

`how={'daily': {'hourly': 'max', '3hourly': 'max'}}`

This change does not work as expected.

**Comment by hansbrenna** [comment]
Attempted solution:

Add 
```
if isinstance(how,dict):
            how = how[to_ts_type][self.ts_type]
```
before check. Testing

**Comment by hansbrenna** [comment]
This is probably not the right solution...

**Comment by jgliss** [comment]
@hansbrenna these are 2 things you refer to here, correct? The first one (which you already fixed in your main dev branch) has now also been fixed in `main-dev`. The second one (specifying 2 "from" frequencies for a resampling step) I have to look into.

**Comment by jgliss** [comment]
@hansbrenna you could also specify min_num_obs explicitly in the model_config entry of CAMSRA (which is the model with 3hourly, right) and then leave out the hourly entry. Maybe this would work as a quick fix for O3 max?

**Comment by hansbrenna** [comment]
I see. I think I can fix it by adding the 3hourly to the model config entry.

**Comment by hansbrenna** [comment]
Even when using only one entry in the resample how dict `resample_how={'vmro3' : {'daily' : {'hourly' : 'max'}}},` I still need the check for type of how in `resample_how='max'`.
```
        if isinstance(how,dict):
            how = how[to_ts_type][self.ts_type]
```
You did not include that in your fix. If I don't include it, how is still a dict when checking for valid aggregators.

**Comment by jgliss** [comment]
@hansbrenna True, thanks for spotting this. I will include it in main-dev. I guess for you it works now?

**Comment by hansbrenna** [comment]
Yes. I believe it does. I have tested it quite extensively this morning.

**Comment by hansbrenna** [comment]
Can I close this?

**Comment by jgliss** [comment]
I will close it when I have implemented a proper solution for it (if `how` is a dict it needs to check each resampling "step"). I will implement that in `TimeResampler`.

**Comment by jgliss** [comment]
@hansbrenna this worked now for you, right? If yes, I think this can be closed :)

**Comment by hansbrenna** [comment]
yes. Can be closed
