### ISSUE TITLE
CAMSRA no longer readable in main-dev still readable in older branch (9 days since last commit)

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#264]
@jgliss I think this is another bug introduced when merging the ebas stuff into main-dev. CAMSRA is no longer readable in main-dev (or my main dev branch which I synced yesterday or Monday). In the dev_gridded_conc_from_vmr branch it's still readable. 

It fails with the following message when running `pya.browse_database('*CAMSRA.cams61*')`:

`Reading failed for CAMSRA.cams61.rerun. Error: VariableDefinitionError('Error (VarCollection): input variable mmrprcpoxn is not supported')`

It doesn't work when using the web evaluation setup either (working in the older branch), failing with:

`pyaerocom.exceptions.DataCoverageError: No variable matches between CAMSRA.cams61.rerun and GHOST.EEA.daily for input vars: ['concpm10', 'concpm25', 'vmrno2', 'vmrso2']`

But it seems to work when doing simple low-level colocation.

**Comment by jgliss** [comment]
@hansbrenna sorry about that, I had that one fixed in another branch which I merged into `main-dev` now...

**Comment by jgliss** [comment]
Let me know if this does not fix it!

**Comment by jgliss** [comment]
@hansbrenna can this be closed?
