### ISSUE TITLE
Ts_type is sometimes passed to ReadGridded.read_var as dictionary instead of string

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#276]
`Colocator._read_gridded` can pass ts_type as a dictionary when calling reader.read_var if `model_ts_type_read` is defined as a dictionary.
There is some logic in `ReadGridded._eval_vert_which_and_ts_type` that is capable of handling dictionaries, but the expected value of ts_type is a string.

#272 ensures that ts_type is passed as a string. This should probably be revisited at some point, to make sure there arent' use cases for passing it as a dictionary.
If not `_eval_vert_which_and_ts_type` should probably be simplified and renamed `__eval_vert_which`.

**Comment by jgliss** [comment]
Can this be closed?
