### ISSUE TITLE
Fallback logic in TimeResampler._gen_idx() overwrites argument 'how'

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#277]
At the end of TimeResampler._gen_idx() (line 125-126) there's some logic to make a resampling tuple when generating it does not fully work. This logic silently defaults to how='mean' even when how is specified to be another function, like median or sum.
```Python
        if len(idx) == 0  or not idx[-1][0] == to_ts_type.val:
            idx.append((to_ts_type.val, 0, 'mean'))
```
I ran into this when testing precip from EBAS. Since `'weekly'` is not specified in the default `min_num_obs['monthly']` it jumps to this default fallback. I'm not sure if this is a bug or a feature made for a good reason.

Would it be safe to change it to  the following @jgliss?
```Python
        if len(idx) == 0  or not idx[-1][0] == to_ts_type.val:
            idx.append((to_ts_type.val, 0, _how))
```

**Comment by hansbrenna** [comment]
Changing it to
```Python
        if len(idx) == 0  or not idx[-1][0] == to_ts_type.val:
            _how = how_default
            idx.append((to_ts_type.val, 0, _how))
```
works for my case, but I'm not sure it's safe since I don't fully understand the logic in this method.

**Comment by jgliss** [comment]
@hansbrenna I think this is indeed a bug and your solution seems to be the way it should be done (`_how` was introduced very recently and I missed to replace `"mean"` with `_how`. Can you make a PR for this? Into `main-dev` and also `release_0_10_0`?

**Comment by hansbrenna** [comment]
Thanks. I will do that, then.

**Comment by jgliss** [comment]
@hansbrenna I guess this can be closed?
