### ISSUE TITLE
GriddedData with ts_type='3hourly' not supported for concprcp* coalculation

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#294]
I'm looking into this now, but probably won't have time to implement a fix before my vacation.

Running the concprcp variables for CAMSRA which has 3hourly resolution fails since there's a mismatch between the units, which are 'h-1' and the ts_type which is 'daily'. The traceback is:
```
  File "/home/hansb/pyaerocom/pyaerocom/io/readgridded.py", line 132, in check_wdep_units
    raise NotImplementedError(f'Cannot yet handle wdep in {unit} but '
NotImplementedError: Cannot yet handle wdep in mg N m-2 h-1 but daily sampling frequency
```
I see that this is a check for something that's not implemented already. It seems like the GriddedData is resampled to dailym but the unit is not updated.

**Comment by hansbrenna** [comment]
I had it wrong. The data is (unlike other CAMSRA data) in daily frequency. This explains why it has this mismatch. Should be easier to fix maybe.

Working on debugging.

**Comment by hansbrenna** [comment]
I tried updating the units in the CAMSRA data to be consistent with the TsType. Multiplied the data by 24 and changed the units to be relative to d-1. This seems to work after I added the wet deposition unit as a unit alias. 

I kept the unmodified data in the directory as backup.

**Comment by hansbrenna** [comment]
I was able to run the analysis using the updated units/data. I will keep this open for now.

**Comment by avaldebe** [comment]
Is this issue still relevant?

**Comment by avaldebe** [comment]
Looks like this is no longer a problem.
Please re-open if needed.
