### ISSUE TITLE
Init mounted user server at location other than root

### ISSUE THREAD

**Issue by bikasbhattarai** [metno/pyaerocom#3]
Read data/paths_user_server.ini file misses some obs network specifications 

```
pya.const.BASEDIR = '/home/bikascb/aerocom/aerocom-users-database/'
pya.const.read_config(config, keep_basedirs=True)
``` 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-94-31bd891bfb59> in <module>
      1 pya.const.BASEDIR = '/home/bikascb/aerocom/aerocom-users-database/'
----> 2 pya.const.read_config(config, keep_basedirs=True)

~/anaconda3/envs/NEGI-Andoya-workshop/lib/python3.6/site-packages/pyaerocom/config.py in read_config(self, config_file, keep_basedirs)
    448         self.AERONET_SUN_V3L2_SDA_ALL_POINTS_NAME = cr['obsnames']['AERONET_SUN_V3L2_SDA_ALL_POINTS']
    449         # inversions
--> 450         self.AERONET_INV_V3L15_DAILY_NAME = cr['obsnames']['AERONET_INV_V3L15_DAILY']
    451         self.AERONET_INV_V3L2_DAILY_NAME = cr['obsnames']['AERONET_INV_V3L2_DAILY']
    452 

~/anaconda3/envs/NEGI-Andoya-workshop/lib/python3.6/configparser.py in __getitem__(self, key)
   1231     def __getitem__(self, key):
   1232         if not self._parser.has_option(self._name, key):
-> 1233             raise KeyError(key)
   1234         return self._parser.get(self._name, key)
   1235 

KeyError: 'AERONET_INV_V3L15_DAILY'

**Comment by jgliss** [comment]
This issue should be resolved in the latest updates (use branch **andoya_course**). Final tests will be run soon before merge back into master and issue will be closed if tests okay after the merge.

@bikasbhattarai Please report back if problem still occurs. Thank you.

**Comment by jgliss** [comment]
Closing issue after merging with master and running all tests (just before release of v0.7.0)

**PLEASE NOTE**: we made a [new notebook](https://github.com/metno/pyaerocom/blob/master/notebooks/tut001_setup_userserver.ipynb) that shows how to setup pyaerocom when working on the [AeroCom users database](https://wiki.met.no/aerocom/data_retrieval).
