### ISSUE TITLE
colocate_gridded_ungridded with colocate_time=True fails if gridded data has higher time resolution than ungridded data

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#300]
colocating gridded hourly and ungridded daily to monthly resolution in time requires extraction of time series from gridded data with time resolution daily or greater. i.e. gridded is extracted in native resolution and not resampled to requested ts_type like normally done.

But because col_freq = str(grid_ts_type), i.e. the colocation frequency is set from the gridded data ts_type (hourly), when running _colocate_site_data_helper it will fail and raise a TemporalResolutionError since col_freq is greater than the observation ts_type

If all station data had the same frequency it would work to set col_freq to the observation ts_type in this case. But since each station can have different time resolutions in our EBAS case I think col_freq needs to be set on a station-by-station basis. Does this make sense @jgliss Gliss ?

Either I'm missing the obvious solution, or this problem is a bit more involved than I thought

**Comment by jgliss** [comment]
@hansbrenna thanks for that! I think I fixed it in the linked commit. The colocation routine checks now for the lowest available resolution in obs and updates the colocation frequency if needed.

**Comment by hansbrenna** [comment]
I think it works now. I'll look at the results to see if they look reasonable.

**Comment by hansbrenna** [comment]
I'm not sure how to interpret the results. The daily model time series still has all days in it, no only every 6th day like to observations when obs are in 6daily. Is that expected? Is the colocation in time only taken into account when resampling to monthly time series? @jgliss 
![ec-waldhof](https://user-images.githubusercontent.com/12746882/105337204-6dea4580-5bda-11eb-9d14-cc5bdfc39721.png)

**Comment by jgliss** [comment]
@hansbrenna great that it works. I think the behaviour is expected as you colocate in daily resolution (i.e. colocated data created is in daily). This will of course  not impact the statistics as they are only compute where both model and obs have daily values. If you would colocate in monthly, then model daily values where there are not obsdata would be invalidated before computing the monthly mean. See the end of colocate_gridded_ungridded: 

```python 
if col_freq != str(ts_type):
        data = data.resample_time(to_ts_type=ts_type,
                                  colocate_time=colocate_time,
                                  apply_constraints=apply_time_resampling_constraints,
                                  min_num_obs=min_num_obs,
                                  how=resample_how,
                                  **kwargs)
```

I.e. this if condition is not entered since col_freq is equal ts_type.

**Comment by jgliss** [comment]
So for the monthly statistics shown here, the  model means are computed only from the days where there are obsdata...

**Comment by hansbrenna** [comment]
That was what I thought. Then I think it works.

**Comment by hansbrenna** [comment]
When using colocate_time=True the weekly data is not included when doing monthly colocation. Pyaerocom prints the standard warning:

`concec data from site Hurdal will not be added to ColocatedData. Reason: Cannot resample time-series from weekly to daily`

Is this because the colocation routine sets the colocation frequency to daily to be able to do meaningful colocation in time?

**Comment by hansbrenna** [comment]
This is my obs config entry:
```Python
'EBAS-m'      :  dict(obs_id='EBASMC',
                           web_interface_name='EBAS-m',
                           obs_vars=['concec','conccoc','concso4','conchno3','concno310','concno325',
                                     'concss10','concss25',],
                           obs_vert_type='Surface',
                           ts_type = 'monthly',
                           colocate_time=True,
                           min_num_obs = {'yearly': {'monthly': 9},
                                          'monthly': {'daily': 4,'weekly' : 1},
                                          'daily': {'hourly': 18},
                                          'hourly': {'minutely': 45}},
                           remove_outliers=True,
                           var_ref_outlier_ranges = {'conctno3':(-1e9,1e9),'conctnh':(-1e9,1e9),
                                                     'concso4':(-1e9,1e9),'concnh3':(-1e9,1e9),
                                                     'concnh4':(-1e9,1e9),
                                                     'conchno3':(-1e9,1e9),'concno310':(-1e9,1e9),
                                                     'concno325':(-1e9,1e9),
                                                     'concss10':(-1e9,1e9),'concss25':(0,1e9),
                                                     'concec':(-1e9,1e9),'conccoc':(-1e9,1e9)},
                           obs_filters= {
                               'data_level':2,
                               **standard_filter,
                               'altitude':[-20,1000],
                               }),
```

I think `concso4` would be the easiest variable to debug since it does not require any model_read_aux or other complicated setup.

**Comment by hansbrenna** [comment]
By the way, we get the same problem when running daily colocation for concso4 since some of the data is in hourly resolution. That means all the daily and weekly data is excluded.

**Comment by jgliss** [comment]
Thanks, will check it now!

**Comment by avaldebe** [comment]
is this issue still relevant?
the last comment, seems to indicate this was fixed

**Comment by jgliss** [comment]
I think this was fixed.

**Comment by avaldebe** [comment]
thanks!
