### ISSUE TITLE
"Per station" time colocation in gridded / ungridded colocation routine

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#301]
Option `colocate_time` in `colocate_gridded_ungridded` should be able to apply "time colocation" for each obs station individually (if obsdata contains multiple resolutions based on site location). 

Consider the following examples (in all cases `colocate_time=True` in  `colocate_gridded_ungridded`): 

1. Case 1:
   - input model is `hourly`
   - input obsdata contains sites with `3hourly`, `daily`, `2weekly`
   - output colocation frequency is `monthly` (i.e. input `ts_type="monthly"` in method `colocate_gridded_ungridded`)
   
   This will use all observation sites available, since all have higher freq. than `monthly`, that is, for `3hourly` obs sites, model is resampled to `3hourly` and where obs is NaN, model is invalidated, then both `3hourly` model and obs are resampled to `monthly` and appended to output `ColocatedData` object. The same procedure is applied for the other sites, based on the corresponding obs frequencies there.

2. Case 2:
   - Like Case 1, but output colocation frequency is `weekly`

   Same procedure as 1., but observation sites in `2weekly` resolution will not be included.

3. Case 3.
   - input model is `daily`
   - input obsdata contains sites with `hourly` and `daily`
   - output colocation frequency is `weekly`
   
   All obsdata is used and the "time colocation" (i.e. invalidating model where obs is NaN) is done in `daily` resolution before resampling to output freq `weekly`.

**Comment by hansbrenna** [comment]
I think your three cases makes sens. Case 1 is the one I haven when doing monthly colocation and case 2 is analogous to the case I have when doing daily colocation.

In all cases I think your description of intended behaviour is how it should be.

**Comment by jgliss** [comment]
@hansbrenna thanks. I will push soon and let you know, I will put it as new PR into a new branch and would appreciate if you could briefly make sense of the changes, before I merge into our common branch

**Comment by hansbrenna** [comment]
I will try to check it later today.
