### ISSUE TITLE
Support for multiple entries in model_add_var

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#314]
I would really like support for lists as input to `model_add_var` in the web processing. This would allow entries like

`model_add_var = {'vmro3':['dryo3','drydepvelo3']}`

I have started the implementation of this in my main branch, and I think I got it to work for the colocation part, but I'm still struggling with the json computations because the colocated data objects has `coldata.data.attrs['var_names']=['vmro3','dryo3']` instead of `['dryo3','dryo3']`when using a list as input. I will keep working on this.

**Comment by jgliss** [comment]
I think this is a good idea @hansbrenna! Let me know if I should review some code. Note that there have been quite some updates in the web processing needed for CAMS84 (see branch `dev-cams84` and associated PR's). We should soon merge all your stuff from your main branch into `main-dev`. So please, go ahead and already create a draft PR for that. 

I am almost certain that there will be conflicts.
