### ISSUE TITLE
Specifying "ts_type" as ungridded obs filter in Colocator fails

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#319]
If `Colocator.obs_filters` is defined and contains an entry `ts_type` it will be ifgnored in the filtering of the `UngriddedData` due to the way `Colocator._eval_obs_filters` method is implemented (i.e. `ts_type` is a class attr. of Colocator itself). This is not a big problem for most cases, but in case of e.g. EBAS concpm10 data, it is needed to filter the obsdata by ts_type before running the colocation.

**Comment by avaldebe** [comment]
@lewisblake after your experience with #707, do you think this is still an issue?

**Comment by lewisblake** [comment]
That PR didn't touch much on this, but looking at the code, it appears as this may still be an issue. `ts_type` is being skipped as a filtering criterion

**Comment by lewisblake** [comment]
But it appears to be in `UngriddedData.filter_by_meta`? Admittedly I'm confused now. Maybe we should talk about this at our next meeting or wait until we have an experiment where this bug is demonstrated.

**Comment by dulte** [comment]
If I understand this issue correctly, then it is possible to get around this by setting the entries in min_num_obs very high. It is a "hack", but I think it is sufficient until someone insists on using the ts_type in Colocator.obs_filters

**Comment by avaldebe** [comment]
> If I understand this issue correctly, then it is possible to get around this by setting the entries in min_num_obs very high. It is a "hack", but I think it is sufficient until someone insists on using the ts_type in Colocator.obs_filters

This does not seem to be an urgent issue and we have enough technical debt already,
so we might try to come up with an actual fix.
