### ISSUE TITLE
Some problems with country regions in branch dev-annual-limit

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#361]
I'm not exactly sure what's going on here.

For some reason Latvia (sometimes) does not work as a country when processing heatmaps and regional time series since it is in `region_ids`, but not in `coldata.countries_available`

I think I need some help to figure this out. It's probably simple, but I'm not able to do i right now. @jgliss 

Run this file in the branch dev-annual-limit.

https://gitlab.met.no/aerocom-evaluation/data/-/blob/master/config_files/cfg_cams61_p3_test-annstat.py

**Comment by jgliss** [comment]
@hansbrenna can you also update `/eval_py/cube_read_methods.py` on GitLab? I can currently not run your config file because of some new functions in that file.

**Comment by jgliss** [comment]
@hansbrenna I managed to run this now by commenting out these additional variable, however, it seems that the model data you use in the example is hourly, and I have no idea, how long it will take on my local computer until the colocation is finished (so I can debug the json file issues you have with the countries). Perhaps you could also send me the colocated data object.

**Comment by hansbrenna** [comment]
Sorry I did not see this before. I have sent you the colocated data object. Sorry about the cube_read_methods. I will update it on gitlab.

**Comment by hansbrenna** [comment]
The updated cube_read_methods file is here 

https://gitlab.met.no/aerocom-evaluation/data/-/blob/calctno3/eval_py/cube_read_methods.py

**Comment by jgliss** [comment]
@hansbrenna I think I managed to fix this issue, see latest commits in #347

**Comment by jgliss** [comment]
Looks like this can be closed. @hansbrenna feel free to reopen if I missed something.
