### ISSUE TITLE
Ozone from EBAS in vmr

### ISSUE THREAD

**Issue by hildefagerli** [metno/pyaerocom#369]
This is the old issue that EBAS has the double amount of ozone data in ug/m3 than ppb (although obs are done in ppb, they are reported in ug/m3 and many sites do not report the conversion factor). Should have a default conversion factor (2) for ug/m3-ppb for sites that do not report conversion factor (except for high mountain sites probably)

**Comment by jgliss** [comment]
This is a good point, I forgot about that, some pre-thoughts on that:

1. For individual NASA Ames files: need to check whether it can happen that one file contains both mass conc (unit ug m-3) and vmr (nmole mole-1), in different columns?
2. If 1 is True, then in such cases `ReadEbas` needs to pick the right column dependent on what AeroCom variable name the user specified (i.e., `conco3` vs `vmro3`), based on the corresponding units in column matches.
3. In cases where a NASA Ames file contains only one column match, e.g. `conco3` (ug m-3), but the user wants `vmro3` (nmole mole-1), automatic conversion should be attempted, in which case the following should be checked:  
   a. If the column meta data in the NASA Ames file specifies a conversion factor, use that.
   b. If not, check if temperature and pressure is accessible in metadata and compute conversion factor from that (using [concx_to_vmrx](https://github.com/metno/pyaerocom/blob/4945b1aebf51f637f824149744329a33b4ff9968/pyaerocom/mathutils.py#L767).
   c. If temp and / or pressure are not available, use station altitude and standard atmosphere to compute conversion factor.
   d. If a, b and c fail, we could use a constant conversion factor of 0.5.

If any of 3a - 3d is done, information should be added in the associated metadata block of the `UngriddedData`, about how the conversion was done and which assumptions were made.
