### ISSUE TITLE
Check source ts_type and naming convention of ColocatedData

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#39]
Currently, the source ts_type of the model is included in the file naming convention of the colocated data object, as well as the actual ts_type of the colocated data. E.g.:

scatc550dryaer_REF-EBAS-Lev3_MOD-GFDL-AM4-met2010-monthly_20100101_20101231_monthly_WORLD-noMOUNTAINS.nc

I think this is not needed and makes it confusing to understand the file naming. Only the actual ts_type should be in the file name and source ts_type for both model and obs remains accessible in the metadata of the colocated NetCDF file.

Keep in mind commit 8fc9c3e24397303bdcd43515ab4d8e6bf1e71617

**Comment by jgriesfeller** [comment]
@jgliss looks too old to be still relevant. Closing for now. Please reopen if still relevant
