### ISSUE TITLE
AeroVal maps feature for raster data

### ISSUE THREAD

**Issue by AugustinMortier** [metno/pyaerocom#401]
The geojson files can get very large for long time series (eg: >50MB for monthly data over 3 years in C3S project).

One year of data with monthly resolution (12 layers) has been shown to be fast enough both in loading the data and in plotting the maps. For multi-year projects and monthly resolutions, we could sinply split up the time period into individual years and provide a geojson file per year. 

We could also investigate web map tiles services (https://www.ogc.org/standards/wmts), but this is a major change.

**Comment by jgriesfeller** [comment]
Because we likely need the maps in higher / native resolution, GeoJSON is not the right format for maps.

WMS (https://en.wikipedia.org/wiki/Web_Map_Service), the noted wmts or also GeoTIFF (https://en.wikipedia.org/wiki/GeoTIFF) comes to mind here. There's also a lot of expertise about how to use e.g. WMS in the institute already and e.g. uEMEP does high resolution maps already in a web service

**Comment by AugustinMortier** [comment]
I already use WMS in the aerosol alerts service to display MODIS data behind the alerts polygons, so it should not be that difficult to implement it on the web side.  
![Screenshot from 2021-09-09 09-32-36](https://user-images.githubusercontent.com/19610522/132642746-dc288a6a-b577-470a-8f5c-4984d3bc44be.png)

 However, I think it is also nice to have very quick changes happening when we explore the time dimension, with is currently possible with the polygons, but not so much with the tiles. So it's another compromise.. As we already have the maps feature working with the polygons, I would prefer to keep this for the first version. In a second time, if we are really limited by the model resolution, then we could switch to one of the other solutions.
![Screenshot from 2021-09-09 09-42-12](https://user-images.githubusercontent.com/19610522/132644105-d991ac9e-eda5-4538-a288-8e46eeb3c765.png)

**Comment by lewisblake** [comment]
This is still relevant to projects such as SESAM.

**Comment by lewisblake** [comment]
Placing this on the release for June. We can discuss if this is a realistic timeline, but it is certainly needed to meet SESAM deadlines approaching this summer.

**Comment by lewisblake** [comment]
We had some success displaying png files of model and satellite data on Aeroval. I believe the web is now set up to display such images. Will need to talk with @AugustinMortier about the details it expects for formatting, naming, etc., but in principle we can implement plotting and saving of pngs files into pyaerocom for model and satellite data.
