### ISSUE TITLE
Country regions broken in new web processing

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#402]
Something is wrong with the country regions functionality in the new web processing engine. The aeroval website won't display the bar chart for regions when regions_how='country'. I will investigate.

**Comment by hansbrenna** [comment]
I'm not sure if this is a problem in the web processing output or in the web server code. When I only process one variable it displays correctly. It seems to me like it only wants to display the countries if there are no null/nan values in the .json files. When I try to display country heatmaps it only displays the ones with no null cells. @AugustinMortier 

I will try to process two different obs data sets and  see if that works.

**Comment by hansbrenna** [comment]
Doesn't work when having two different data sets either.

**Comment by hansbrenna** [comment]
It works for defauls and htap regions though. even when some of the regions have null values.

**Comment by hansbrenna** [comment]
This script backfills the heatmap files:

```Python
import glob
import pyaerocom as pya

"""
As a quick fix I will put this program in the data repository and then think 
pyaerocom integration later.
"""

# at the end of processing all coldata:


dummy_stats=pya.aeroval.coldatatojson_engine._init_stats_dummy()
    


regions = pya.aeroval.coldatatojson_engine.read_json('regions.json')

hm_files = glob.glob('hm/glob_stats*.json')
for file in hm_files:
    hm = pya.aeroval.coldatatojson_engine.read_json(file)
    
    for k1,v1 in hm.items():
        for k2,v2 in v1.items():
            for k3,v3, in v2.items():
                for k4,v4 in v3.items():
                    for k5,v5 in v4.items():
                        region_subkeys = list(v5['WORLD'].keys())
                        for region in regions.keys():
                            try:
                                v5[region]
                            except KeyError:
                                v5[region] = {}
                                for subkey in region_subkeys:
                                    v5[region][subkey] = dummy_stats
                                    
    pya.aeroval.coldatatojson_engine.write_json(hm, file,ignore_nan=True)
```

I will integrate it into the pyaerocom workflow.

**Comment by jgliss** [comment]
Is this still an issue? @AugustinMortier @hansbrenna ?
