### ISSUE TITLE
Move tests out of source directories 

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#420]
@avaldebe suggested to move the test suite out of the application code, which I think would be a good idea to have them centralised in a separate folder structure from the toplevel directory. So this issue is just to document this planned change.

**Comment by jgliss** [comment]
Probably good to do that already for the upcoming release 0.12.0, but maybe good to wait with it until the source and all tests for that are ready, and then do the move in one go.

**Comment by avaldebe** [comment]
shall I create separate PR for this, or I can add it to #410?

**Comment by jgliss** [comment]
I think we could do a separate PR on this

**Comment by avaldebe** [comment]
@jgliss #421 is ready to be merged
