### ISSUE TITLE
Change main branch from master to main-dev?

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#450]
@avaldebe brought in the idea to use main-dev as the main branch of pyaerocom, and keep master as the branch that always contains the latest release. I think that is a good idea, as this would also wipe out fixed issues more timely, since they are closed automatically if they have been tagged as fixed (e.g. via PR or via commit message `fixes #334`) in the main branch.

**Comment by jgriesfeller** [comment]
I support this idea.

**Comment by jgliss** [comment]
I will do that then!

**Comment by jgliss** [comment]
Done!
