### ISSUE TITLE
Get aggregation and species from filename

### ISSUE THREAD

**Issue by dulte** [metno/pyaerocom#492]
We might want to use aggregated species that exist in variables.ini, but not in some observations. If these species have the method of aggregation in there names, we can use this to aggregate the species. 

The prime example is O3, where EMEP has vmro3 and vmro3max. EEA and EBAS does not have that, but from the name we know that we want to take the max of vmro3. This will also enable us to have separate menu entries for O3 and O3max. 

We can also use, e.g., vmro3min. In this case, if vmro3min exist in variables.ini, the min will be taken of vmro3 for both the obs and mod.

varnameinfo.py can be used to find patterns in the var name

**Comment by jgriesfeller** [comment]
JFYI, vmro3min is scientifically not interesting. And as far as I know, the only species where we care about the max is vmro3

**Comment by lewisblake** [comment]
@dulte Closing this because we have O3 max implemented
