### ISSUE TITLE
Something wrong with EEA and set_flags_nan

### ISSUE THREAD

**Issue by dulte** [metno/pyaerocom#523]
When running EMEP against EEA I get

```
    raise MetaDataError('Cannot apply filter "set_flags_nan" to '
pyaerocom.exceptions.MetaDataError: Cannot apply filter "set_flags_nan" to UngriddedData object, since it does not contain flag information

```

**Comment by dulte** [comment]
When we tested the EEA reader before Jonas left I got it to work. I then worked on that version until I updated to 0.12, and now I get this error

**Comment by dulte** [comment]
@jgriesfeller, I think I need your help with this

**Comment by jgriesfeller** [comment]
I sort of knew that this will come up again...
Can you provide some code for reproducing the error please. Out of the dark it's hard to do some development...

**Comment by dulte** [comment]
Sure. I have to run the collocation once more to check if my script reproduces the error. I will send it to you when it is done (most likely after lunch)

**Comment by dulte** [comment]
[This config](https://gitlab.met.no/aeroval/config/-/blob/master/config_files/cfg_eea-test.py) is a shaved down version of the script I used to get the error. All the non relevant observations are removed

**Comment by jgriesfeller** [comment]
Line 18 in the config file needs to be removed (Sorry Met internal only)

```
BASE_FILTER = {
    'set_flags_nan' : True,
    'latitude':[30,82],'longitude':[-30,90],
    'station_id':['NO0042*'], 
    'negate':'station_id'
    }
```
 `'set_flags_nan' : True,` needs to be removed. That's the unsupported feature in the EEA reader.
 At some point we should unify the way NaNs are set in the obs reading. There's too many possibilities right now.
