### ISSUE TITLE
CAMS2_83 plots / long-term plans

### ISSUE THREAD

**Issue by michaelgau** [metno/pyaerocom#525]
This is the kind of plots we are supposed to show operationally from 2023. The aim is to have a prototype running already next year. The example shows the correlation of model forecasts with observations, for ozone, as a function of forecast hour. One figure shows only CHIMERE and the Ensemble, while the other one shows ALL the models and the Ensemble. These plots have so far been created by Meteo France with an OpenSource software called evaltools, see https://opensource.umr-cnrm.fr/projects/evaltools
One can use, modify and/or redistribute the software under the terms of the CeCILL-C license as circulated by CEA, CNRS and INRIA at http://www.cecill.info/index.en.html
Not sure if we can learn anything from that software of if we should continue developing our own software (pyaerocom) independently.

Krister is in the process of downloading 3 months of model data (the same period as the attached plots are for), so we can start testing. But there's no rush just yet.

To be further discussed at the various kick-off meetings during the next few months. I also attach Meteo France's documentation about statistics (see link under the plots).

<img width="400" alt="CHIforecast_o3_corr" src="https://user-images.githubusercontent.com/22744451/142203696-a3022f2a-2b2c-4bdd-a30b-da7b51054958.png">

<img width="400" alt="All_o3_corr" src="https://user-images.githubusercontent.com/22744451/142204229-35b037f4-f6f6-4fed-b50c-5eb3d7779d5c.png">

[USER_GUIDE_VERIFICATION_STATISTICS.pdf](https://github.com/metno/pyaerocom/files/7554737/USER_GUIDE_VERIFICATION_STATISTICS.pdf)

**Comment by jgriesfeller** [comment]
Some thoughts about that:
- Since I happen to know that this analysis should be on a web page: That part will separate from aeroval. I think it's too different.
- The analysis shown above can be done with the current pyaerocom using the API:

1. create one model per forecast day 
2. colocate all models with observations "the right way" (details about that in the meeting)
3. store that colocated data for later usage
4. calculate the above hourly statistics

Trying to put the entire analysis into pyaerocom is a too huge effort in my opinion.

**Comment by michaelgau** [comment]
...what I didn't get time for at the meeting is to explain why the Meteo France plots don't have discontinuities at each 00UTC. It's because, as you can read in their documentation, they evaluate the full 96 hours of the forecasts for each model. In other words, they take the 4-day forecast issued on 1 June, and evaluate that single forecast all they way through 4th of June, against measurements for the entire 1st - 4th June period. If one does that for all the 92 forecasts during JJA2021, and than plots the average (or median) for each hour, there won't be a discontinuity at 00UTC. "My" method, combining *different* forecasts of the same calendar day, will in general show discontinuities at each 00UTC, which however become less visible the longer the average time gets.

**Comment by michaelgau** [comment]
just had a discussion with Krister, and we concluded for now that we do it in the "Meteo France way", i.e. use all 4-day forecasts created during the JJA2021 period (no more and no less) and evaluate all model results created during that period (although the last few records will spill over into the SON2021 period). "My" method, which I presented yesterday, was to use model results that strictly cover the JJA2021 period only (i.e. including a few forecasts created end of May). Both methods are justifyable, but we'll go for Meteo France because it's less confusing and probably easier to implement.

**Comment by michaelgau** [comment]
Dear All, we should have the first prototype service on AeroVal running by April. How exactly that 'prototype service' should look like was formulated vaguely in the proposal (on purpose, because I couldn't know last summer how much we could possibly achieve by April 2022).
ECMWF wanted to come up with some suggestions at the kick-off meeting but that one won't occur before 14 January.

**Comment by michaelgau** [comment]
ok, let's close this one next Thursday.
We still try to re-run some of the evaluation by then (with parallel code) so that the user can select year and season

**Comment by michaelgau** [comment]
and yes, I'll create a new git issue, with remaining tasks until December (including the evaluation of the analysis, stronger filtering of stations for FAIRMODE plots, extract-quarterly-plots-for-ECQ-reports functionality, .. and defining routines, e.g. how often we re-run seasons and long_slims, if at all)

**Comment by michaelgau** [comment]
Milestone notification report was submitted yesterday. Closing this issue now. Will define new issue with tasks until operational status of CAMS2_83-AeroVal
