### ISSUE TITLE
Earlinet and CAMS extinction profile comparison

### ISSUE THREAD

**Issue by MichaelSchulzMETNO** [metno/pyaerocom#539]
I believe the Earlinet data reading is working in pyaerocom. For CAMS2-82 it would be needed to connect this to the vertical pofiles of aerosol extinction coming from the IFS model. Required are:
- check that the Earlinet read is still working (based on EARLINET netcdf files)
- update the EARLINET database on lustre (include NRT stream from ACTRIS at one point)
- decide on model output to be used (CAMS 3d fields versus profile extracts from KNMI)
- check colocate profiles
- split pofiles in layers (surface, boundary, lower troposphere, upper troposphere) and treat each layer as a 2D variable (such as AOD) 
- introduce into aeroval

**Comment by lewisblake** [comment]
Example of new EARLINET format located at /lustre/storeB/users/lewisb/projects/CAMS2_82/Data/testing_stuff/EARLINET
