### ISSUE TITLE
Observation catalogue / overview

### ISSUE THREAD

**Issue by MichaelSchulzMETNO** [metno/pyaerocom#551]
For users, production, but also for development: It would be useful to have a way to get an overview on observational data sets which can be read by pyaerocom. 

Which obs data sets are accessible via aerocom from lustre/metno?
Which obs data sets are accessible publicly?

What are the characteristics of the obs dataset that can be accessed via pyaerocom? (variables, temporal coverage&resolution, pyaerocom name,id,location of dataset, origin, data policy, additional documentation (papers, websites), version management on lustre, which pyaerocom reader is attached )

How can these characteristics be retrieved? How can this be stored best in pyaercom in the future? 

Can help on getting such an overview be included in the documentation?

**Comment by avaldebe** [comment]
see #572

**Comment by avaldebe** [comment]
We could start with enhancing the documentation of the reader, so the description is more than a list of acronyms.

**Comment by MichaelSchulzMETNO** [comment]
And have a list of readers on the documentation page, (if not already somewhere ?)
