### ISSUE TITLE
logging miss configuration

### ISSUE THREAD

**Issue by dulte** [metno/pyaerocom#574]
Logging.info no longer show when running aeroval. This is due to a new change to make all the loggers to one main logger.

This has removed a lot of the printing to console. 

We need to agree on if we should have this printing to console or not, and how to turn it on/off

**Comment by avaldebe** [comment]
the default configuration for `pyaerocom` and all its child loggers is to write the messages into the console, so this is likely a miss configuration of the logging module

**Comment by avaldebe** [comment]
Found the error, the `pyaerocom` did not have an explicit level set (only the console handler had a level) so the default level was used (30 or "WARNING"). Therefore info messages were discarded instead of been given to the handler.
I will test a bit more and open an PR wit a patch.
