### ISSUE TITLE
global models: processing of models providing only positive coordinates is wrong

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#588]
@avaldebe discovered that CI using iris 3.2 shows this error:
```
data_tm5 = pyaerocom.GriddedData: (od550aer, TM5_AP3-CTRL2016)
<iris 'Cube' of atmosphere_optical_thickness_due_to_ambient_aerosol / (1) (time: 12; latitude: 90; longitude: 120)>

    @data_unavail
    def test_GriddedData_longitude(data_tm5):
        """Test if longitudes are defined right"""
        assert str(data_tm5.longitude.units) == "degrees"
    
        lons = data_tm5.longitude.points
>       assert_allclose(lons.min(), -181.5, rtol=TEST_RTOL)
E       AssertionError: 
E       Not equal to tolerance rtol=0.0001, atol=0
E       
E       Mismatched elements: 1 / 1 (100%)
E       Max absolute difference: 3.
E       Max relative difference: 0.01652893
E        x: array(-178.5)
E        y: array(-181.5)

tests/test_griddeddata.py:101: AssertionError
```

looking at 
https://github.com/metno/pyaerocom/blob/27a7dac9d8eb3a695a8a71393b6b33a798063c67/tests/test_griddeddata.py#L100-L102
tells that the longitudes are just wrong. 
original dato from the file shows that this is a model that initially provided the longitudes from 0 to 360 degrees:

```
(base) jang@pc4847:~$ ncdump -v lon /home/jang/MyPyaerocom/testdata-minimal/modeldata/TM5-met2010_CTRL-TEST/renamed/aerocom3_TM5_AP3-CTRL2016_od550aer_Column_2010_monthly.nc

 lon = 1.5, 4.5, 7.5, 10.5, 13.5, 16.5, 19.5, 22.5, 25.5, 28.5, 31.5, 34.5, 
    37.5, 40.5, 43.5, 46.5, 49.5, 52.5, 55.5, 58.5, 61.5, 64.5, 67.5, 70.5, 
    73.5, 76.5, 79.5, 82.5, 85.5, 88.5, 91.5, 94.5, 97.5, 100.5, 103.5, 
    106.5, 109.5, 112.5, 115.5, 118.5, 121.5, 124.5, 127.5, 130.5, 133.5, 
    136.5, 139.5, 142.5, 145.5, 148.5, 151.5, 154.5, 157.5, 160.5, 163.5, 
    166.5, 169.5, 172.5, 175.5, 178.5, 181.5, 184.5, 187.5, 190.5, 193.5, 
    196.5, 199.5, 202.5, 205.5, 208.5, 211.5, 214.5, 217.5, 220.5, 223.5, 
    226.5, 229.5, 232.5, 235.5, 238.5, 241.5, 244.5, 247.5, 250.5, 253.5, 
    256.5, 259.5, 262.5, 265.5, 268.5, 271.5, 274.5, 277.5, 280.5, 283.5, 
    286.5, 289.5, 292.5, 295.5, 298.5, 301.5, 304.5, 307.5, 310.5, 313.5, 
    316.5, 319.5, 322.5, 325.5, 328.5, 331.5, 334.5, 337.5, 340.5, 343.5, 
    346.5, 349.5, 352.5, 355.5, 358.5 ;
```

using iris up to 3.1 [iris.cube.Cube.intersection](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris/cube.html?highlight=intersection#iris.cube.Cube.intersection) gives this as a result:
```
>>> new_cube = cubes[0].intersection(longitude=(-180, 180))
>>> new_cube.coord('longitude')
DimCoord(array([-181.5, -178.5, -175.5, -172.5, -169.5, -166.5, -163.5, -160.5,
```
from iris 3.2 this is the result **(the correct one!)**:
```
>>> new_cube = cubes[0].intersection(longitude=(-180, 180))
>>> new_cube.coord('longitude')
<DimCoord: longitude / (degrees)  [-178.5, -175.5, ..., 175.5, 178.5]+bounds  shape(120,)>
```

since these longitudes are used for the colocation, **current results from models not providing negative longitudes are likely wrong** (one longitude index off; additional problems at the upper end).

**Comment by jgriesfeller** [comment]
although the odd numbers appear in the test mentioned above, there's no code to correct them that I could find
e.g. here:
https://github.com/metno/pyaerocom/blob/27a7dac9d8eb3a695a8a71393b6b33a798063c67/pyaerocom/io/iris_io.py#L186-L212

or here:
https://github.com/metno/pyaerocom/blob/27a7dac9d8eb3a695a8a71393b6b33a798063c67/pyaerocom/griddeddata.py#L2350-L2375

**Comment by jgriesfeller** [comment]
The solution to the problem is to upgrade to iris 3.2.x (which does things right) but that is impossible right now because an incompatibility between our proj6 usage and the need of iris 3.2 for cartopy >= 0.20 which by itself depends on proj8.
So we need to either use proj8 in pyaerocom or use it indirectly via [pyproj](https://pyproj4.github.io/pyproj/stable/)

Both needs some work that I can't tell right now how long it will take. Investigating...

**Comment by jgriesfeller** [comment]
IFS is one of the models that provide the data from 0 to 360 degrees and is affected by the error

**Comment by andagit** [comment]
No, seems that IFS download on default domain (G) do not wrap around.....
(from ECMWF/confluence:)
"G | specifies  the global area  90/0/-90/360 (default)
If the longitude values overlap, the most eastern line of points will not be returned, e.g.
AREA=90/-180/-90/180, GRID=0.5/0.5
-will return a field with the boundaries 90/-180/-90/179.5. 
Areas can be defined to wrap around the globe"

**Comment by jgriesfeller** [comment]
So that basically means the longitude values indicate the lower edge and not the middle point, right?

**Comment by avaldebe** [comment]
> So that basically means the longitude values indicate the lower edge and not the middle point, right?

Yes, but in regards of the request specification. We can not infer from this that the coordinates on the netCDF file represent the boundaries. For that we need to examine the production chain.

**Comment by andagit** [comment]
Well, there is more on the confluence...
"
MARS (with MIR) also supports shifted grids, with no point at latitude=0, longitude=0, e.g. 
AREA=89.5/0.5/-89.5/359.5, GRID=1.0/1.0
-provided the differences between N-S and E-W limits are both divisible by the corresponding grid increments without remainder. 
In this example
![shifted_grid](https://user-images.githubusercontent.com/22189399/155302705-761cc4f4-edf2-47cb-94d9-90f1c778c2e4.png)
, the black points represent the original grid with 1 degree spacing. The red points show the user defined area, which has the
 same spacing but shifted by half a degree. MARS will honour the user defined area and return the inner grid shown in green.  In cases where the differences between N-S and E-W limits are not divisible by the corresponding increments without remainder, MARS starts from the user-specified south-west corner and goes up to (but does not exceed) 
the north-east corner.  For example, a request specifying:
AREA=55.5/0.5/45.0/5.0, GRID=1.0/1.0
retrieves AREA=55.0/0.5/45.0/4.5 with the northern and eastern boundaries adjusted so that the area 
returned lies within that specified by the request and includes a point at latitude=0, longitude=0.
"
But this only means that you can shift the grid by 0.5 degree (1x1) and I do not understand everything here: "with no point at latitude=0, longitude=0" ? Is this clear?

**Comment by jgriesfeller** [comment]
So who defined the 1.125 degree resolution of the CAMS downloads then? 
I guess that what @MichaelSchulzMETNO is interested the most is to get the colocation between the data downloaded e.g. for CAMS83 and the observations right. If I understood you correctly, we would achieve that by adding half a grid-box to the current longitudes. Since the current maximum in the longitudes is `358.875` and not `360` it seems to me that this is not a user defined area.

I do understand that on other areas this adding might not be correct.

Or shall we just ignore this problem entirely?

**Comment by jgriesfeller** [comment]
Ci has just proved that using iris 3.2 changes the results. I have made a PR to make CI work with iris 3.2 as well and now 
https://github.com/metno/pyaerocom/blob/27a7dac9d8eb3a695a8a71393b6b33a798063c67/tests/test_colocation.py#L186-L198 fails:
```
    def test_colocate_gridded_ungridded(
        data_tm5, aeronetsunv3lev2_subset, addargs, ts_type, shape, obsmean, modmean
    ):
    
        coldata = colocate_gridded_ungridded(data_tm5, aeronetsunv3lev2_subset, **addargs)
    
        assert isinstance(coldata, ColocatedData)
        assert coldata.ts_type == ts_type
        assert coldata.shape == shape
    
        means = [np.nanmean(coldata.data.data[0]), np.nanmean(coldata.data.data[1])]
    
>       assert_allclose(means, [obsmean, modmean], rtol=TEST_RTOL)
E       AssertionError: 
E       Not equal to tolerance rtol=0.0001, atol=0
E       
E       Mismatched elements: 1 / 2 (50%)
E       Max absolute difference: 0.00980256
E       Max relative difference: 0.0545496
E        x: array([0.31593 , 0.169897])
E        y: array([0.31593, 0.1797 ])
```

**Comment by jgriesfeller** [comment]
I ran aeroval using iris version 3.2.0.post0. The results differ from the ones before:

Old:
![Screenshot from 2022-03-02 11-07-13](https://user-images.githubusercontent.com/10772065/156340922-e7f0eded-c1e1-4020-bafc-679fb4d8a515.png)
iris 3.2:
![Screenshot from 2022-03-02 11-07-40](https://user-images.githubusercontent.com/10772065/156340982-a13648e1-4ced-4f10-a7e4-bf60ad4f8de2.png)

Unfortunately also the underlying data has changed, I will run another experiment where that is not the case (SON 2021)
