### ISSUE TITLE
Where to put masks for region filtering

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#59]
I still think it is better to keep additional resources for pyaerocom (e.g. HTAP masks) in a separate repository, especially if these are binary files.

For that purpose I created [pyaerocom-suppl](https://github.com/metno/pyaerocom-suppl) which should contain supplementary data such as masks.

In pyaerocom itself, the access to these masks will be provided automatically whenever they are needed, that is, on first access they will be downloaded automatically from [pyaerocom-suppl](https://github.com/metno/pyaerocom-suppl) to local *MyPyaerocom* directory (is created automatically and is also the place where other things are stored, such as cached `UngriddedData` objects). On second ++ access, the masks locally stored masks can be used.

I think this is better, and keeps the distributed pyaerocom source code smaller, without loosing any functionality or introducing user inconvenience (only if first access to the masks would be in a case where the user does not have a internet connection). 
That way, it will also not impact the size of the pyaerocom repository if in the future, e.g. the masks are changed / updated, etc. (only the download URL needs to be modified then in pyaerocom).

**Comment by jgliss** [comment]
@hannasv @MichaelSchulzMETNO @jgriesfeller 

Please object if you disagree! :)

**Comment by MichaelSchulzMETNO** [comment]
Thats  fine with me. 
It does not solve the problem where eg benchmark data are sitting. If we want to access eg a standard climatology of AOD and if the data provider agrees, can we store such data in this repository? Isnt it too small? Maybe I am too pessimistic here, and a climatology would not need much space anyway.

**Comment by hannasv** [comment]
Should we close this? @jgliss

**Comment by jgliss** [comment]
Yes @hannasv :)
