### ISSUE TITLE
NEGI-ANDOYA COURSE - MISSING FEATURES (NICE TO HAVE)

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#6]
Please insert features (by commenting this issue) that you are missing in pyaerocom or that you think would be nice to have. 

**Note**

**This issue is not for reporting bugs. If you find bugs in the current version, please open a new issue.**

**Comment by jgliss** [comment]
Changes title of issue

**Comment by betsy-noaa** [comment]
would be nice to be able to select data based on instrument_name and/or
instrument_manufacturer (as opposed to instrument_type such as filter_absorption_photometer)

**Comment by krisgarv** [comment]
When converting  .to_dataframe the column name loose relevant information when only given the column name. As when the columns contain the same information, but for different size bins.

**Comment by jgliss** [comment]
Method `to_xarray()` for `GriddedData` object-
