### ISSUE TITLE
update testdata creation scripts to current coding style and make sure they still work

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#604]
I just added some testdata creation scripts I found in a gitlab repo hwn I needed to update the EBAS testing data. 
I think these should be maintained with the code but probabl;y not include in the source distribution.
In any case they use outdated code and except for the EBAS script might not even work anymore.

Someone should look over them and make sure they work and use a decent code style.

**Comment by avaldebe** [comment]
I'll create a PR that moves `./pyaerocom/scripts/testdata-minimal/` to `./scripts` or `./tests/scripts` and imports `TESTDATA_ROOT` from `tests.fixtures.data_access`.
