### ISSUE TITLE
EBAS reading: add tests for correct values for the most used EBAS variables

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#605]
The current EBAS reading tests do not test actual variable values. 
I think we should also make sure that the read values of the most used variables make sense.
Variables:
- concso4
- concso2
- concpm10
- concpm25
- conco3
- concoa
- concss
- concoc

**Comment by lewisblake** [comment]
Some guidance for criteria for "makes sense" would be appreciated here. In my initial testing, I've found concpm10 concentrations with negative values (all -0.1), but can't seem to find an obvious way to determine if these are fill values or suspect data.

**Comment by lewisblake** [comment]
It is also worth noting that the ReasEbas filter itself does not check for negative values in the data.

**Comment by avaldebe** [comment]
@jgriesfeller 

> It is also worth noting that the ReasEbas filter itself does not check for negative values in the data.

Do you k now if this is a bug or a feature?

**Comment by lewisblake** [comment]
I think it's a feature. It's listed:  

TODO
    ----
    - Check for negative values vs. detection limit
    - ...
 
I looked to see if this was just outdated and had been implemented but this TODO not removed, but I did not see anything which appears like it has been implemented. I think we should implement removing of negative values before testing for it :)

**Comment by lewisblake** [comment]
I do not see an issue, so I will open one and address it.
