### ISSUE TITLE
Error with computation of concso4 from OsloCTM3...HIST

### ISSUE THREAD

**Issue by AugustinMortier** [metno/pyaerocom#61]
Only zero values are returned when trying to read/compute concso4 from OsloCTM3...HIST model 

```
mod = 'OsloCTM3v1.01-met2010_AP3-HIST'
r = pya.io.ReadGridded(mod)
data = r.read_var('concso4', start=2010)
data.quickplot_map()

```

**ValueError: Minimum value in data equals maximum value: 0.0**

**Comment by jgliss** [comment]
@AugustinMortier have you checked the source files from the model (rho, mmrso4)?

**Comment by jgliss** [comment]
Hi again @AugustinMortier, I checked quickly and I guess your are suppressing output, right? Else, you would see:

```
Did not find concso4 field but sconcso4. Using the latter instead
``` 

I further checked the data directory of the OsloCTM submission: they did not provide fields for `rho`, so computation of `concso4` from `mmrso4` will not work in this case. What the reading routine did in your case is, that it read the provided `sconcso4` field instead. 

Looking into this one (e.g. with Python or ncview), you will find that there is only 0's in the provided data. So it's not a bug in pyaerocom but a problem in the provided data. 

Can you contact Gunnar about this?

**Comment by avaldebe** [comment]
@AugustinMortier 

Is this issue still relevant?  Can we close it?
