### ISSUE TITLE
Temp files in EEA NRT data

### ISSUE THREAD

**Issue by dulte** [metno/pyaerocom#611]
There are some tmp files in the eea nrt data with a #. Some seem to be created by emacs. These need to be removed or filtered out

**Comment by dulte** [comment]
One possible solution is to change the pattern to something like "**/[A-Z][A-Z]_7_*_timeseries.csv*". This assumes that every file starts with a two letter country code

**Comment by avaldebe** [comment]
@MichaelSchulzMETNO and @jgriesfeller what is our backup strategy?

**Comment by MichaelSchulzMETNO** [comment]
The strategy has been to rsync regularly between lustre A and B. However, with the change in general lustre storage strategy, this has to be rethought. @jgriesfeller could you please make a suggestion how to hav at least one copy of data which can not easily be redownloaded or are needed in the operational chains?
