### ISSUE TITLE
cartopy version in pyaerocom_env.yml is not up  to date

### ISSUE THREAD

**Issue by dulte** [metno/pyaerocom#615]
cartopy version in pyaerocom_env.yml does not have the "!=0.20.*" that the setup.cfg has, meaning that conda environments don't work

**Comment by avaldebe** [comment]
That is because, on conda you should be able to install cartopy-0.20.*, as stated on #583

> None of these options are reasonable for CI, not to users installing from pip (conda users are not affected).
