### ISSUE TITLE
RMS as statistics

### ISSUE THREAD

**Issue by MichaelSchulzMETNO** [metno/pyaerocom#63]
@jgliss @AugustinMortier I wonder why the RMS is not any longer appearing on the model evaluation webpage, heat maps for statistics. I think it should...

**Comment by jgliss** [comment]
I am not sure, why and when we removed RMSE from the interface @AugustinMortier can you put it back in (it should be available in the json files)?

**Comment by AugustinMortier** [comment]
It is now back live. I think that we removed it since it's not a normalized statistic, which means we can have (and we do have) different ranges of values for the different parameters.

**Comment by MichaelSchulzMETNO** [comment]
we can also normalize it by the mean of the observations !!

**Comment by jgliss** [comment]
Thanks!! Normalising makes sense here. But I think, then we should call it NRMSE:

https://en.wikipedia.org/wiki/Root-mean-square_deviation#Normalized_root-mean-square_deviation

**Comment by AugustinMortier** [comment]
RMSE has been updated with a normalization against observations and is now
called NRMSE.

**Comment by jgliss** [comment]
Thanks!

**Comment by MichaelSchulzMETNO** [comment]
Actually - the color scale on the website should only use one color, there is only more and more large values. eg white to red. Also  - the numbers can be truncated at the dot....100 % instead of 100.00 %

**Comment by AugustinMortier** [comment]
This has just been fixed and put live.

**Comment by MichaelSchulzMETNO** [comment]
veldig fint :)
