### ISSUE TITLE
Definition of NMB wrong

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#64]
@AugustinMortier Hi Augustin, the definition of NMB in the [evaluation interface](https://aerocom-evaluation.met.no/infos.php?project=aerocom) is wrong. Currently it is 

NMB=1/N x sum(Mi-Oi))

Instead, it should be:

NMB = sum(Mi - Oi) / sum(Oi) 

Can you fix that?

Note also, that we also filter out negative values in Oi before computing the bias  (as NMB only has a meaning for expectation values exceeding 0).

Cheers,
Jonas

**Comment by AugustinMortier** [comment]
The definition has been fixed

**Comment by jgliss** [comment]
Thanks!
