### ISSUE TITLE
Negative O3 values EEA_AQeRep.v2

### ISSUE THREAD

**Issue by WillemVanCaspel** [metno/pyaerocom#640]
Reading O3 data for the years 2015 and 2016 from EEA_AQeRep.v2 data produces negative ozone values (both mean and daily max). This is not the case for the years 2017 to 2020.

The only difference I can find between 2015-2016 and the other years is that the rows in the .cvs files from the former aren't sorted by date.

**Comment by jgriesfeller** [comment]
Can you please add a file name to this issue? It's faster to test then due to the single file reading.

**Comment by WillemVanCaspel** [comment]
See for example

/lustre/storeA/project/aerocom/aerocom1/AEROCOM_OBSDATA/EEA_AQeRep.v2/renamed/NL

**Comment by jgriesfeller** [comment]
That is just a folder... Or does it apply to all year 2015 files in there?
Sorry, but please make these issues as precise as possible. The easier they can be tested, the faster they are addressed.

**Comment by WillemVanCaspel** [comment]
Ah, silly me. 

Here's the full path:

/lustre/storeA/project/aerocom/aerocom1/AEROCOM_OBSDATA/EEA_AQeRep.v2/renamed/NL/NL_7_28545_2015_timeseries.csv

**Comment by lewisblake** [comment]
Note: Check if data are ordered correctly in time

**Comment by jgriesfeller** [comment]
The data is not always ordered in time. Correcting that at the lowest possible level for speed.
