### ISSUE TITLE
Set daily averages to the middle of the day

### ISSUE THREAD

**Issue by AugustinMortier** [metno/pyaerocom#642]
The daily averages should be set to the middle of the day, as we do for the monthly and yearly averages (middle of the month/year). It is now set to the beginning of the day.

![Screenshot from 2022-05-09 09-36-09](https://user-images.githubusercontent.com/19610522/167362333-15ef24d9-d28b-42f6-bb99-5b1121b8dd9e.png)

**Comment by jgriesfeller** [comment]
To avoid reprocessing of old experiments one might just want to add an offset to the existing times in the json files. Remember that code and data changes over time, so we might not be able to reproduce exactly old results.
Not really complicated...
