### ISSUE TITLE
aeroval processing is missing parallelisation

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#663]
The outcome of this issue shall be (as a start) Python scripts 
1. can take in an aeroval configuration file and put out a bunch of config files with one model and one obs network only
2. support scripts to submit these to any PPI queue
3. combine all runs into one experiment again

**Comment by dulte** [comment]
You can find config files for daily and seasonal runs here: /lustre/storeB/project/fou/kl/emep/People/danielh/projects/pyaerocom/div/cams2_82_configs

You have to run it on the branch fix-missing-dates-cams2-83 as of now.

**Comment by jgriesfeller** [comment]
We need to discuss some caching strategy...
**Problem**: 
Lustre has only file locking on the machine level (so two separate machines can in principle write to the same file at the same time). Not good when two parallelized jobs try to write the same cache file at the same time.

**Proposal**:
I do have a (simple at this point) cache file generator (see also #700 for reference), that could be run via cron every night (in parallel via the cluster). Users that want to use these can then copy them to the right place (`/lustre/storeA/project/aerocom/aerocom2/pyaerocom_out/_cache/${USER}/`) and make sure they get a a cache hit that way.

**Comment by jgriesfeller** [comment]
We need to discuss some caching strategy...
**Problem**: 
Lustre has only file locking on the machine level (so two separate machines can in principle write to the same file at the same time). Not good when two parallelized jobs try to write the same cache file at the same time.

**Proposal**:
I do have a (simple at this point) cache file generator (see also #700 for reference), that could be run via cron every night (in parallel via the cluster). Users that want to use these can then copy them to the right place (`/lustre/storeA/project/aerocom/aerocom2/pyaerocom_out/_cache/${USER}/`) and make sure they get a a cache hit that way.

**Comment by jgriesfeller** [comment]
I moved the development of this to another repo: https://github.com/metno/pyaerocom-parallelization
The package is install-able via PyPI already (`pip install  pyaerocom-parallelization`) but that version might not work entirely since the version there right now was just created to proof the packaging to work.
All Pyaerocom developers are welcome to contribute. Testing is still missing though.
Keeping this issue open until there's a 1st working version

**Comment by jgriesfeller** [comment]
closing this since https://github.com/metno/pyaerocom-parallelization is working
