### ISSUE TITLE
Add pyaeroval CLI example in documentation

### ISSUE THREAD

**Issue by AugustinMortier** [metno/pyaerocom#670]
In the documentation, there are some exmaples of pyaeroval [configuration files](https://pyaerocom.readthedocs.io/en/latest/aeroval-examples.html). Would be great to add the command line to run this experiment.

**Comment by jgriesfeller** [comment]
just put `python` in front and it runs...

**Comment by AugustinMortier** [comment]
Then it should be easy to solve ;)

**Comment by AugustinMortier** [comment]
For info, I'm writing a [page](https://aeroval.met.no/contribute.php) describing how external users could contribute to AeroVal. It would be nice to have clear examples that could be just copy paste.

**Comment by lewisblake** [comment]
I tend to agree with @jgriesfeller on this. I'm not sure this is the most appropriate addition to the CLI bu certainly it would be easy to include something like `python config_example.py` in some documentation. It also demonstrates how all other config files users might make will be executed

**Comment by AugustinMortier** [comment]
I think that it does not cost a lot to mention that a 'configuration could be run as following: ....'
And that the code blocks in this page are actually .py files. It might not be as obvious as you think for external users.

The general pyaerocom tutorials are quite well detailed: anybody with an access to the data can easily read Aeronet data and plot things. When it's about processing AeroVal files, I think the recipe is not that clear yet.
