### ISSUE TITLE
Non-standard grids / projections for model output

### ISSUE THREAD

**Issue by WillemVanCaspel** [metno/pyaerocom#671]
Maybe Pyaerocom could be developed to accept model data on non-standard grids (e.g., polar stereographic projection). Currently using a non-standard grid raises the

"NotImplementedError: Coord latitude is associated with multiple dimensions. This cannot yet be handled..."

error by the check_dimcoords_tseries function in griddeddata.py.

**Comment by jgriesfeller** [comment]
Just as a comment: Iris can actually read more that just a rectangular lat / lon grid. @WillemVanCaspel maybe you want to check if your grid is supported by iris (just try to load the file with iris.load_cube). We could then use iris' grid conversion methods to at least use an interpolated result for the colocation (which is actually done by xarray).
Not sure if iris itself supports colocation already.

**Comment by lewisblake** [comment]
@WillemVanCaspel please link me to a small data set and config so I can recreate the issue. Thank you

**Comment by WillemVanCaspel** [comment]
/lustre/storeB/users/willemvc/modelruns/CLT4_2017/

This folder contains a one-year run on the EECCA domain. The output only includes a small number of variables, two of which are the 2D latitude and longitude arrays!

**Comment by avaldebe** [comment]
We need docs telling the user how to interpolate model data to regular lat-long,
and a custom `Exception` that points the user to the docs.

**Comment by WillemVanCaspel** [comment]
Back from the dead! 

We will again have to consider making Pyaerocom compatible with non-regular grids.

**Comment by lewisblake** [comment]
Briefly describing a possible solution based on a conversation with @dulte @WillemVanCaspel @mmd1998:

Pyaerocom can not handle if the coordinates are 2D arrays, which for non-lonlat grids, they are. The EMEP reader should therefore be expanded to check that if the coordinate arrays are 2D. Then the reader needs metadata regarding the projection the model output is on (available) and then do a conversion based on that projection to standard (lon, lat) coordinates, most likely taking the centroid of the cell as the model output location.

**Comment by lewisblake** [comment]
Meeting note: Iris will likely not crash for nonstandard grids, but the collocation might. Iris may be able to do the collocation. So consider handing the collocation (in this case?) over to iris. 

Also, check if current versions of xarray support vectorized indexing on curvi-linear coordinates

**Comment by dulte** [comment]
Possible pipeline:

1.  The user adds model projection parameters to aeroval config/passed directly to colocator if aeroval is not used
2. That is passed to the colocator
3. Some check of the projection parameters when reading model data 
4. The obs is transformed to model coordinates
5. Colocation on "i" and "j"

**Comment by WillemVanCaspel** [comment]
This issue was posted with the EECCA EMEP grid in mind. This grid is, however, non-standard and not relevant to any of the EMEP simulation results. This issue can therefore be closed as far as I am concerned.
