### ISSUE TITLE
Flag to set to read in the model data before the observations

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#676]
Sometimes in debugging the issue is with the way pyaerocom reads model data. In these cases, for debugging, all the observations must be read in first before reading in the model data, which is very slow.  Maybe it would be nice to have a flag to read in the model data first so reading in the obs could be avoided.

**Comment by jgriesfeller** [comment]
I don't understand the problem really. You should be able to use the API to just read model data. Here's my model reading scratch:

```python
# quick and dirty test for model reading via the api

DATA_ID = 'EMEP.cams61.BASE'
VAR_NAME = 'SO4ugSm3'
TS_TYPE = 'daily'

def main():
    import pyaerocom.io as pio
    
    model_obj = pio.ReadGridded(data_id = DATA_ID)
    model_data = model_obj.read_var(var_name=VAR_NAME, ts_type=TS_TYPE, rename_var=VAR_NAME)
    print(model_data)

if __name__ == "__main__":
    main()

```

Or am I missing something?

**Comment by avaldebe** [comment]
> I don't understand the problem really.

I think this is about how AeroVal reads observations and model data

**Comment by lewisblake** [comment]
Indeed, the problem was intended to be about Aeroval, but Jan's approach can probably take care of this for now.
