### ISSUE TITLE
EEA unit and conversion issues

### ISSUE THREAD

**Issue by WillemVanCaspel** [metno/pyaerocom#678]
Evaluating the EEA data is giving inconsistent results. As an example, there is an evaluation that can be (local) hosted from /lustre/storeB/users/willemvc/Python/aeroval/web and accessed by visiting localhost:8000/intercomp.php?project=CAMS21vsGENEMIS

Selecting EEA-rural SO2 observations for the ModelEvals-2019 experiment shows what looks to be a problem with the units in EEA, with observations being about a factor of 4-5 too large. Similarly, the EEA values for NO2 are much too large. 

Possibly unrelated to unit issues, is that the O3 observations look good, but that O3max is very wrong. O3max shows no seasonal cycle, and values are less than half of what they should be. 

In an earlier EMEP-trend evaluation, the above problems did not exists, see: https://aeroval.met.no/evaluation.php?project=emep&exp_name=2021-reporting&station=WORLD&par=concso2&obs=EEA-rural-O3max#

**Comment by avaldebe** [comment]
Hi @WillemVanCaspel and @dulte 

@WillemVanCaspel 
Can you provide the path to the configuration used for this specific experiment?

@dulte 
Could be this related to #492 and #627

**Comment by WillemVanCaspel** [comment]
Yes, gladly. 

Path to the config for this experiment: 

/home/willemvc/lustre/Python/aeroval/config/documentation/cfg_emep-CAMS21vsGENEMISt-2019.py

**Comment by jgriesfeller** [comment]
```
(pyadev-applied) jang@ppi-clogin-a1:.../logs/aeroval_logs$ less /home/willemvc/lustre/Python/aeroval/config/documentation/cfg_emep-CAMS21vsGENEMISt-2019.py
/home/willemvc/lustre/Python/aeroval/config/documentation/cfg_emep-CAMS21vsGENEMISt-2019.py: Permission denied
```
We can't read that file, no permissions

These configs should be in the aeroval config repo here (create your own branch for testing, put working configs in the main branch)
https://gitlab.met.no/aeroval/config

I just added you to the repo.
Please put all your aeroval configs there so others can have a look

**Comment by avaldebe** [comment]
The bug causing this error might have been addressed by #682.
@WillemVanCaspel please check...

**Comment by avaldebe** [comment]
> The bug causing this error might have been addressed by #682. @WillemVanCaspel please check...

@WillemVanCaspel can you check

**Comment by WillemVanCaspel** [comment]
Finally, I can confirm that this has fixed the EEA bug. Evaluations now look good.

**Comment by jgriesfeller** [comment]
In this case please close the issue
