### ISSUE TITLE
Filtering based on square regions

### ISSUE THREAD

**Issue by hannasv** [metno/pyaerocom#68]
Seen this before? @jgliss 

```python
OSError: Cannot filter <class 'pyaerocom.ungriddeddata.UngriddedData'> obj, need instance of GriddedData or UngriddedData
```

**Comment by jgliss** [comment]
I think so, and I think restarting the kernel helped for me (I did not really find out why this happens sometimes, but may be related to Spyder). I think it is related to how libraries, etc are imported, but if you find out more, please provide info here. I found this thread:

https://stackoverflow.com/questions/57097641/class-instance-fails-isinstance-check

**Comment by hannasv** [comment]
I swapped the order of filtering in the filter class. Now it applies a square filter first and then the mask. Works for now.
