### ISSUE TITLE
logging needs to use a more specific file name

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#687]
The future paralleisation will start several aeroval jobs from the same work directory. The current logging to the file `./pyaerocom.log` ends up in a scambled log file.
Because my qsub scripts log the console output to a specific file like `/lustre/storeA/project/aerocom/logs/aeroval_logs/jang.20220621_101003.cfg_file_IASI.ULB_AeronetSDAV3L2.1657189_log.txt` the general log file in in principle not needed at all (if the console output works). So we might want to get rid of that somehow with an option.

For discussion.

**Comment by avaldebe** [comment]
Maybe the name of the log file could be set up on an environmental variable, like `PYAEROCOM_LOG_FILE`. When the variable is found the logging to file will activate.

**Comment by jgriesfeller** [comment]
@avaldebe I support your proposal and would keep the current behavior as a default.
