### ISSUE TITLE
Testing suite should be machine and user agnostic

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#692]
When trying to run the test suit on PPI, I ran into an issue with permissions. e.g., 

```
PermissionError: [Errno 13] Permission denied: '/lustre/storeA/project/aerocom/aerocom2/pyaerocom_out/testdata-minimal/scripts/create_subset_ebas.py'
```

After chatting with @jgriesfeller and @avaldebe and a ticket to IT to change ownership of the directories needed for testing to @jgriesfeller, we concluded that testing is not multi-user capable.

```
/modules/centos7/user-apps/aerocom/anaconda3/envs/pyadev-applied/lib/python3.9/pathlib.py:1120: in _opener
    return self._accessor.open(self, flags, mode)
E   PermissionError: [Errno 13] Permission denied: '/tmp/test_iris_io/invalid.nc'
```
```
(pyadev-applied) jang@ppi-clogin-a1:~/.../Python3/pyaerocom$ ll /tmp/test_iris_io/invalid.nc
-rw-rw-r-- 1 danielh danielh 0 Jul  4 12:44 /tmp/test_iris_io/invalid.nc
```

In order for tests to be run agnostically, they should not depend on `/tmp`, but rather be specific to the machine and $USER (@jgriesfeller please let me know if I am forgetting anything). The Python module [tempfile](https://docs.python.org/3/library/tempfile.html#) may be starting point for thinking of a solution.

**Comment by avaldebe** [comment]
> ```
> /modules/centos7/user-apps/aerocom/anaconda3/envs/pyadev-applied/lib/python3.9/pathlib.py:1120: in _opener
>     return self._accessor.open(self, flags, mode)
> E   PermissionError: [Errno 13] Permission denied: '/tmp/test_iris_io/invalid.nc'
> ```
> 
> ```
> (pyadev-applied) jang@ppi-clogin-a1:~/.../Python3/pyaerocom$ ll /tmp/test_iris_io/invalid.nc
> -rw-rw-r-- 1 danielh danielh 0 Jul  4 12:44 /tmp/test_iris_io/invalid.nc
> ```

The likes that create this file are

https://github.com/metno/pyaerocom/blob/e9f26665a551be2489a0f05baa8637c5d93e9ffb/tests/io/test_iris_io.py#L66-L68

The quick'n dirty solution would be to create a temporary directory each time with `tempfile.mkdtemp()` as follows

``` diff
- FAKE_FILE = Path(tempfile.gettempdir()) / "test_iris_io/invalid.nc"
+ FAKE_FILE = Path(tempfile.mkdtemp()) / "test_iris_io/invalid.nc"
```

IMO, this file should be created inside a fixture and modify the tests consuming this file to use the fixture.

**Comment by avaldebe** [comment]
I can find only one other usage of `tempfile` on the test suite

https://github.com/metno/pyaerocom/blob/e9f26665a551be2489a0f05baa8637c5d93e9ffb/tests/test_config.py#L18-L25

Fortunately, `tempfile.mkdtemp()` is used here. It creates a new temporary directory each time, so there is no interference between users.

However, like on my last comment I would prefer these temporary files to be provided by fixtures.
