### ISSUE TITLE
We need docs telling the user how to interpolate model data to regular lat-long

### ISSUE THREAD

**Issue by avaldebe** [metno/pyaerocom#699]
We need docs telling the user how to interpolate model data to regular lat-long,
and a custom `Exception` that points the user to the docs.

_Originally posted by @avaldebe in https://github.com/metno/pyaerocom/issues/671#issuecomment-1180167683_

**Comment by lewisblake** [comment]
Maybe we should just point to a library that does this, or simply state that they need to have their model output in regular lon-lat format

**Comment by jgriesfeller** [comment]
The _library_ used in the community is usually the command line tools cdo and nco, or pyproj in Python. 
Doing interpolation on the fly takes a lot of resources and will cause a lot of frustration on the user side.
