### ISSUE TITLE
making AeroVal for CAMS2_83 operational

### ISSUE THREAD

**Issue by michaelgau** [metno/pyaerocom#701]

**Comment by avaldebe** [comment]
## Production environment

- deploy via environment module
- install with pip
- only use conda if pip is not possible

**Comment by charlienegri** [comment]
the environment modules (centos+rhel8) are already in place, not used in ecflow yet but ready to be tested, at the moment they (pip) install the branch `fix-missing-dates-cams2-83`,  
in production we'll have a production branch (e.g. 'cams2_83_production`) and a production version of the module installing that,   
plus a development branch (e. g. `cams2_83_dev`) and a development version of the module checking out that. 
(but btw i think it's safer if I'll maintain also local conda installations for user uemep and my user, in case there are any issues with modules at some point)

**Comment by lewisblake** [comment]
Could this be closed? CAMS2_83 has been operational for six months now

**Comment by michaelgau** [comment]
Yes, can be closed.
