### ISSUE TITLE
Check for negative values in EBAS Reader

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#708]
#605 would like use to include test which ensure that the values read from EBAS make sense. However, filtering of spurious data is not yet implemented in `ReadEbas`. At the very least, `ReadEbas` should not read in values with negative concentrations, VMRS, or any species which a negative value is non-physical.

**Comment by lewisblake** [comment]
This is not such an obvious problem, because negative values are appropriate for some EBAS species (e.g., scattering coefficients). We therefore need to have more species-specific criteria for filtering of observations.

**Comment by dulte** [comment]
Let this be up to the users. Maybe with some documentation(?)
