### ISSUE TITLE
Cleanup and some minor fixes related to new land sea mask filtering

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#71]
@hannasv just to inform you: I checked the new features a bit more in detail today and found some minor bugs and style issues, which I fixed in commit 09e1f9ae6c201f22bce818907a4afcb25830c7c5 and the commits before from today. Please merge these and doublecheck before you continue working in your branch. If everything is okay, please send me a notification and close this issue.

Cheers, 
Jonas

**Comment by hannasv** [comment]
It works on my branch.

If we extend the make_dummy_lat_lon cube to have a time dimension of 1 i think this could be used for testing filtering when lustre is unavailable. Not a hundred percent certain how it would work, but i know it needs the time dimension for this to work. Lets discuss this next week. 

Best,
Hanna
