### ISSUE TITLE
tests fail with xarray 2022.6.0

### ISSUE THREAD

**Issue by avaldebe** [metno/pyaerocom#710]
The following text raise an IndexError exception

```
FAILED tests/aeroval/test_aeroval_HIGHLEV.py::test_ExperimentOutput__FILES[cfgexp1-chk_files0] - IndexError: dimension coordinat...
FAILED tests/aeroval/test_aeroval_HIGHLEV.py::test_ExperimentOutput__FILES[cfgexp2-chk_files1] - IndexError: dimension coordinat...
FAILED tests/aeroval/test_aeroval_HIGHLEV.py::test_ExperimentOutput__FILES[cfgexp4-chk_files2] - IndexError: dimension coordinat...
FAILED tests/aeroval/test_aeroval_HIGHLEV.py::test_reanalyse_existing[cfgexp4] - IndexError: dimension coordinate 'data_source' ...
FAILED tests/aeroval/test_aeroval_HIGHLEV.py::test_superobs_different_resolutions[cfgexp4] - IndexError: dimension coordinate 'd...
FAILED tests/aeroval/test_experiment_output.py::test_ExperimentOutput_delete_experiment_data_CFG1[cfgexp1] - IndexError: dimensi...
FAILED tests/aeroval/test_experiment_output.py::test_Experiment_Output_clean_json_files_CFG1[cfgexp1] - IndexError: dimension co...
FAILED tests/aeroval/test_experiment_output.py::test_Experiment_Output_clean_json_files_CFG1_INVALIDMOD[cfgexp1] - IndexError: d...
FAILED tests/aeroval/test_experiment_output.py::test_Experiment_Output_clean_json_files_CFG1_INVALIDOBS[cfgexp1] - IndexError: d...
FAILED tests/aeroval/test_experiment_processor.py::test_ExperimentProcessor_run[cfgexp1] - IndexError: dimension coordinate 'dat...
FAILED tests/aeroval/test_experiment_processor.py::test_ExperimentProcessor_run[cfgexp2] - IndexError: dimension coordinate 'dat...
FAILED tests/aeroval/test_experiment_processor.py::test_ExperimentProcessor_run[cfgexp3] - IndexError: dimension coordinate 'dat...
FAILED tests/aeroval/test_experiment_processor.py::test_ExperimentProcessor_run[cfgexp4] - IndexError: dimension coordinate 'dat...
```

for example
```
$ test_ExperimentOutput__FILES[cfgexp1-chk_files0]
[...]
E               IndexError: dimension coordinate 'data_source' conflicts between indexed and indexing objects:
E               ['AeronetSunV3L2Subset.daily' 'TM5-met2010_CTRL-TEST']
E               vs.
E               AeronetSunV3L2Subset.daily

.venv/lib/python3.10/site-packages/xarray/core/coordinates.py:464: IndexError
[...]
```

and
```
$ pytest tests/aeroval/test_experiment_processor.py::test_ExperimentProcessor_run[cfgexp1]
[...]
E               IndexError: dimension coordinate 'data_source' conflicts between indexed and indexing objects:
E               ['AeronetSunV3L2Subset.daily' 'TM5-met2010_CTRL-TEST']
E               vs.
E               AeronetSunV3L2Subset.daily

.venv/lib/python3.10/site-packages/xarray/core/coordinates.py:464: IndexError
[...]
```

**Comment by WillemVanCaspel** [comment]
Unfortunately, this change causes EEA evaluations to fail. Executing "arr[0].where(obs_ok, drop=True)" works, but when assigning as "arr[0] = arr[0].where(obs_ok, drop=True)", an error is raised. Reverting the change of #710 gets rid of this problem. If it helps, I would be happy to upload a config file that reproduces the problem, but simply running any EEA evaluation should be enough. 

The error shows up as follows:

Traceback (most recent call last):
File "/lustre/storeB/users/willemvc/Python/aeroval/config/documentation/cfg_emep-CAMS21vsGENEMISt-2019.py", line 488, in
res = ana.run()
File "/home/willemvc/Python/pyaerocom/pyaerocom/pyaerocom/aeroval/experiment_processor.py", line 135, in run
self._run_single_entry(model_name, obs_name, var_list)
File "/home/willemvc/Python/pyaerocom/pyaerocom/pyaerocom/aeroval/experiment_processor.py", line 73, in _run_single_entry
engine.run(files_to_convert)
File "/home/willemvc/Python/pyaerocom/pyaerocom/pyaerocom/aeroval/coldatatojson_engine.py", line 53, in run
self.process_coldata(coldata)
File "/home/willemvc/Python/pyaerocom/pyaerocom/pyaerocom/aeroval/coldatatojson_engine.py", line 192, in process_coldata
hm_all = _process_heatmap_data(
File "/home/willemvc/Python/pyaerocom/pyaerocom/pyaerocom/aeroval/coldatatojson_helpers.py", line 1168, in _process_heatmap_data
stats = _get_extended_stats(subset, use_weights)
File "/home/willemvc/Python/pyaerocom/pyaerocom/pyaerocom/aeroval/coldatatojson_helpers.py", line 1027, in get_extended_stats
(, stats["R_temporal_median"]) = _calc_temporal_corr(coldata)
File "/home/willemvc/Python/pyaerocom/pyaerocom/pyaerocom/aeroval/coldatatojson_helpers.py", line 1082, in _calc_temporal_corr
arr[0] = arr[0].where(obs_ok, drop=True)
File "/home/willemvc/miniconda3/envs/pya/lib/python3.10/site-packages/xarray/core/dataarray.py", line 752, in setitem
assert_coordinate_consistent(value, obj.coords.variables)
File "/home/willemvc/miniconda3/envs/pya/lib/python3.10/site-packages/xarray/core/coordinates.py", line 389, in assert_coordinate_consistent
raise IndexError(
IndexError: dimension coordinate 'station_name' conflicts between indexed and indexing objects:
<xarray.DataArray 'station_name' (station_name: 341)>
array(['AT0ENK1', 'AT0ILL1', 'AT0KLH1', ..., 'SK0406A', 'TR0016A', 'TR0017A'],
dtype=object)
Coordinates:
data_source <U12 'EEAAQeRep.v2'

station_name (station_name) object 'AT0ENK1' 'AT0ILL1' ... 'TR0017A'
latitude (station_name) float64 48.39 47.77 46.77 ... 48.93 36.85 37.19
longitude (station_name) float64 13.67 16.77 15.96 ... 22.27 35.35 35.26
altitude (station_name) float64 525.0 117.0 415.0 ... 431.0 12.0 107.0
country (station_name) <U22 'Austria' 'Austria' ... 'Turkey' 'Turkey'
country_code (station_name) <U2 'AT' 'AT' 'AT' 'AT' ... 'SK' 'SK' 'TR' 'TR'
vs.
<xarray.IndexVariable 'station_name' (station_name: 384)>
array(['AT0ENK1', 'AT0ILL1', 'AT0KLH1', ..., 'SK0406A', 'TR0016A', 'TR0017A'],
dtype=object)

**Comment by jgriesfeller** [comment]
Just as a comment:
At least for Aeronet where there's actually data removed both the lines 
```python
arr[0] = arr[0].where(obs_ok, drop=True)
arr[1] = arr[1].where(obs_ok, drop=True)
```
and 
```python
arr = arr.where(obs_ok, drop=True)
```
crash.

The 1st is logical because the `station_name` dimension is actually shared between `arr[0]` and `arr[1]` but the second should work, but does not:
```
File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/xarray/core/common.py", line 1078, in where
    self = self.isel(**indexers)
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/xarray/core/dataarray.py", line 1283, in isel
    ds = self._to_temp_dataset()._isel_fancy(
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/xarray/core/dataset.py", line 2458, in _isel_fancy
    coord_vars, new_indexes = selected._get_indexers_coords_and_indexes(indexers)
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/xarray/core/dataset.py", line 2323, in _get_indexers_coords_and_indexes
    assert_coordinate_consistent(self, coords)
  File "/...
```
Interestingly it works when the `drop=True` keyword is removed.

**Comment by jgriesfeller** [comment]
I have created a PR for making it work and with a removal of an unnecessary data copy operation #715

**Comment by lewisblake** [comment]
Should I review since Alvaro is on vacation?

**Comment by WillemVanCaspel** [comment]
If you would be so kind! 

I am still a little puzzled by how the .where operation evens work on a numpy array. The stuff coming out of xarray objects using .data (as in coldata.data) are ndarrays, right?

**Comment by lewisblake** [comment]
They're xarray objects (https://docs.xarray.dev/en/stable/generated/xarray.where.html)
