### ISSUE TITLE
use original data format for AeronetDirectSun and AeronetSDA data

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#719]
Right now the AeronetDirectSun and Aeronet SDA readers use data that has been reformatted so that IDL can read these data faster (replacing a string for a NaN with a number).

We should switch to reading the original data format to be able to do the data set updates using ECflow easier.

**Comment by jgriesfeller** [comment]
**URLs (version 3 level 2.0):**

- tar file, one file per station
https://aeronet.gsfc.nasa.gov/data_push/V3/AOD/AOD_Level20_Daily_V3.tar.gz

- zip file, one file containing all stations
https://aeronet.gsfc.nasa.gov/data_push/V3/All_Sites_Times_Daily_Averages_AOD20.zip

**Comment by jgriesfeller** [comment]
another [presentation](https://aeronet.gsfc.nasa.gov/new_web/Documents/AeroCenter_Poster_Bash-AERONET.pdf), calls V1.5 NRT (slide 39). 

There is real NRT data in the web service. Example URL for all sites providing data at 30 August 2022:
https://aeronet.gsfc.nasa.gov/cgi-bin/print_web_data_v3?year=2022&month=8&day=30&year2=2022&month2=8&day2=30&AOD15=1&AVG=10&if_no_html=1

Documentation is here: 
https://aeronet.gsfc.nasa.gov/print_web_data_help_v3_new.html

**Comment by jgriesfeller** [comment]
To keep the old stuff running I suggest to create a new obs network for the new reader and deprecate the old one once the new one works reliably

**Comment by lewisblake** [comment]
Good idea. Maybe it could be done in the plugin framework
