### ISSUE TITLE
Inconsistency in split time series names

### ISSUE THREAD

**Issue by AugustinMortier** [metno/pyaerocom#720]
I've updated the web interface so it can read both files splitted by region or not, but it seems that the region name used in the filenames does not match the actual region name.

e.g
*Time series* 
https://gitlab.met.no/aeroval/cams2-82/-/tree/master/IFS-beta/hm/ts
`EEUROPE-AN-EEA-MP-concpm10-Surface.json`

*Regions*
https://gitlab.met.no/aeroval/cams2-82/-/blob/master/IFS-beta/regions.json
```
{"ALL": {"minLat": -90, "maxLat": 90, "minLon": -180, "maxLon": 180}, "N America": {"minLat": 18.95, "maxLat": 71.15, "minLon": 172, "maxLon": -52}, "Europe": {"minLat": 27.75, "maxLat": 66.45, "minLon": -31.25, "maxLon": 44.75}, "E Europe": {"minLat": 34.65, "maxLat": 59.55, "minLon": 12.15, "maxLon": 44.75}, "Rus,Bel,Ukr": {"minLat": 29.45, "maxLat": 66.25, "minLon": 22, "maxLon": -170}, "Middle East": {"minLat": 12.15, "maxLat": 39.65, "minLon": 34.25, "maxLon": 63.25}, "E Asia": {"minLat": 18.25, "maxLat": 53.55, "minLon": 73.65, "maxLon": 145.75}, "S Asia": {"minLat": -9.75, "maxLat": 37.05, "minLon": 46.35, "maxLon": 97.35}, "SE Asia": {"minLat": -11.65, "maxLat": 28.45, "minLon": 92.25, "maxLon": 155.95}, "N Africa": {"minLat": 19.05, "maxLat": 37.25, "minLon": -17.05, "maxLon": 35.75}, "C America": {"minLat": -4.15, "maxLat": 32.65, "minLon": -118.35, "maxLon": -51.65}, "S Africa": {"minLat": -54.45, "maxLat": 27.25, "minLon": -25.35, "maxLon": 77.55}, "S America": {"minLat": -59.45, "maxLat": 5.15, "minLon": -109.35, "maxLon": -26.25}, "Pacific,Aust,NZ": {"minLat": -54.75, "maxLat": 11.55, "minLon": 112, "maxLon": -134}, "Oceans": {"minLat": -59.95, "maxLat": 66.25, "minLon": -180, "maxLon": 180}}
```

In this case, the time series should be called
`E Europe-AN-EEA-MP-concpm10-Surface.json`

**Comment by lewisblake** [comment]
This is one of those things which you may call a bug, but I would call a feature ;)

If we are splitting the timeseries files by region, then the safe way to do this is to use what pyaerocom internally uses to represents the region, not the region name. Doing so avoids some technical issues, like having spaces in file names. There are many technical reasons for this (https://superuser.com/questions/29111/what-technical-reasons-exist-for-not-using-space-characters-in-file-names).

`regions_defs.py` links the regions to the region names through dictionaries such as 

```
_HTAP_NAMES = {
    "NAM": "N America",
    "EUR": "Europe",
    "EEUROPE": "E Europe",
    "RBU": "Rus,Bel,Ukr",
    "MDE": "Middle East",
    "EAS": "E Asia",
    "SAS": "S Asia",
    "SEA": "SE Asia",
    "NAF": "N Africa",
    "MCA": "C America",
    "SAF": "S Africa",
    "SAM": "S America",
    "PAN": "Pacific,Aust,NZ",
    "OCN": "Oceans",
}
```

So maybe we should discuss this more.

**Comment by AugustinMortier** [comment]
The spaces in the file names are not an issue on my scripts on the web side, at least (which is the only place where the AeroVal files are used right now).. I'm opened to the idea of changing that in future releases, or at least discussing it though :)
However, for consistency with all other files whose file name already includes the region name as is, I think we should probably keep the proper region names in the meantime. Doing otherwise would imply different logic for different types of files, which is not ideal.
