### ISSUE TITLE
Outdated tutorials

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#728]
The tutorials need updating to reflect the latest functionality of pyaerocom. In [getting_started_setup.html](https://pyaerocom.met.no/pyaerocom-tutorials/getting_started_setup.html) one of the first code snippets

```python
from pyaerocom.testdata_access import TestDataAccess
TestDataAccess().download()
```
fails because `TestDataAccess` is no longer part of the code base. There are also many [obsolete tutorials](https://github.com/metno/pyaerocom-tutorials/tree/master/obsolete), which have functionality which would be still be useful.

**Comment by lewisblake** [comment]
https://github.com/metno/pyaerocom-tutorials/pulls

**Comment by avaldebe** [comment]
Maybe we need to move the test data back to pyaerocom?
