### ISSUE TITLE
Missing model data is interpolated when colocate_time=True

### ISSUE THREAD

**Issue by dulte** [metno/pyaerocom#736]
When colocate_time=True one expects the time stamp to be removed if either obs data or model data is missing. When obs data is missing, the model data is removed at that point. But in the reverse case, model data is interpolated instead of the obs data being removed. This means that you will end up with phantom model data

This is most probably done because model data is assumed to be complete

(sorry for the bad explanation, I will elaborate more during the meeting)

**Comment by jgriesfeller** [comment]
In the case of satellite data (as model data) model data is also not complete. So this is a bug that needs to be resolved.

**Comment by dulte** [comment]
#755
