### ISSUE TITLE
Filtering by altitude = nan 

### ISSUE THREAD

**Issue by hannasv** [metno/pyaerocom#74]
In Aas et al subset the altitude is nan (since its not provided). This becomes as issue when trying to co-locate with other datasets since its automatically calls filter by a altitude below 1000m. The code below reproduces the DataExtractionError: Filtering results in empty data object.

```python
vars_to_retrieve = 'wetso4'
OBS_network = 'GAWTADsubsetAasEtAl'
MODELS = ['TM5-met2010_AP3-CTRL2019', 'NorESM2-met2010_AP3-CTRL']

ungridded_data    = ReadUngridded().read(datasets_to_read = OBS_network, vars_to_retrieve = vars_to_retrieve)
list_gridded_data = [pya.io.ReadGridded(ID).read(vars_to_retrieve = [vars_to_retrieve], start = 2010)[0] for ID in MODELS ] 

# Possible to retrieve ts type of obeservation 
list_colocate = []
for gridded_data in list_gridded_data:
    list_colocate.append(pya.colocation.colocate_gridded_ungridded(gridded_data, 
                                                                   ungridded_data, 
                                                                   ts_type='monthly'))

```

**Comment by hannasv** [comment]
@jgliss thoughts?

**Comment by jgliss** [comment]
Hmm, you could try to use method:

```python
pya.geodesy.get_topo_altitude(lat=station_data.latitude, lon=station_data.longitude)
```
preferably during reading of the data. For colocation, could be also good to throw proper error if none of the stations in the `UngriddedData` has altitude set. And suggest to provide a different filter name (since default is noMOUNTAINS).

**Comment by hannasv** [comment]
It is using the default. I thought noMOUNTAINS is the reason it filtering below 1000m? If I update the altitude to 
```python 
pya.geodesy.get_topo_altitude(lat=station_data.latitude, lon=station_data.longitude)
``` 
we have to make geonum a requirement. I am experiencing some issues with installation but I'll give you an update ones its all working.

**Comment by hannasv** [comment]
I'm not really sure what's going on here. I can import geonum in the console in spyder. Running pyaerocom yields the following error. 
```python 
  File "/home/hannas/Desktop/pyaerocom/pyaerocom/geodesy.py", line 55, in get_topo_data
    raise ModuleNotFoundError('Feature disabled: geonum library is not '
ModuleNotFoundError: Feature disabled: geonum library is not installed
```

**Comment by hannasv** [comment]
Never mind. It seems to be working now.

**Comment by hannasv** [comment]
I have updated the reading routine in Aas et al to use the altitude found by geodesy.  For most stations it works however I get these issues for at least one ... @jgliss 
```python
~/anaconda3/envs/pya/lib/python3.7/site-packages/geonum/topodata.py in get_altitude(self, lat, lon)
    367         dat = self.data[idx_lat, idx_lon]
    368         if np.isnan(dat):
--> 369             raise ValueError("Invalid value encountered in topodata...")
    370         return dat
 ValueError: Invalid value encountered in topodata...
```
