### ISSUE TITLE
Documentation Hackathon

### ISSUE THREAD

**Issue by dulte** [metno/pyaerocom#770]
- [ ] Colocation (Lewis)
- [ ] Pyaerocom scaffolding (Daniel / Lewis)
- [ ] Aeroval webpage (Augustin)
- [ ] Pyaeroval (Daniel)
- [ ] Remove plotting, make an unsupported plugin
- [ ] Readers (Alvaro / Daniel)

**Comment by lewisblake** [comment]
#728

CAMS2_82 partners will likely want to start using pyaerocom, and it would be good to have updated tutorials and documentation by then

**Comment by lewisblake** [comment]
Still relevant I think, although not sure if it needs to be a Hackathon.
