### ISSUE TITLE
Rewrite EMEP reader

### ISSUE THREAD

**Issue by dulte** [metno/pyaerocom#771]
- [ ] Make naming convention more flexible 
- [ ] Combine multiple files to make one dataset. Can now combine one year files. Should do the same for e.g. one hour-files

**Comment by jgriesfeller** [comment]
We basically decided to stick to one model data input format only (aerocom phase 3). This basically means we should focus on a fast and easy way to convert EMEP output to aerocom. In earlier years this has been done serially in a bash script, but recent developments regarding parallelization gave me some knowledge how to parallelize the conversion quite easily using the research queue. I think we should discuss this issue with that in mind again.
