### ISSUE TITLE
Make minimal common observation data

### ISSUE THREAD

**Issue by dulte** [metno/pyaerocom#773]
This is a suggestion for a MINImal Common Observation Data (miniCOD) format for the minimal about of observation data needed for pyaerocom/aeroval to make an evaluation.

For external users I want to define a simple csv schema/format, that is easy for users to make their data into. This makes it so that external users can format their data onto this format, and thus be sure that pyaerocom can read it out of the box. This means that users can test data without being taught how to write readers, making it easy for us and them.

This is not meant for complicated or large datasets!

- [ ] Define a csv schema for this format
- [ ] Create a reader
- [ ] Tests

**Comment by avaldebe** [comment]
This will be handled by the [pyaro interface](https://github.com/metno/pyaro)
