### ISSUE TITLE
model output in other projections

### ISSUE THREAD

**Issue by mmd1998** [metno/pyaerocom#775]
EMEP4NO run uses a Lambert conformal conic projection (LCC) which can't be handeld by pyaerocom colocate. A possible sollution is to convert observation location from the latlon projection into the lambert projection, so that the model and observation can be colocated under the same projection. Heiko has developed a tool called fimex that could do such conversion. So it would be nice if pyaerocom could apply fimex (or borrow some code from fimex) to realize colocate in other projections.

**Comment by lewisblake** [comment]
Related to #699?

**Comment by mmd1998** [comment]
I once used fimex to convert my model output to latlon. There are several  problems with this method: 1) it takes extremely long time to convert hourly model output. Converting from the obervation location should be much faster. 2) not only the projection, but some other properties are also modified/missing after the conversion, so that pyaerocom still can't colocate fimex output. Need to find out why. And whatever extra postprecessing is needed, manipulating the hourly output is extreme slow. 3) most critical reason is that, there's accuracy missing in the model's projection conversion, The converted model output is not exactly the same. 

Therefore, Hilde suggested the method I wrote in the beginning. Instead of converting the model, we could instead convert the projection of observations. Hilde, Daniel, and I discussed together yesterday, and decided to create an issue so that we could follow up with it. 

What do you think?
