### ISSUE TITLE
Review different pyaerocom CLI's and harmonise into single CLI

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#78]
Currently, we have 3 command line interfaces in pyaerocom:

- **pyaeroeval** ([pyaerocom.web.cli.main_aerocom_evaluation:main](https://github.com/metno/pyaerocom/blob/v090dev/pyaerocom/web/cli/main_aerocom_evaluation.py)) : processing routines for [AeroCom Evaluation](https://aerocom-evaluation.met.no/main.php?project=aerocom) website.
- **pyaerotrends** ([pyaerocom.web.cli.main_trends_evaluation:main](https://github.com/metno/pyaerocom/blob/v090dev/pyaerocom/web/cli/main_trends_evaluation.py)): processing routines for [trends interface](https://aerocom-trends.met.no/).
- **NOT IN USE**: [pyaerocom.scripts.main.cli](https://github.com/metno/pyaerocom/blob/v090dev/pyaerocom/scripts/main.py): currently not working or in use, but initially designed to resemble old IDL plotting tools.

This functionality should be contained in **a single** CLI called **pya**, e.g. using [subparsers](https://pythonhosted.org/argh/subparsers.html).

E.g. **pyaeroeval** and **pyaerotrends** could be subtasks of **pya**, e.g.:

```
pyaeroeval aerocom optics2019 -m ECMWF* -o Aeronet*
```

would become (via subparser **eval**)

```
pya eval aerocom optics2019 -m ECMWF* -o Aeronet*
```

Similar for trends processing:

```
pyaerotrends default
```

would become (via subparser **trends**)

```
pya trends default
```

This needs some discussion first, which largely depends on which other functionality should be provided via the CLI. E.g.

```
pya plot scatter -m ECMWF_CAMS_REAN -o AeronetSunV3Lev2.daily -v od550aer --start 2010 --stop 2015 --outdir "~/MyPyaerocom"
```

**Comment by MichaelSchulzMETNO** [comment]
Ketzerische Frage: Do we need this command line interface at all? Wouldnt it be good with notebooks, synchronised to python files (see my mail from yesterday) stored as examples, which would work as such?

**Comment by jgliss** [comment]
In my opinion: I think a CLI has its value, yes, at least for the automated web processing tools since it is so much quicker for me (and probably others that may want to use them) to update the interface etc. from the CLI. 

I also think that a command line interface can be very nice, e.g. for someone to just do create some quick standard  results (e.g. 12 AOD maps as .png files from a monthly model output, or a scatter plot from that). For instance, for a quick check after running a model.

For me personally, having to open a (or create a new) notebook somewhere and doing this would be often (even on a subconscious level), too much effort and I would probably not do it at all. And then I would accumulate all these notebooks somewhere, whereas the CLI would not need any new coding (or updating existing code, e.g. in an existing notebook) from my side and just create the output (figures, or CSV files, or ...).

Also, from my experience, if I go the step to create a notebook to do something very specific, I often end up playing around too much in it and loosing the focus and loosing time.

But these are just personal views! I do think though that a CLI would have its value. But probably, it should be kept simple and wrap around certain tasks, that we (want to) do all the time.

**Comment by MichaelSchulzMETNO** [comment]
no problem, good to have several ways to use pyaerocom ! Its good to have one approach for command line use. I guess in the IDL tools the choice of model id, obs id, year of model and year of obs and the variable was giving a lot of flexibility to script processing. Attached to the variable was a configuration file which was specifying more details on the plotting and processing.

**Comment by avaldebe** [comment]
As far as I can tell, the current version has only one cli

https://github.com/metno/pyaerocom/blob/3e8048895bbd403e504a99e38967f43afc441dbf/setup.cfg#L59-L61
