### ISSUE TITLE
Temperature data

### ISSUE THREAD

**Issue by AugustinMortier** [metno/pyaerocom#788]
As part of the [observations explorer](https://aeroval.met.no/evaluation.php?project=obs) project, it would be great to have temperature data, in addition to the already supported precipitations. Those two variables could be part of the 'meteorology' experiment.
EBAS provide temperature data over Europe.

**Comment by dulte** [comment]
Surface temp. is already defined as ts in variables.ini, so you only need to add it to the ebas_config. EBAS has a variable called temperature, which is found as "air", "instrument", "met", or "aerosol" or "PM X"

**Comment by lewisblake** [comment]
Currently implemented in main and working in test observation meteorology experiments
