### ISSUE TITLE
Text in trend plot overlap for some figure sizes 

### ISSUE THREAD

**Issue by alpsjur** [metno/pyaerocom#80]
```
stationdata.compute_trend(var_name)
trend = stationdata.trends[var_name]
trend.plot(ax=ax)
```
can give a figure with overlapping text if the figure size is customized/small. See example in attached figure 
[trend_fig.pdf](https://github.com/metno/pyaerocom/files/4274962/trend_fig.pdf)

**Comment by jgliss** [comment]
Thanks. The plotting code is implemented in [pyaerocom.trends_engine.TrendsEngine.plot](https://github.com/metno/pyaerocom/blob/v090dev/pyaerocom/trends_engine.py), lines 416+ and could be optimized for these cases! I think this plotting function in general could be revised (e.g. fontsize, etc.).
