### ISSUE TITLE
second Pool processes (to create the weird plots) hang when running the long forecast evaluation

### ISSUE THREAD

**Issue by charlienegri** [metno/pyaerocom#807]
when running the eval_type=long evaluation of the forecast (i.e. when the p flag is > 1, this does not affect the analysis since pool is 1 then)
there is a need of running 2 Pool(pool) processes one after the other, and the second (see https://github.com/metno/pyaerocom/blob/temporary-cams2-83/pyaerocom/scripts/cams2_83/cli.py#L402) hangs.

the first Pool(pool) process completes without issues, and the code runs successfully up to here https://github.com/metno/pyaerocom/blob/temporary-cams2-83/pyaerocom/scripts/cams2_83/cli.py#L394
if I re-run commenting out the workflow up to this line 394 (e.g. keeping the cache and results and not re-running the first Pool), the Pool that creates the weird plots runs without issues.

I suspect every multiprocessing instance in main has to have its own function call: here the function called in main is runner(), but it's not straightforward to modify the code then since runner() contains both Pool creations...

(this is not super urgent, it affects only the seasonal evaluation, and I can run that manually in 2 steps with the above mentioned hack)

**Comment by charlienegri** [comment]
I'll test a separation into 2 calls, one to a runner() function that does everything up to the weird plots followed by a new call to a runner2() that does the weird plots stat only.. but this feels dirty

**Comment by charlienegri** [comment]
Alvaro improved the code a bit but the issue is still there, same behaviour, hangs when full run, works if first part of the run is commented out

**Comment by lewisblake** [comment]
Is this new behavior or do we know if it has always done this?

**Comment by charlienegri** [comment]
introduction of multiprocessing for obs reading and weird plots is very recent, is the latest thing Daniel implemented for cams2-83, so it has always been there afaik, but it affects only the "long" runs so not easy to catch

**Comment by charlienegri** [comment]
workaround has been implemented since a while
