### ISSUE TITLE
vmro3 and vmrco evaluation

### ISSUE THREAD

**Issue by michaelgau** [metno/pyaerocom#821]
I'm trying to evaluate
 - vmro3 against hourly measurements in 2018, and
 - vmrco against daily measurements in 2020.
Both fail. Maybe trivial to fix? My config files are here:
/lustre/storeB/project/fou/kl/emep/ModelRuns/CWF/pyaerocom/cfg_michaelg_mike-vra2020.py  (vmrco failure)
/lustre/storeB/project/fou/kl/emep/ModelRuns/CWF/pyaerocom/cfg_michaelg_mike-hourly.py  (vmro3 failure)
Can talk about it at the next pyaerocom meeting.

**Comment by lewisblake** [comment]
Do you have any information from the error log? Unfortunately recreating this issue porior to about Thursday may be difficult due to this issues with storeB, but maybe something from the logs would indicate what went wrong without needing to directly run the config file. Thanks

**Comment by michaelgau** [comment]
Do you mean the "pyaerocom.log" file?

For the vmrco problem it says
0    None    vmrco   NOT OK: Missing/invalid obs variable

For vmro3 it's hard to find the error message. The file is already 330 Mbyte large and there are so many vmro3 occurrences. Probably I should delete it and run the hourly evaluation once more.

**Comment by lewisblake** [comment]
@michaelgau This has been completed, correct?

**Comment by michaelgau** [comment]
Yes, thanks.
