### ISSUE TITLE
FAIRMODE stats

### ISSUE THREAD

**Issue by michaelgau** [metno/pyaerocom#829]
Easy issue: We should update some of the parameters in https://github.com/metno/pyaerocom/blob/main-dev/pyaerocom/aeroval/fairmode_stats.py  ... github allows me to edit, but probably I shouldn't? Who is responsible for that file right now?

**Comment by lewisblake** [comment]
Hi @michaelgau this is the correct way to bring an issue to our attention :) I can pick up the issue and submit a PR. Please detail here what the new parameters should be. Thanks!

**Comment by michaelgau** [comment]
it's in fairmode_stats.py , SPECIES = dict ...

Currently, the values for PM10 and PM2.5 are:

    concpm10=dict(UrRV=0.28, RV=50, alpha=0.13),
    concpm25=dict(UrRV=0.36, RV=25, alpha=0.3),

They should be changed to:

    concpm10=dict(UrRV=0.28, RV=50, alpha=0.25),
    concpm25=dict(UrRV=0.36, RV=25, alpha=0.5),

**Comment by michaelgau** [comment]
wait... one more thing: is there a possibility to evaluate "daily maximum of 8-hour moving average" for ozone (instead of hourly data).

**Comment by lewisblake** [comment]
Probably there is, but such a feature request would be outside the scope of the original PR. You are welcome to open a new issue for that though, but ti sounds like that will take more time

**Comment by michaelgau** [comment]
OK, thanks. I will attend a FAIRMODE meeting later this week. I'll try and find out how important it is and then open a new issue, if needed.
