### ISSUE TITLE
Not able to read the new CHIMERE data

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#83]
I tried to read the CHIMERE data that was prepared today, and it failed with 

`OSError: None of the input files could be loaded in CHIMERE.cams61.day1`

The following lines of code produces the error on my machine:

`import pyaerocom as pya`
`pya.const.add_data_search_dir('/home/hansb/lustre/storeA/project/fou/kl/CAMS61/')`
`pya.browse_database('*CHIMERE*')`
`chimere = pya.io.ReadGridded(data_id='CHIMERE.cams61.day1')`
`data = chimere.read_var(var_name='sconcpm10',ts_type='hourly')`

**Comment by jgliss** [comment]
I think the reason is that the variable name in the files is different from the one in the filenames. The error is raised in pyaerocom/io/iris_io.py, method `load_cube_custom`:

```python
cube_list = iris.load(file)
    
    _num = len(cube_list)
    if _num != 1:
        if _num == 0:
            raise NetcdfError('Data from file {} could not be loaded using iris'
                              .format(file))
        else:
            logger.warning('File {} contains more than one variable'
                           .format(file))
    cube = None
    if var_name is None:
        if not len(cube_list) == 1:
            vars_avail = [c.var_name for c in cube_list]
            raise NetcdfError('Could not load single cube from {}. Please '
                              'specify var_name. Input file contains the '
                              'following variables: {}'.format(file, 
                                                               vars_avail))
        cube = cube_list[0]
        var_name = cube.var_name
    else:
        for c in cube_list:
            if c.var_name == var_name:
                cube = c
                break
    if cube is None:
        raise NetcdfError('Variable {} not available in file {}'.format(var_name, 
                                                                        file))
```

**Comment by jgliss** [comment]
Closing this as this has been resolved.

**Comment by jgliss** [comment]
Just a follow up @hansbrenna and @jgriesfeller 

This works now after recent update in branch dev_read_ghost:

```python

reader = pya.io.ReadGridded('CHIMERE.cams61.day1')
data = reader.read_var('sconcpm10').extract_surface_level()
data.quickplot_map()
```

Note that the changes in ReadGhost will trigger a reload of any cached UngriddedData object on your local machine.

Cheers
