### ISSUE TITLE
map plots of non-observables

### ISSUE THREAD

**Issue by andagit** [metno/pyaerocom#832]
For CAMS2_82 there is a request for plots of speciated AODS - available from the Aeroval Maps menu?

**Comment by jgriesfeller** [comment]
as comment: I just tried to create a maps only experiment for the DOMOS project and found out that just setting `only_model_maps=True,` in the config does not result in a valid aeroval experiment.
I guess that was more meant as an update of the maps of an existing experiment (?)

**Comment by lewisblake** [comment]
Potential solution: For e.g., sulfate AOD, we introduce these variables into the Aeronet reader and vairables.ini, associating them with total AOD. Can either suppress statistics or interpret them with care (could be interesting). Look at this solution and go from there. For maps use monthly time-resolution.
