### ISSUE TITLE
Clean up MEP, IPCForests and remove MarcoPolo

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#842]
Clean up some of the work from #805 and remove MarocPolo from pyaerocom. This data set is dead now

**Comment by lewisblake** [comment]
Can you link the issue / PR please?

**Comment by jgriesfeller** [comment]
IPCForests PR: #746

**Comment by jgriesfeller** [comment]
No PR for solving this issue yet

**Comment by lewisblake** [comment]
Closed #738
