### ISSUE TITLE
Reading derived variable "conco3" from GHOST does not work properly

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#86]
When reading the derived variable `conco3` from GHOST, there is an issue with some of the meta data. At least somewhere the variable name is not updated. This becomes a problem when trying to co-locate the data with a model, since the altitude filter raises a `KeyError` since the variable name is still `vmro3`.

The code below provides a minimal example to recreate the error on my system.

```
import pyaerocom as pya

obs_reader = pya.io.ReadUngridded()
network = 'GHOST.hourly'

variable = 'conco3'

obs = obs_reader.read(network, variable)

obs.filter_altitude((0,1000))
```

```
Traceback (most recent call last):

  File "/home/hansb/untitled0.py", line 19, in <module>
    obs.filter_altitude((0,1000))

  File "/home/hansb/pyaerocom/pyaerocom/ungriddeddata.py", line 1286, in filter_altitude
    return self.filter_by_meta(altitude=alt_range)

  File "/home/hansb/pyaerocom/pyaerocom/ungriddeddata.py", line 1468, in filter_by_meta
    meta_matches, totnum_new = self._find_meta_matches(*filters)

  File "/home/hansb/pyaerocom/pyaerocom/ungriddeddata.py", line 1269, in _find_meta_matches
    totnum += len(self.meta_idx[meta_idx][var])

KeyError: 'vmro3'
```

**Comment by jgliss** [comment]
Hi @hansbrenna, I think I fixed it (v090dev). Can you check now? 
Cheers, Jonas

**Comment by jgliss** [comment]
@hansbrenna I am closing this issue as I assume this works now. Feel free to reopen if not.
