### ISSUE TITLE
Aeroval maps of PM seem wrong

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#864]
The maps for PM10 and PM2.5 seem wrong. This just effects PM, not e.g., no2 and so2. Checking the data with ncview shows that the raw data appears okay.
![Screenshot from 2023-05-22 13-28-50](https://github.com/metno/pyaerocom/assets/24661500/6214502c-1508-4da9-9b4f-11dc8981c912)

From @andagit (Could you please also link to the data files?)
![unnamed](https://github.com/metno/pyaerocom/assets/24661500/4b00c9fd-f3c6-4936-aeab-34612e2444cf)

**Comment by jgriesfeller** [comment]
Just to add to this... The following maps should show the same (I created some monthly mean data with cdo):
![image](https://github.com/metno/pyaerocom/assets/10772065/ba83382e-2b51-48a0-b811-2f5121b57b37)
![image](https://github.com/metno/pyaerocom/assets/10772065/7b97ca6a-9bb7-4a06-9e70-180ba54ceee5)

The units are unfortunately not the same, but even the patterns look different. The files look OK. Very weird.

**Comment by lewisblake** [comment]
Maybe it's just a fluke with lustre and if we ran the experiment again it might work?

**Comment by lewisblake** [comment]
```
Processing model maps for IFS-ESUITE (concpm10)
Searching database for ECMWF_ESUITE
/lustre/storeB/project/aerocom/aerocom-users-database/ECMWF/ECMWF_ESUITE has subdir renamed. Using that one
Found match for ID ECMWF_ESUITE
Did not find concpm10 field but sconcpm10. Using the latter instead
Invalid time dimension coordinate in file:
/lustre/storeB/project/aerocom/aerocom-users-database/ECMWF/ECMWF_ESUITE/renamed/aerocom3_ECMWF_ESUITE_sconcpm10_Surface_2022_daily.nc.
Error: repr(Cube does not contain time dimension)
```

**Comment by andagit** [comment]
But this is from all comps, ie.:
![log](https://github.com/metno/pyaerocom/assets/22189399/3697dc41-9eba-4c7b-9cdb-0ebd3e31540b)

**Comment by lewisblake** [comment]
Yes, just making notes to myself. This is typical although look suspicious at first glance

**Comment by lewisblake** [comment]
![d25aeeae-dbfd-445d-b458-e86b12864501](https://github.com/metno/pyaerocom/assets/24661500/e9879b0d-a71f-4b9b-8fc7-8138ea191bbf)
Iris cube after rearranging longitude coords to [180, 180) seems fine

**Comment by lewisblake** [comment]
![82ef9f31-aedf-4ff3-a7a8-20047a6173a8](https://github.com/metno/pyaerocom/assets/24661500/9a3c3e2d-9910-4dba-a7c7-7ef5cd01e569)

Same iris cube before being written to geojson. Between pyaerocom/io/iris_io.py(208)check_and_regrid_lons_cube()
and pyaerocom/aeroval/modelmaps_engine.py(158)_process_map_var() the problem occurs

**Comment by lewisblake** [comment]
![42732729-ed87-4231-b3a2-c3707395c1e2](https://github.com/metno/pyaerocom/assets/24661500/59e6ddf4-2df5-4e66-9e56-e46962a6e1f0)
iris cube before being put into `GriddedData` object. Still looks okay

**Comment by lewisblake** [comment]
![072ea505-c8d2-4dbb-ade4-72f6c044b23e](https://github.com/metno/pyaerocom/assets/24661500/f60d581a-25df-47b9-b60e-bc1e4d62c6f3)
After becoming a `GriddedData` object it gets messed up

**Comment by lewisblake** [comment]
Before calling iris.grid.convert_units():

![7bf5477e-fc02-474f-ab94-e5dbf9e155cc](https://github.com/metno/pyaerocom/assets/24661500/f653a909-5fe0-4fd0-bacb-72873cc234bd)

After calling iris.grid.convert_units():

![d20e5fe4-6ba9-45fa-a2cd-d9f2162f010a](https://github.com/metno/pyaerocom/assets/24661500/57db3183-a84a-4df0-a742-4ad8f868e4b2)

Happens in pyaerocom/gridded_data.py::convert_unit() line 849. Seems like the issue is with iris

**Comment by lewisblake** [comment]
BTW, in pyaerocom/io/iris_io.py line 535 has `cube.attributes["timedim-corrected"] = True`which is technically wrong because netcdf can't have boolean attributes when saving an iris cube.

**Comment by lewisblake** [comment]
Using iris 3.5.0  pyhd8ed1ab_0 conda-forge

**Comment by lewisblake** [comment]
![Screenshot from 2023-06-02 11-43-13](https://github.com/metno/pyaerocom/assets/24661500/8410410e-d18a-40dc-9835-02e0bb46b56b)
Works with iris 3.4.1
