### ISSUE TITLE
Error in the number of stations

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#868]
![Screenshot from 2023-05-30 10-32-20](https://github.com/metno/pyaerocom/assets/24661500/144fa3a2-8e9f-4e71-9289-db4e112f0e9b)

In CAMS2_82, looking at the number of stations for E-SUITE, it appears as though there are stations for ESUITE in months prior to October 2022. This can not be since we only have data since October. So the number of stations are either being incorrectly applied or incorrectly visualized.

**Comment by lewisblake** [comment]
@AugustinMortier is this potentially an Aeroval issue?

**Comment by AugustinMortier** [comment]
A quick look at `hm/ts/ALL-AeronetL1.5-d-od550aer-Column.json` shows

```
{
    "od550aer": {
        "AeronetL1.5-d": {
            "Column": {
                "IFS-ESUITE": {
                    "od550aer": {
                        "ALL": {
                            "1642204800000": {
                                "totnum": 13392.0,
                                "num_valid": 0.0,
                                "refdata_mean": null,
                                "refdata_std": null,
                                "data_mean": null,
                                "data_std": null,
                                "weighted": 0.0,
                                "rms": null,
                                "nmb": null,
                                "mnmb": null,
                                "fge": null,
                                "R": null,
                                "R_spearman": null,
                                "num_coords_tot": 432.0,
                                "num_coords_with_data": 309.0
                            },
```

with `new Date(1642204800000) = Sat Jan 15 2022 01:00:00 GMT+0100 (Central European Standard Time)`

It looks like an issue in the statistics calculation, because num_coords_with_data is not null.

**Comment by lewisblake** [comment]
Thanks, I didn't have time to look into it on the fly, but thanks for doing so. Looks like we'll keep it here as an issue to address

**Comment by lewisblake** [comment]
![Screenshot from 2023-07-25 11-52-23](https://github.com/metno/pyaerocom/assets/24661500/df85b3eb-1c7a-4ea3-992f-9a869d31ce04)

Closing because the issue is no longer present and not reproducible
