### ISSUE TITLE
Suggestion BibTex citation

### ISSUE THREAD

**Issue by hannasv** [metno/pyaerocom#87]
Hei,

It quite common to cite python package these days, I've used the filter class in my thesis and plan to cite pyaerocom. I'm not sure how you do this in the earth system course, but I though it could be useful there that as well. Drawing inspiration from Cartopy, I made the following bibtex, 
any comments @MichaelSchulzMETNO ? 

@misc{pyaerocom,
author = {{MET Norway }},
title = {Pyaerocom, a Python package containing reading, post analysis and visualisation tools for the AEROCOM project.},
year = {2020},
address = {Oslo, Norway},
url = {https://pyaerocom.met.no/},
publisher={GitHub},
howpublished={\url{https://github.com/metno/pyaerocom}},
}

**Comment by MichaelSchulzMETNO** [comment]
That is a good idea! It has to enter the documentation webpage . Lets see with Jonas when he is available again.

**Comment by jgliss** [comment]
Good initiative @hannasv. Happy to hear you could use it in your thesis. I added a Citation section in the [README](https://github.com/metno/pyaerocom#citation).

I close this issue.
