### ISSUE TITLE
proxyod550s need better names on AeroVal and maps=only switch

### ISSUE THREAD

**Issue by andagit** [metno/pyaerocom#872]
Non-observables, proxyod550*, could probably be named without "proxy" on AeroVal and should only appear in Maps tab as they do not make sense to have elsewhere for evaluation.

**Comment by andagit** [comment]
Not sure if this is the time to add, but -: nh4 and no3 is still having proxynames in the ie. IFS-ESUITE-beta experiment

**Comment by lewisblake** [comment]
> Not sure if this is the time to add, but -: nh4 and no3 is still having proxynames in the ie. IFS-ESUITE-beta experiment

Weird. It looks like one of my last commits didn't go through... trying again

**Comment by lewisblake** [comment]
@andagit They should be in there  https://github.com/metno/pyaerocom/blob/865dee1d54e30dd61b3dda946831c36ed6678406/pyaerocom/aeroval/glob_defaults.py#L331

**Comment by lewisblake** [comment]
> This was solved the wrong way since in task4041 we want the model means to show up in the heatmap (but only these). Daniel had developed a flag named `CFG["model_only_stats"] = True` that does exactly that (it's in the ipc_forests branch), so we need to bring back the proxy variables to the heatmap in aeroval. This approach works unfortunately on the experiments level... so not that straight forward to bring together the two approaches... Not good for merging ipc-forests into main-dev before summer

Will @AugustinMortier's response cover it?
https://github.com/metno/pyaerocom/pull/873#issuecomment-1597163454

**Comment by andagit** [comment]
But we still need to renate files in exp directory to proxy?

man. 11. sep. 2023, 10:42 skrev Lewis Blake ***@***.***>:

**Comment by andagit** [comment]
Renaming is not necessary, just make sure that the menu.json have the correct config for all proxy* variables:
"only_use_in": [
            "maps"
        ]

**Comment by andagit** [comment]
Renaming is still necessary, but why?
