### ISSUE TITLE
Make computed statistics configurable

### ISSUE THREAD

**Issue by AugustinMortier** [metno/pyaerocom#885]
The lately introduced Mean Bias and Mean Absolute Bias seem to be set as default statistics since they show up in freshly processed experiments (like the ones in CAMS2_83). I understand some project requires it, but it's not the case for most of them. I would suggest to remove those statistics from the list of the default used statistics. This would make the menus less overwhelming for most of the users, and mostly, the files smaller by default.

**Comment by michaelgau** [comment]
for CAMS2_83, Mean Bias can stay. Easy to understand and useful. Only Mean Absolute Bias can go.

**Comment by lewisblake** [comment]
want: configurable list of statistics that make it into the json files

**Comment by jgriesfeller** [comment]
C3S2 needs these lately introduced statistics. But I'm in favor of a configurable way for what makes it into the json files

**Comment by lewisblake** [comment]
Note: task40401 PR has some of this functionality implemented. Could be expanded to do multiple selections.

**Comment by lewisblake** [comment]
The number of decimals is set as a default to 1.
https://github.com/metno/pyaerocom/blob/89501477f70e4d47ef994e7e2d71e6b37839683d/pyaerocom/aeroval/glob_defaults.py#L337

This should be configurable based on project needs
