### ISSUE TITLE
test fail on conda-forge CI

### ISSUE THREAD

**Issue by avaldebe** [metno/pyaerocom#892]
v0.14.0 conda package conda-forge/pyaerocom-feedstock#23 fails with this message on Python 3.11.4

```
    def test_ReadEMEP__init__():
>       with pytest.raises(DeprecationWarning) as e:
E       Failed: DID NOT RAISE <class 'DeprecationWarning'>
```

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=760364&view=logs&j=516f237f-98f1-50a4-0946-c43fe5437b81&t=19870002-9ea0-5c64-a2c3-e2872fb3f101&l=623

**Comment by lewisblake** [comment]
Conda forge will not be supported in the near future. It is preferred that users pip install into a conda env if they need.
