### ISSUE TITLE
Errors in Country Database

### ISSUE THREAD

**Issue by heikoklein** [metno/pyaerocom#898]
The following countries are problematic in the pyaerocom country database:

MK: Macedonia -> North Macedonia
TR: Turkey -> Türkiye

SJ: Svalbard and Jan Mayen should be part of NO

**Comment by heikoklein** [comment]
https://github.com/metno/pyaerocom/blob/main-dev/pyaerocom/data/country_codes.json needs updating, too.

geocode usage:  https://github.com/metno/pyaerocom/blob/a216c5f1250f43ffafc907c4469cf92306696c30/pyaerocom/ungriddeddata.py#L719

**Comment by jgriesfeller** [comment]
I just had a deeper look at `reverse_geocode`: It does not have a license, so forking is problematic.
It basically works by using a list of known locations and uses the one with the smallest distance to determine the country of the point given. So the _intelligence_ is in that list. Unfortunately we need to assume that that list is copyrighted.

There is `geopy` which acts as interface to various web services that are slow and might need an account and payment (have a look at https://stackoverflow.com/questions/40634522/determine-country-from-its-geographical-locations-in-python)

Also keep in mind that e.g. MEP has nearly 2500 stations, so this needs to be speedy or cached or...

So replacing reverse_geocode is not as easy as it seems.

I also know about using shape files for this purpose, but I have not found an easy way to use them for this purpose in Python. 

Any suggestions?

**Comment by jgriesfeller** [comment]
Shapely (https://shapely.readthedocs.io/en/stable/) seems to have the infrastructure to use shape files to determine the country of a given point and is in conda

**Comment by heikoklein** [comment]
For shapefile, I suggest using one of the natural_earth shapefiles, i.e. I'm using for UN-country borders admin_0_countries_deu: 
https://scitools.org.uk/cartopy/docs/latest/reference/generated/cartopy.io.shapereader.natural_earth.html

I use shapely or osgeo.ogr for lookups: https://gitlab.met.no/emep/uemep-web/-/blob/master/src/kart/UEmep/GrunnkretsLookup.py (internal link only, but Jan/Alvaro have access) or  https://gitlab.met.no/emep/uemep-web/-/blob/master/src/kart/UEmep/GrunnkretsLookupOgr.py

When testing speed a few years ago, shapely is a bit slow on startup and had internal memory allocation problems which were critical for a webservice, but might work well for pyaerocom.

**Comment by lewisblake** [comment]
Is it envisioned that pyaro will handle this? https://github.com/metno/pyaro-readers/tree/main-dev/src/geocoder_reverse_natural_earth

**Comment by heikoklein** [comment]
It's the pyaro-readers, not the pyaro interface which come bundled with this implementation. We intend to keep it there unless pyaerocom insists putting it into a separate repo.

**Comment by lewisblake** [comment]
This is a very common problem and probably worth moving into a separate repository and using as a separate package. We propose this is moved into a package and put on PyPI and conda. It can then become a dependency of pyaro and pyaerocom, probably others outside the institute will use it, but we need to maintain it for our use anyway. There should not be any licensing issues.

**Comment by heikoklein** [comment]
There are two problems here: One is location->country lookup, which is handled in #952 . The original problem in this issue here is mapping of ISO2 code to country name, which is technically much simpler, but we might have requirements to use special names for a region or another. This should not be outsourced to an external package.

**Comment by heikoklein** [comment]
depends on: https://github.com/metno/geocoder_reverse_natural_earth/issues/3
