### ISSUE TITLE
Aeronet Sun daily reading routine

### ISSUE THREAD

**Issue by paulina-t** [metno/pyaerocom#9]
It would be good to also read the number of measurements from which daily averages where computed.

**Comment by jgliss** [comment]
Started working on this some time ago in #223, however, perhaps this needs some more general implementation, also with respect to temporal resampling, so perhaps, numobs could not be a separate variable to be read, but one more column in UngriddedData, i.e. like flags, etc. for each measurement.

**Comment by jgliss** [comment]
Closing this until there is no clear need for this, or strategy how to handle / represent this in a more general way, e.g. in `UngriddedData`.
