### ISSUE TITLE
Flexible filtering of regions for AeroCom Evaluation web processing tools

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#90]
Currently, the pyaerocom web processing tools use pyaerocom default regions for regional statistics.  These are the regions that are currently stored in attr. OLD_AEROCOM_REGIONS in Config class (pyaerocom.const). Currently:

```python
import pyaerocom as pya
pya.const.OLD_AEROCOM_REGIONS
['EUROPE', 'WORLD', 'ASIA', 'AUSTRALIA', 'CHINA',
'INDIA', 'NAFRICA', 'SAFRICA', 'SAMERICA', 'NAMERICA']
```

which are displayed on the [website](https://aerocom-evaluation.met.no/main.php?project=aerocom) under *Regional statistics*.

The evaluation details about the web processing for a certain project and experiment is specified in configuration files that are loaded into the AerocomEvaluation class that is running colocation and creates all json files. 

These configuration files should allow for (optionally) specifying a custom list of regions IDs (must be specified in regions.ini and automatically accessible, cf. #89) which are then used instead of the default ones.

@AugustinMortier this will probably also need some adjustments at the front end :)

**Comment by jgliss** [comment]
It was decided today, that it would be useful to define the regions on the run, based on metadata in the observations, particularly for CAMS61, using the country code, or to define regions by a set of those metadata values (e.g. NORDIC = [country code Sweden, country code Norway, country code Finland, country code Iceland]).

This could be, e.g. defined in the processing configuration file via:

```python
use_regions : dict(
how='obsmeta', #optional, if not defined, look for the below names in regions.ini
obsmeta_key='country',
names={'Nordic' : ['Norway', 'Sweden', 'Finland', 'Iceland']
)
```
The problem with this (and the current design of the [web interface](https://aerocom-evaluation.met.no/main.php?project=aerocom)) is that the regions need to be the same throughout the different variables and that each region corresponds to a rectangular area.

That said, if, for e.g. CAMS61, we want to create regions based on country codes assigned to station data, then the rectangular regions associated with a country would be different for the different variables, if they would be defined by the outer borders of all sites associated with a country. 

And also, in an experiment, that would contain multiple different data sources (i.e. not only GHOST) it would be more difficult to define the regions and it may not be possible for some observations to filter by the corresponding meta key, since that observation does not include these meta information.

**Comment by jgliss** [comment]
A way to solve this could be:

- regions.json file is on experiment level (currently there is only one global regions.json for all projects and experiments)
- before any processing is done, the regions.json is created based on the settings in the config file which would need to have specified the observation data name from which the regions are defined:  
```python
use_regions : dict(
how='obsmeta', #optional, if not defined, look for the below names in regions.ini
obsname='GHOST',
obsmeta_key='country',
names={'Nordic' : ['Norway', 'Sweden', 'Finland', 'Iceland']
)
```
- for customised regions based on metadata, the regions.json would mark the outer edges based on the location of all sites located within a region applying the metadata filter defined.
- Then, during the analysis: if the observation data contains that metadata key, it is filtered by that and assigned to the corresponding region (country). Otherwise (e.g. if AERONET is also in the experiment), the corresponding rectangular region is used that was created based on the GHOST data)

**Comment by jgliss** [comment]
@AugustinMortier and @hansbrenna I would appreciate if you could comment. It may be a little more tricky to apply this country code based filtering. Maybe I also just think too complicated here.

**Comment by hansbrenna** [comment]
@jgliss I'm not completely sure why you say we need to define the edges of the regions? For doing the aggregation on country-based regions I was thinking the easiest way would be to just aggregate all stations with the same country code. This means going away from having "map-defined" regions to just using the metadata instead.

I'll see if I can prototype something today.

**Comment by jgliss** [comment]
@hansbrenna the reason at the moment is that the regions are displayed when hovering the bar in Regional Statistics. And: as mentioned above, CAMS61 is quite particular having only one observation network (allowing to filter by e.g. country code). Most other experiments (e.g. AEROCOM) contain many different observation networks, which contain different metadata, and it should be that any regions used in the web interface should be shared among all obs / var combinations displayed, e.g. in the heatmap. So that is why we need a rectangular area (as long as we do not have binary maps and filter by country code) for the regions, so that the interface could also filter e.g. AERONET in the corresponding region (which does not include country codes in the metadata).

Thanks for offering to help, but let me have a look at this today and tomorrow. I think we should not work on some issue at the same time (will create a merging mess).

I'll have a meeting from 10-12 and can only work on this in the afternoon.

**Comment by hansbrenna** [comment]
I see your point, and that takes us back to needing definitions of the country borders or something like that to be able to us (lat,lon) to assign a location to a country.

**Comment by AugustinMortier** [comment]
This is the library that I used for doing the reverse geocoding in the trends/covid19 page. By using such a system, you would not have to rely only on the country code in the metadata (which does not exist in AERONET for instance):
[reverse-geocoder](https://github.com/thampiman/reverse-geocoder)

**Comment by jgliss** [comment]
Thanks @hansbrenna and @AugustinMortier for your feedback and suggestions. After a brief chat with @AugustinMortier I think it is indeed best to assign countries by lat lon coordinates using, e.g. the library that you suggest, Augustin. This will ensure that the same "regions" are used throughout different obsnetworks and it will move away from the cumbersome solution I suggested above. 

It remains to be tested then, how this reverse mapping works in edge cases, e.g. for sites located on tiny Islands or in the oceans, or near country borders. But for me it seems like this is the way to go and makes it also much easier to streamline the processing code (as it does not rely on the availability of metadata in the observations).

Regardless of this, if we want to assign rectangles to regions (e.g. for the hover feature) we need to think how we do this then, but maybe this we can figure out in a second step. @AugustinMortier can you confirm that the *regions.json* file in the web interface is only used for the hovering?

**Comment by jgliss** [comment]
@hansbrenna just for your info: I will start looking into this reverse mapping now in a new branch (auto_regions_reverse_latlon) and I hope I will have a working example ready before the weekend.

**Comment by AugustinMortier** [comment]
@jgliss I can confirm that the regions are only used for displaying it in the map when hovering a bar.

**Comment by hansbrenna** [comment]
I think this sounds like a good solution. I'm looking forward to testing the prototype.

**Comment by jgliss** [comment]
@hansbrenna unfortunately, I did not manage to get a first working version of the country filters, but I have the basic functionality ready (i.e. retrieval via reverse_geocode library) and implementation of filtering by country name in `filter_region` method of `UngriddedData` and `ColocatedData`. I will probably manage on Monday to do the highlevel work needed for the web processing (if there is not too many other things popping up in addition ...).

**Comment by jgliss** [comment]
@hansbrenna @AugustinMortier I finished a first version of country region filtering for the web processing of gridded / ungridded. It can be activated in the config file via

```python
regions_how = 'country'
```
I haven't tested it and have to go into a meeting now.

Hans, can you test this (maybe in an 1 model / 1obs / 1 var test config) and push it so that Augustin can see if / what needs to be done on the frontend?

Augustin, for now the regions.json is ignored, so there is no information anywhere about the rectangular limits of each country.

We can discuss more this afternoon. Cheers.

**Comment by hansbrenna** [comment]
I ran the web processing like you suggested and it failed with the following traceback:

```
Traceback (most recent call last):
  File "cfg_cams61_2018-day1_test_country_regions.py", line 142, in <module>
    stp.run_evaluation()
  File "/home/hansb/pyaerocom/pyaerocom/web/aerocom_evaluation.py", line 986, in run_evaluation
    colocator=col)
  File "/home/hansb/pyaerocom/pyaerocom/web/aerocom_evaluation.py", line 670, in make_json_files
    self.compute_json_files_from_colocateddata(d, obs_name, model_name)
  File "/home/hansb/pyaerocom/pyaerocom/web/aerocom_evaluation.py", line 530, in compute_json_files_from_colocateddata
    self.colocation_settings, vert_code, self.out_dirs)
  File "/home/hansb/pyaerocom/pyaerocom/web/helpers_evaluation_iface.py", line 613, in compute_json_files_from_colocateddata
    regions_how, vert_code)
  File "/home/hansb/pyaerocom/pyaerocom/web/helpers_evaluation_iface.py", line 471, in _process_sites
    meta_glob = _init_meta_glob(coldata, vert_code=vert_code)
  File "/home/hansb/pyaerocom/pyaerocom/web/helpers_evaluation_iface.py", line 447, in _init_meta_glob
    meta_glob['obs_name'] = obs_name
NameError: name 'obs_name' is not defined
```
I'll try to debug, but please help out.

**Comment by jgliss** [comment]
@hansbrenna thanks for testing. This looks like an easy one and is probably only a result of the fact that I subdivided this (formerly) huge function into sub functions and probably forgot to pass some arguments. I'll check!

**Comment by jgliss** [comment]
@hansbrenna should be fixed now.

**Comment by hansbrenna** [comment]
I'll try it again.

**Comment by jgliss** [comment]
@hansbrenna found another bug (did not pass the new arg. `regions_how`in AerocomEvaluation when calling the method that computes the json files). Hope it works now.

**Comment by hansbrenna** [comment]
I will test it again now.
