### ISSUE TITLE
Too many regions assigned to stations

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#901]
In CAMS2_82 we noticed that too many regions are assigned to stations. It can be that a station is assigned one region and oceans, but not a third. 

https://cams2-82.aeroval.met.no/evaluation.php?project=cams2-82&exp_name=IFS&station=SE+Asia&mod=IFS-Reanalysis#

Ctrl+F e.g., N Africa in the station list. Also check the overall evaluation, for a region, number of stations. Then click on one of them and look at the linear model for pred vs obs. More stations appear in this linear model than are reported in the evaluation table.

**Comment by Ovewh** [comment]
I noticed that quite a few stations gets assigned "ALL" as the region, Does that mean it gets excluded from the regional calculation, or is ALL always included?
