### ISSUE TITLE
Bring Trends-fix into main-dev

### ISSUE THREAD

**Issue by Ovewh** [metno/pyaerocom#903]
There where some nice updates to the trend calculation implemented by @dulte that where (as far as i know)  never merged into main. Is there any interest of putting these changes into the pyaerocom?

**Comment by lewisblake** [comment]
[Example](https://aeroval.met.no/intercomp.php?project=emep-trends&exp_name=2000-2019&station=WORLD&statistic=obs_mean_trend#)

**Comment by dulte** [comment]
#1266 is a new PR that tried to do this. Main-dev seems to be successfully merged, with a working example: https://aeroval-test.met.no/danielh/pages/evaluation/?project=TrendsNew&experiment=2000-2010&statistic=obs%2Fmod_trend&station=ALL#
