### ISSUE TITLE
Support both yearly and monthly timeseries in one experiment

### ISSUE THREAD

**Issue by Ovewh** [metno/pyaerocom#904]
Currently it is not supported to show both yearly and monthly timeseries, within one experiment in aeroval. Would it be possible to add a toggle like the what is done with the statistics. Rather than letting main_freq determine the frequency of the timeseries used.

**Comment by lewisblake** [comment]
You specifically want the collocation of the time series to be shown at yearly frequency? Aeroval has the ability to show yearly and monthly time series, but the collocation frequency is still monthly. If you have an experiment over multiple years, the default time series is over the whole time frame. You can use the zoom-in feature to look at monthly time series for a specific year.

**Comment by Ovewh** [comment]
I want yearly timeseries to show the yearly mean. Under the evaluation timeseries tab. Here you can only have either monthly or yearly not both, like under evaluation heatmap.The seasonality can be a bit distracting when looking trends.

**Comment by lewisblake** [comment]
It looks like this info is already available in the json files in the `ts` directory, so this is an AeroVal issue. Let's chat with @AugustinMortier about how to include this functionality

**Comment by AugustinMortier** [comment]
This is about the scores time series (and not the data time series), so the files located in `hm/ts`, which only have data for the `main_freq` (if I'm not mistaken)
