### ISSUE TITLE
model order has changed on AeroVal

### ISSUE THREAD

**Issue by andagit** [metno/pyaerocom#935]
Model order in AeroVal experiment: https://aeroval.met.no/overall.php?project=cams2-82&exp_name=IFS
(in all json files) has suddenly (recently changed?) exactly the opposite of what it is in my experiment pyaerocom config:

# Setup for models used in analysis
MODELS = {
    "IFS-OSUITE": dict(model_id="ECMWF_OSUITE", model_read_aux=MODEL_AUX_VARS,model_use_vars=dict(proxyod550dust="od550dust",proxyod550so4="od550so4",proxyod550bc="od550bc",proxyod550nh4="od550nh4",proxyod550oa="od550oa",proxyod550ss="od550ss"),model_rename_vars=dict(od550dust="proxyod550dust",od550so4="proxyod550so4",od550bc="proxyod550bc",od550nh4="proxyod550nh4",od550oa="proxyod550oa",od550ss="proxyod550ss")),
    "IFS-OSUITE-96h": dict(model_id="ECMWF_OSUITE_96H", model_read_aux=MODEL_AUX_VARS,model_use_vars=dict(proxyod550dust="od550dust",proxyod550so4="od550so4",proxyod550bc="od550bc",proxyod550nh4="od550nh4",proxyod550oa="od550oa",proxyod550ss="od550ss"),model_rename_vars=dict(od550dust="proxyod550dust",od550so4="proxyod550so4",od550bc="proxyod550bc",od550nh4="proxyod550nh4",od550oa="proxyod550oa",od550ss="proxyod550ss")),
    "IFS-CTRL": dict(model_id="ECMWF_CNTRL", model_read_aux=MODEL_AUX_VARS,model_use_vars=dict(proxyod550dust="od550dust",proxyod550so4="od550so4",proxyod550bc="od550bc",proxyod550nh4="od550nh4",proxyod550oa="od550oa",proxyod550ss="od550ss"),model_rename_vars=dict(od550dust="proxyod550dust",od550so4="proxyod550so4",od550bc="proxyod550bc",od550nh4="proxyod550nh4",od550oa="proxyod550oa",od550ss="proxyod550ss")),
    "IFS-CTRL-96h": dict(model_id="ECMWF_CNTRL_96H", model_read_aux=MODEL_AUX_VARS,model_use_vars=dict(proxyod550dust="od550dust",proxyod550so4="od550so4",proxyod550bc="od550bc",proxyod550nh4="od550nh4",proxyod550oa="od550oa",proxyod550ss="od550ss"),model_rename_vars=dict(od550dust="proxyod550dust",od550so4="proxyod550so4",od550bc="proxyod550bc",od550nh4="proxyod550nh4",od550oa="proxyod550oa",od550ss="proxyod550ss")),
    "IFS-Reanalysis": dict(model_id="ECMWF_CAMS_REAN", model_read_aux=MODEL_AUX_VARS),
    "IFS-Reanalysis-ctrl": dict(model_id="CAMS_REANCTRL", model_read_aux=MODEL_AUX_VARS),
    "IFS-Reanalysis-clim": dict(model_id="ECMWF_CAMS_REAN_clim", model_read_aux=MODEL_AUX_VARS
    ),
    "IFS-OSUITE-p": dict(model_id="ECMWF_OSUITEp", model_read_aux=MODEL_AUX_VARS),

**Comment by lewisblake** [comment]
Last step of the assembly wasn't going through properly. Running the last line in the parallel processing again fixed this.
