### ISSUE TITLE
EEA stations number drops from Jan 2022

### ISSUE THREAD

**Issue by andagit** [metno/pyaerocom#940]
From Dec2021 to Jan2022 no of EEA stations drop from 350 to 250 for PM10, but also by ~50 stations for PM25, O3 and NO2
![pm10-europe-2013-2023](https://github.com/metno/pyaerocom/assets/22189399/4ec1b6f1-13be-4107-8de0-7e91ea2b900a)
. Why?

**Comment by lewisblake** [comment]
Keep in mind that some countries may not have submitted yet.

**Comment by avaldebe** [comment]
maybe updating the `EEA.NRT` dataset for 2022 will include late submissions.

**Comment by avaldebe** [comment]
``` console
$ ls /lustre/storeB/project/aerocom/aerocom1/AEROCOM_OBSDATA/EEA_AQeRep.NRT/download/2022 | wc -w
14138

```
