### ISSUE TITLE
the name of pyaerocom's IPCFORESTS obs network rather ICPFORESTS

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#945]
that name is wrong:
https://github.com/metno/pyaerocom/blob/89501477f70e4d47ef994e7e2d71e6b37839683d/pyaerocom/data/paths.ini#L160

The correct name is `ICPFORESTS` (look at the first three characters)

I propose to allow both names and just call the very same reading classes

**Comment by lewisblake** [comment]
Sure, maybe throw a warning that if the user uses the wrong spelling, that they should use the correct one.

**Comment by jgriesfeller** [comment]
done
