### ISSUE TITLE
aeroval contour plotting: Does not support variable renaming

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#949]
for cams2-40 / task4041 we used this type of config (from json file) to use proxy variables:
```
"model_cfg": {
        "EMEP": {
            "model_id": "EMEP.cams2.40.p2",
            "model_ts_type_read": "daily",
            "model_read_aux": {},
            "model_use_vars": {
                "proxydryna": "dryna"
            },
            "model_rename_vars": {
                "dryna": "proxydryna"
            }
        },
```
to be usable with the aeroval web page, the files below the `contour` folder of the json file output need to use the renamed name (e.g. `proxydryna_EMEP.geojson`), but what is created is `dryna_EMEP.geojson`.

The problem is solvable with the renaming of the produced files...

**Comment by jgriesfeller** [comment]
for documentation:
Small one-liner that does the renaming for drydep variables:
```
for file in `find . -name '*json'`; do echo ${file}; newfile=$(echo ${file} | sed -e 's/dry/proxydry/g');mv ${file} ${newfile};done
```

**Comment by lewisblake** [comment]
Are you taking care of this or should we look into it?

**Comment by jgriesfeller** [comment]
duplicate to #902

**Comment by lewisblake** [comment]
Will address #902 and reference this issue there if needed
