### ISSUE TITLE
Custom regions.json for AerocomEvaluation (on experiment level)

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#95]
Is connected with new features related to region handling (cf. #90). Before only AeroCom default regions were used. Now, also countries can be used (and soon also groups of regions) in which case @AugustinMortier will highlight the countries directly using the country code (a feature that is available in highcharts) rather than having rectangular areas for the regions.

This will need the following changes in the backend:

- need to create regions.json on experiment level (i.e.   
*data_new/json/<proj_name>/<exp_name>/regions.json* instead of, as currently, a global one in *data_new/json/regions.json*
- Need to support rectangular regions as well as country codes as well as region groups in new regions.json, i.e. the following formats of regions specifications will be supported in *regions.json*: 

  - Rectangular: `{"WORLD": {"minLat": -90, "maxLat": 90, "minLon": -180, "maxLon": 180}, "EUROPE": {"minLat": 30, "maxLat": 80, "minLon": -20, "maxLon": 70}, ...}`
  - Individual countries: `{"Greece": "GR", "Australia" : "AU", ...}`
  - Grouped rectangular: `{"AFRICA": ["NAFRICA", "SAFRICA"], ...}`
  - Grouped countries: `{"Greece&Australia": ["GR", "AU"], ...}`

The last combination may be of particular interest to be combined, from a scientific point of view!

**Comment by jgliss** [comment]
@AugustinMortier and @hansbrenna I think it should work now. It will automatically create regions.json in experiment directory and checks - and updates - this, whenever a colocated NetCDF file is converted to json.

**Comment by AugustinMortier** [comment]
OK, I'm waiting for this new regions.json file. I have prepared something locally with a fake file. This should work with both single and grouped countries (hopefully)

**Comment by hansbrenna** [comment]
@AugustinMortier @jgliss I've re-run the test case, and it generated a regions.json file in the correct place. I've pushed it to the web repository. 

Running the web site locally didn't work though.

**Comment by jgliss** [comment]
Great @hansbrenna @AugustinMortier can you check? Or is there any action needed from my side?

**Comment by AugustinMortier** [comment]
@jgliss @hansbrenna 
I'm working on it. I see that the 'WORLD' region is missing in the new hm/glob_stats.json files. We still need it, even though we might rename in the case of CAMS61 (Europe) on the front side..

**Comment by jgliss** [comment]
@AugustinMortier okay, but then it would be a mix of region definitions in the regions.json (i.e. some are coutnry codes, others, like WORLD, rectangular). Would that be okay?

**Comment by AugustinMortier** [comment]
I think it will work. Or, we can have something like
{"WORLD": ["GR", "AU", "NO", "FR", ...], ...}

**Comment by jgliss** [comment]
Hmm, will need to think but since WORLD, by definition, is a rectangular region covering the whole globe, the filtering in the backend really takes all sites / coordinates that fall into that rectangle. At least that is what the name WORLD implies, right (thinking also of satellite colocation, where we have the oceans etc.)? If we want a combined country filter for CAMS61 (e.g. really all countries available), we could name it ALL or so and make it a grouped filter (which is coming soon.). What do you think?

**Comment by AugustinMortier** [comment]
okay, I didn't think about the oceans. Let's keep the rectangle for the WORLD now, and I'll make sure the combination of coutnries and rectangles works on the website

**Comment by jgliss** [comment]
@AugustinMortier @hansbrenna WORLD is now added to regions.json and also, both daily and monthly heatmap json files should be created (cf #97). I pushed in data_new cams61 exp. test-regions. Can you test?

**Comment by AugustinMortier** [comment]
It works ;)

**Comment by AugustinMortier** [comment]
I'm already triggering an event so it's trying to read the regional time series when you hover a bar in the regional chart. If a file is produced for the regions as it is for the stations, it should work straight away. I'm using the country names (and not the country codes) in this case.

**Comment by jgliss** [comment]
Great!! Thanks for feedback. I'm on the regional timeseries now!

**Comment by AugustinMortier** [comment]
Just a detail, but as we show the regions in the order it appears in the heatmap file, maybe we want the WORLD region to be the first one..? (Now it's the last one)

**Comment by jgliss** [comment]
Is it? Okay, will check
