### ISSUE TITLE
Restore default colormaps

### ISSUE THREAD

**Issue by AugustinMortier** [metno/pyaerocom#953]
The [new default colormaps](pyaerocom/aeroval/glob_defaults.py) include too many steps in the colorscales which cause several display problems. The maximum number of levels should be around 10 in order for the legend to be properly displayed, and for the maps to not be too heavy with too many polygons. This should be high priority since this affects all projects.

**Comment by lewisblake** [comment]
`ang4487aer, od550aer, od550lt1aer, od550gt1aer, od550dust, concNnh4`
