### ISSUE TITLE
Accommodate newer versions of dependencies 

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#955]
Currently: 
- pandas<=1.5.3
- xarray<=2022.10.0

Breaking changes mean we need to rewrite some of the code to accommodate these updates.

**Comment by Ovewh** [comment]
This makes it difficult to install pyaerocom in other conda enviroments. I'm attempting to use pyaerocom in a course but these requirement makes it not compatible with the pangeo conda enviroment, which i would like to use.

Could it be a milestone of this month?

**Comment by Ovewh** [comment]
#845

**Comment by lewisblake** [comment]
@Ovewh Is it a specific package that causes the problem or both?

**Comment by Ovewh** [comment]
> @Ovewh Is it a specific package that causes the problem or both?

Xarray, but Pandas is a dependency of Xarray i guess the they are two sides of the same coin.

**Comment by heikoklein** [comment]
blocked by #1141 
blocked by #1140

**Comment by thorbjoernl** [comment]
Fixed by https://github.com/metno/pyaerocom/pull/1151
