### ISSUE TITLE
Add regional time-series data as json files in AerocomEvaluation for each region

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#96]
Closely linked with #90, #95. 

Add one time-series json file for each region in web evaluation.

- requires computation of regional timeseries for each region (not yet available in pyaerocom).
- corresponding json file with region name (as site location) will be saved under *ts* subdir in experiment directory.

**Comment by jgliss** [comment]
@hansbrenna @AugustinMortier This is done (and pushed into proj. cams61, exp. test-regions). Can anyone check and confirm that it works (not sure where I would see the regional timeseries).

**Comment by AugustinMortier** [comment]
it works!

![Screenshot from 2020-04-30 18-15-18](https://user-images.githubusercontent.com/19610522/80734039-d9512c00-8b0e-11ea-87bf-4b74d02778d1.png)

**Comment by jgliss** [comment]
Nice way to go into the long weekend :)
