### ISSUE TITLE
Integrate pyaro into pyaerocom

### ISSUE THREAD

**Issue by dulte** [metno/pyaerocom#977]
#976

**Comment by dulte** [comment]
Pyaerocom can as of this read and colocate pyaro. I've written tests for reading, and is working on tests for colocation

**Comment by dulte** [comment]
@lewisblake, @heikoklein. I've not made any checks for if the user has made a Pyaro reader that uses the same data id as the one pyaerocom readers. This might cause some error/confusion reading. Should I make such a check, or do we assume that this will not happen? (E.g. by removing all readers internal to pyaerocom)

**Comment by lewisblake** [comment]
I would suggest putting a check until we actually have removed all readers internal to pyaerocom (if  it does indeed get implemented). Better to put in some safety measures than assume someone knows all of this.

**Comment by dulte** [comment]
@lewisblake , I've added you as a reviewer to the pyaro interface PR. It is 90% done, so it is a good time to start looking at it. In the comment below I'll add a list over things features I've yet to add

**Comment by dulte** [comment]
Metadata to get from Pyaro, if possible. Needed for complete Station metadata:
- instrument name
- station_id?
- filename
- revision date
- data level
- PI


Optimalization
- Make code faster...

Features to check
- ts_type (freq)

**Comment by heikoklein** [comment]
PI and instrument name are a good extension for pyaro station-metadata.
filename make no sense in most cases, it is just a way of packing which might not even exist.
Not sure what data level should be.

**Comment by dulte** [comment]
I've now added code that simply checks if the metadata names above are fields in the Station object. If not it will fill in the same default that readungridded uses (mostly None)

**Comment by dulte** [comment]
New changes (list of configs) are not yet tested with PyAeroval. I will test this next week. After that the PR should be ready on my side

**Comment by dulte** [comment]
I've written a couple more tests, and tested the implementation with pyaeroval. Everything seems to work, and the tests passes. There will guaranteed be more bugs, I've yet to find them... So as of now, I think the implementation is ready

**Comment by dulte** [comment]
Now merged
