### ISSUE TITLE
No PM10 stations available for GB since 2021 for CAMS2_82

### ISSUE THREAD

**Issue by andagit** [metno/pyaerocom#989]
I have raised this issue before (see issue: #940), but perhaps not clear enough.
It is peculiar that CAMS2_83 can show stats for GB stations for 2023, but CAMS2_82 can not - 
I realise that the projects are reading different data, but the origin is EEA for both.
I also claim that there are data for GB in our database EEA_AQeRep.NRT/:
2022: 17 stations
2023: 17 stations
2024: 16 stations 
For 2024 it is only until 19.jan currently for GB stations, but for the other years I can not see any missing data
in those files for GB_5*

**Comment by avaldebe** [comment]
Some of the 2024 stations are getting new data.

``` console
$ for F in  GB_*; do tail -1 $F | cut -d, -f9,11,13-14; done | sort -u | 'grep' 2024-02
CO,hour,mg/m3,2024-02-05 03:00:00 +01:00
CO,hour,mg/m3,2024-02-06 16:00:00 +01:00
CO,hour,mg/m3,2024-02-06 19:00:00 +01:00
NO2,hour,µg/m3,2024-02-05 01:00:00 +01:00
NO2,hour,µg/m3,2024-02-05 02:00:00 +01:00
NO2,hour,µg/m3,2024-02-05 12:00:00 +01:00
NO2,hour,µg/m3,2024-02-05 13:00:00 +01:00
NO2,hour,µg/m3,2024-02-05 14:00:00 +01:00
NO2,hour,µg/m3,2024-02-05 16:00:00 +01:00
NO2,hour,µg/m3,2024-02-05 18:00:00 +01:00
NO2,hour,µg/m3,2024-02-06 01:00:00 +01:00
NO2,hour,µg/m3,2024-02-06 02:00:00 +01:00
NO2,hour,µg/m3,2024-02-06 09:00:00 +01:00
NO2,hour,µg/m3,2024-02-06 11:00:00 +01:00
NO2,hour,µg/m3,2024-02-06 12:00:00 +01:00
NO2,hour,µg/m3,2024-02-06 14:00:00 +01:00
NO2,hour,µg/m3,2024-02-06 15:00:00 +01:00
NO2,hour,µg/m3,2024-02-06 16:00:00 +01:00
NO2,hour,µg/m3,2024-02-06 19:00:00 +01:00
O3,hour,µg/m3,2024-02-05 14:00:00 +01:00
O3,hour,µg/m3,2024-02-05 15:00:00 +01:00
O3,hour,µg/m3,2024-02-05 18:00:00 +01:00
O3,hour,µg/m3,2024-02-06 01:00:00 +01:00
O3,hour,µg/m3,2024-02-06 11:00:00 +01:00
O3,hour,µg/m3,2024-02-06 12:00:00 +01:00
O3,hour,µg/m3,2024-02-06 14:00:00 +01:00
O3,hour,µg/m3,2024-02-06 15:00:00 +01:00
O3,hour,µg/m3,2024-02-06 16:00:00 +01:00
O3,hour,µg/m3,2024-02-06 17:00:00 +01:00
O3,hour,µg/m3,2024-02-06 19:00:00 +01:00
PM10,hour,µg/m3,2024-02-05 17:00:00 +01:00
PM10,hour,µg/m3,2024-02-06 14:00:00 +01:00
PM10,hour,µg/m3,2024-02-06 16:00:00 +01:00
PM10,hour,µg/m3,2024-02-06 19:00:00 +01:00
PM2.5,hour,µg/m3,2024-02-05 12:00:00 +01:00
PM2.5,hour,µg/m3,2024-02-05 13:00:00 +01:00
PM2.5,hour,µg/m3,2024-02-06 16:00:00 +01:00
PM2.5,hour,µg/m3,2024-02-06 19:00:00 +01:00
SO2,hour,µg/m3,2024-02-06 11:00:00 +01:00
SO2,hour,µg/m3,2024-02-06 14:00:00 +01:00
SO2,hour,µg/m3,2024-02-06 15:00:00 +01:00
SO2,hour,µg/m3,2024-02-06 16:00:00 +01:00
SO2,hour,µg/m3,2024-02-06 19:00:00 +01:00
```

Should I re-download the 2022 and 2023 GB stations?

**Comment by avaldebe** [comment]
> Should I re-download the 2022 and 2023 GB stations?

I downloaded all 2022 and 2023 GB stations and there is no new data.

**Comment by avaldebe** [comment]
looks like the station metadata has changed a lot since the last time it was updated

``` console
$ cd /lustre/storeB/project/aerocom/aerocom1/AEROCOM_OBSDATA/EEA_AQeRep.NRT/
$ wget http://discomap.eea.europa.eu/map/fme/metadata/PanEuropean_metadata.csv
$ wc -l renamed/metadata.csv PanEuropean_metadata.csv
   67257 renamed/metadata.csv
   69272 PanEuropean_metadata.csv
```

**Comment by avaldebe** [comment]
should I update the metadata file?

**Comment by avaldebe** [comment]
> should I update the metadata file?

I updated the metadata files on storeA/B, hope it helps

``` console
$ wc -l /lustre/store?/project/aerocom/aerocom1/AEROCOM_OBSDATA/EEA_AQeRep.NRT/download/metadata.csv
   69274 /lustre/storeA/project/aerocom/aerocom1/AEROCOM_OBSDATA/EEA_AQeRep.NRT/download/metadata.csv
   69274 /lustre/storeB/project/aerocom/aerocom1/AEROCOM_OBSDATA/EEA_AQeRep.NRT/download/metadata.csv
```

**Comment by jgriesfeller** [comment]
The location of a stations is only noted in the metadata file. So it's vital to have that up to date. Without it, the station's data cannot be read.
https://github.com/metno/pyaerocom/blob/f8596b2cca36bf53226d1f224c95a01564888b2b/pyaerocom/io/read_eea_aqerep_base.py#L678-L682

**Comment by jgriesfeller** [comment]
After @andagit complained again today about the missing stations, I checked the existing 17 stations for 2023 against the metadata file.
It turned out that all stations had a station classification of either `urban-background` or `urban-traffic`. 

The problems is that in our config file we have the following station classification we accept:
```
"area_classification": [
          "rural",
          "rural-nearcity",
          "rural-regional",
          "rural-remote"
        ]
```
So basically none of the british stations match our classification criteria.
Another way of looking at it is that the UK does not submit rural stations anymore.

**Comment by andagit** [comment]
Just for the record - from EEA we got no. of stations from GB:
2015: 85, 2016: 77, 2017: 76, 2018: 70, 2019: 89, 2020: 34 (brexit,Corona), 2021: 90 (last v2), 2022: 17, 2023: 17

**Comment by andagit** [comment]
So could report back to ECMWF (Richard Engelen)/CAMS2_82 about the lack of GB stations.
