### ISSUE TITLE
Create Documentation for NorESM Tutorial Session

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#990]
**Describe a problem and/or suggest an improvement**
 - Something incorrect or unclear in the documentation?
      - Documentation might be outdated.
 - Something should be added to the documentation?
      - New best methods and descriptions of updated flags in config files should be included. 
 - Something should be removed from the documentation?
      - Outdated config files and examples which don't work removed. 
 - Something should be re-structured in the documentation?
      - No, structure is fine. 
 - Suggest a Q&A for the FAQ?

**Additional context**
NorESM folks would like to run Pyaeroval, so updated documentation for a tutorial is needed. Tutorial session to be planned before Easter.

**Comment by dulte** [comment]
In progress. Invitations sent out for week before easter. 

I'm writting new tutorials for installation, "tour of Aerotools", reading models and observations, colocation, and finally PyAeroval. I will make own tutorial for the NorESM, which is a compact summary of these tutorials. This can be used later as a general intro to Aerotools, with the other tutorials being more indepth.
