### ISSUE TITLE
CI crashing due to linters and FileNotFoundError

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#996]
CI has not been passing on GitHub lately despite passing tests locally. Provided are some examples of failing tests.

1. [FileNoteFoundError](https://github.com/metno/pyaerocom/actions/runs/7873616902/job/21481384525#step:8:372)
2. [Linters](https://github.com/metno/pyaerocom/actions/runs/7871920240/job/21476122365?pr=993)
     a. PR attempting to address the linting issue with black 24.1.1: #995

**Comment by charlienegri** [comment]
the full error is  `FileNotFoundError: Input location /home/runner/MyPyaerocom/tmp could not be accessed`
this comes from `const.add_data_search_dir(tmpdir)` in `make_dummy_model` in `pyaerocom/aeroval/helpers.py`,  
and `add_data_search_dir` is defined as:

```
    def add_data_search_dir(self, *dirs):
        """Add data search directories for database browsing"""
        for loc in dirs:
            if not self._check_access(loc):
                raise FileNotFoundError('Input location {} could not be accessed'
                                        .format(loc))
            self._search_dirs.append(loc)
```

(where `_check_access` uses `check_dir_access` from `pyaerocom/_lowlevel_helpers.py`:

```
def check_dir_access(path):
    """Uses multiprocessing approach to check if location can be accessed

    Parameters
    ----------
    loc : str
        path that is supposed to be checked

    Returns
    -------
    bool
        True, if location is accessible, else False
    """
    if not isinstance(path, str):
        return False

    return os.access(path, os.R_OK)
```
)
so, whatever the reason why this fails in CI and not locally must be OS specific, 
w̶h̶a̶t̶ ̶i̶f̶ ̶w̶e̶ ̶a̶d̶d̶ ̶a̶ ̶o̶s̶.̶m̶a̶k̶e̶d̶i̶r̶s̶(̶t̶m̶p̶d̶i̶r̶,̶ ̶e̶x̶i̶s̶t̶_̶o̶k̶=̶T̶r̶u̶e̶)̶?̶     <--- this is useless, nvm

**Comment by avaldebe** [comment]
the linting on `main-dev` passes without problems
https://github.com/metno/pyaerocom/actions/runs/7900657530/job/21562628021

**Comment by avaldebe** [comment]
it is failing to uncompres the test dataset
https://github.com/metno/pyaerocom/actions/runs/7900876585/job/21563318733#step:8:69
```
self = <pyaerocom.config.Config object at 0x7feee58ade50>
dirs = ('/home/runner/MyPyaerocom/tmp',), loc = '/home/runner/MyPyaerocom/tmp'

    def add_data_search_dir(self, *dirs):
        """Add data search directories for database browsing"""
        for loc in dirs:
            if not self._check_access(loc):
>               raise FileNotFoundError(f"Input location {loc} could not be accessed")
E               FileNotFoundError: Input location /home/runner/MyPyaerocom/tmp could not be accessed
```

**Comment by avaldebe** [comment]
the error can be reproduced locally after deleting the `testdata-minimal` and the temporary file
``` console
$ rm -fr ~/MyPyaerocom/tmp/ ~/MyPyaerocom/testdata-minimal
$ tox -e py -- tests/aeroval/test_helpers.py::test_make_dummy_model[cfgexp1] -vv
...
FAILED tests/aeroval/test_helpers.py::test_make_dummy_model[cfgexp1] - FileNotFoundError: Input location /home/alvarov/MyPyaerocom/tmp could not be accessed
```

rerunning the test will work
``` console
$ tox -e py -- tests/aeroval/test_helpers.py::test_make_dummy_model[cfgexp1] -vv
...
tests/aeroval/test_helpers.py::test_make_dummy_model[cfgexp1] PASSED         [100%]
```

**Comment by charlienegri** [comment]
this does not make sense, `const.add_data_search_dir(tmpdir)` is convoluted but should not fail?
